### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by k3v1nwrld** [whoeevee/EeveeSpotify#1]
Hey, i tried compiling the tweak by myself, but got some weird errors. Used an ios 14.5 sdk, since i dont have a 14.0 sdk. Could you release a precompiled deb?? Thanks!

**Comment by binnichtaktiv** [comment]
yea pls its annoying to build every time
![IMAGE 2024-04-21 10:24:21](https://github.com/whoeevee/EeveeSpotify/assets/96953964/f79747ce-1709-4b4e-a2fa-0f78f93f8ce7)

**Comment by k3v1nwrld** [comment]
> yea pls its annoying to build every time ![IMAGE 2024-04-21 10:24:21](https://private-user-images.githubusercontent.com/96953964/324233752-f79747ce-1709-4b4e-a2fa-0f78f93f8ce7.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2ODgyNDUsIm5iZiI6MTcxMzY4Nzk0NSwicGF0aCI6Ii85Njk1Mzk2NC8zMjQyMzM3NTItZjc5NzQ3Y2UtMTcwOS00YjRlLWEyZmEtMGY3OGY5M2Y4Y2U3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIxVDA4MjU0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3OTE4OTEyM2I3MTNkNDc0OTE2NWNlMzBmNzMxNTQ4ZWM2YTkxOTkxYjExMGI0NjZmYzVlMjQwNGI0MjZmN2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0gBMlmrhEVb-85A0GgfX0pfgShrFVbImdGCeQxy-Uvg)

I managed to compile it using github actions. Idk how useful that is if you're trying to change the code tho, since it takes like 4 minutes to compile

**Comment by whoeevee** [comment]
There were releases, but I had to delete them because of an issue with Orion. The rootless (arm64) tweak works, as well as the one you built with Github Actions. However, when injecting the rootful tweak into the ipa, the app crashes while hooking URL. Despite trying to fix it by reinstalling Theos and rebuilding Orion, I couldn't resolve it, and this bug persists in the latest Orion version.

The tweak ended up being rewritten in Objective-C. I'm now waiting for the pull request, and once ObjC version is pushed, I'll upload all the releases.

**Comment by binnichtaktiv** [comment]
> There were releases, but I had to delete them because of an issue with Orion. The rootless (arm64) tweak works, as well as the one you built with Github Actions. However, when injecting the rootful tweak into the ipa, the app crashes while hooking URL. Despite trying to fix it by reinstalling Theos and rebuilding Orion, I couldn't resolve it, and this bug persists in the latest Orion version.
> 
> The tweak ended up being rewritten in Objective-C. I'm now waiting for the pull request, and once ObjC version is pushed, I'll upload all the releases.

Oh okay my bad.. thanks

**Comment by asdfzxcvbn** [comment]
> However, when injecting the rootful tweak into the ipa, the app crashes while hooking URL. Despite trying to fix it by reinstalling Theos and rebuilding Orion, I couldn't resolve it, and this bug persists in the latest Orion version.

sorry guys that one was my fault LMAO
