### ISSUE TITLE
If possible, make it possible for Spotify links to open Spotify application.

### ISSUE THREAD

**Issue by TeaselUwU** [whoeevee/EeveeSpotify#101]
It’s more of a feature request to be exact, I’ve tried to join my friend’s Jam (she has premium) and after clicking the link, I was directed to the App Store. Similarly goes for albums/singles when you open them via Google, it directs to the website player. I think it would be a nice little feature if it could be implemented. (:

**Comment by yodaluca23** [comment]
It's an entitlement issue, if you install with TrollStore is will work. There are work arounds like using opener.

**Comment by whoeevee** [comment]
I’ve updated EeveeSpotify and OpenSpotifySafariExtension. In version 3.1, you can open any links in the app, including Jams. It basically opens the links like the official app opens app links, and it works perfectly. Wait for the release

**Comment by whoeevee** [comment]
3.1 is out

**Comment by DimaSheiko** [comment]
> I’ve updated EeveeSpotify and OpenSpotifySafariExtension. In version 3.1, you can open any links in the app, including Jams. It basically opens the links like the official app opens app links, and it works perfectly. Wait for the release

Is it possible to make it work from other applications and not only from safari? For example from Shazam, when you hit the "open in spotify" button it opens safari, but it opens the Spotify home page and not the music in particular, so you lose what you want to search for which is the specific music. It would be great if you could open directly from other apps without having to open safari.
