### ISSUE TITLE
Lost Likes

### ISSUE THREAD

**Issue by LPCC12** [whoeevee/EeveeSpotify#102]
My app is desynced with my actuall liked songs. I have 2500+ Liked songs and only shows 294. Reseting data didn't fix it and reinstalling with latest version didn't do it. By going on pc i can see all liked songs and if i like a song on ios it overlaps in pc view. Might be a Spotify Bug!? Searching online i find no similar results.

**Comment by yodaluca23** [comment]
This is a native Spotify mobile app issue.

**Comment by asdfzxcvbn** [comment]
please test in spotify app from the appstore @LPCC12

**Comment by LPCC12** [comment]
Spotify in app store as same issue, contacted their support. Even with cache cleared, clean installation and backdoor tinkering it still has the same problem. Might be from my phone or something...

**Comment by asdfzxcvbn** [comment]
i’ve actually seen quite a few people with this problem and it seems to be a stock spotify app issue, closing
