### ISSUE TITLE
Request Make the Reload userdata Pop up dark 

### ISSUE THREAD

**Issue by lolipop88** [whoeevee/EeveeSpotify#104]
As the title says it would be great if you could change the color of the from white to dark as this is extremely bright when it is late

**Comment by whoeevee** [comment]
nice feature
dark popups option will be in release version 3.1

**Comment by Finealex** [comment]
> dark popups option will be in release version 3.1

Do you know what will be the eta for 3.1?

**Comment by whoeevee** [comment]
3.1 is out
