### ISSUE TITLE
Spotify crashes right after it downloads lyrics

### ISSUE THREAD

**Issue by Adam-Karol** [whoeevee/EeveeSpotify#106]
Only on some songs app crashes right after it downloads lyrics. You can see the lyrics only for a split second and then it crashes. Crashes only when using LRCLIB or Musixmatch, Genius works fine.
Sample song: Kendrick Lamar, Not Like Us
Sideloaded on iPhone 12, iOS 16.0 using TrollStore 2.0.15
EeveeSpotify version Swift 3.0

**Comment by whoeevee** [comment]
this song doesn’t lead to crash for me
install debug IPA and send the crashlog

**Comment by Adam-Karol** [comment]
[Spotify-2024-05-14-233750.txt](https://github.com/whoeevee/EeveeSpotify/files/15314015/Spotify-2024-05-14-233750.txt)

**Comment by whoeevee** [comment]
thanks for sharing, but it’s a weird crash log. I can’t figure out the reason why it crashes, and I don’t even see that EeveeSpotify was loaded. Is that right/latest crash log?

**Comment by Adam-Karol** [comment]
yes it is for sure the right crash log. I’m also not sure why it happens. Sometimes it is not crashing on this song and sometimes it crashes on others. Here is other crash log, maybe it will be more helpful 
[Spotify-2024-05-16-134906.txt](https://github.com/whoeevee/EeveeSpotify/files/15334806/Spotify-2024-05-16-134906.txt)

**Comment by Adam-Karol** [comment]
@whoeevee I just used BrowserStack to emulate iPhone in cloud and it crashed also there. Here is crash log: 
[Spotify-2024-05-16-223556.txt](https://github.com/whoeevee/EeveeSpotify/files/15341686/Spotify-2024-05-16-223556.txt)

**Comment by whoeevee** [comment]
Unfortunately, I cannot figure out the reason for the crash or reproduce the issue. It works fine for me and many others. In your case, there is a method during the call to the crash occurs. If you can see the lyrics for a split second, it means they have successfully loaded, and the tweak worked fine. Maybe you should install Dopamine jailbreak with the EeveeSpotify tweak and Spotify from the App Store?

**Comment by Adam-Karol** [comment]
I just installed dopamine. How can I install your Spotify tweak there?

**Comment by whoeevee** [comment]
install eeveespotify and swiftprotobuf arm64 debs (share them to Sileo)

**Comment by Adam-Karol** [comment]
I installed everything and it still crashes 
[Spotify-2024-05-20-001119.txt](https://github.com/whoeevee/EeveeSpotify/files/15370970/Spotify-2024-05-20-001119.txt)

**Comment by whoeevee** [comment]
I see a significant number of reports, and I still cannot figure out why it crashes at random times

**Comment by Steppen-wolf** [comment]
Hi,
I’m having the same use. 
I tested the app with Genius and Musixmatch Lyrics without crash. Only when I use LRCLIB. It is possible to solve this trouble?

**Comment by whoeevee** [comment]
> Hi, I’m having the same use. I tested the app with Genius and Musixmatch Lyrics without crash. Only when I use LRCLIB. It is possible to solve this trouble?

what’s your device and iOS version?

**Comment by Steppen-wolf** [comment]
iPhone XR iOS 17.5

**Comment by asdfzxcvbn** [comment]
please test v4.0

**Comment by asdfzxcvbn** [comment]
@Adam-Karol please test v4.0 before this issue is closed for inactivity
