### ISSUE TITLE
[Feature Suggestion] Option to hide pods in eevee settings

### ISSUE THREAD

**Issue by gototheskinny** [whoeevee/EeveeSpotify#107]
This would be awesome. 
If it's not possible or hard to do add in to the options, ipa with this option would be awesome too.
The tweak that I'm talking about:
[https://www.idownloadblog.com/2021/06/10/spotifynopodcasts/](https://www.idownloadblog.com/2021/06/10/spotifynopodcasts/)

**Comment by asdfzxcvbn** [comment]
will not be implemented

**Comment by gototheskinny** [comment]
> will not be implemented

I don't wanna open another issue for this, I wanna ask you this, is there a way to add this feature back to Spotify? It's not there for me for months...
SS of the feature : 

<details>
  <summary>This one</summary>
  
 ![image](https://github.com/whoeevee/EeveeSpotify/assets/51786709/2f4d48d8-472f-4d7a-9c9f-1210f14d44c5)
  
</details>
