### ISSUE TITLE
Hide the method of bypassing Spotify premium

### ISSUE THREAD

**Issue by astroumi** [whoeevee/EeveeSpotify#11]
Hi, first of all many thanks for making this.

Just a suggestion but I thought it might be best to not advertise the method of bypassing Spotify’s premium check through patching offline.bnk as shown in the readme. 

If Spotify were to see this they might release an update to prevent this from happening and we all lose our Spotify “premium”?

**Comment by Bombproofmoth** [comment]
yeah i agree you should definitely keep it to yourself!

**Comment by asdfzxcvbn** [comment]
the tweak is open source anyway. it's practically easily patchable.
