### ISSUE TITLE
Musixmatch has stopped working

### ISSUE THREAD

**Issue by Kalamardo69** [whoeevee/EeveeSpotify#110]
Well, that, musixmatch has stopped working for me, it appears that I have already reached the monthly limit or that this letter is not available, genius and LRCLIB do work well
Iphone 13, iOS 17.4

**Comment by whoeevee** [comment]
does musixmatch work for you?
can you search lyrics in it?

**Comment by Kalamardo69** [comment]
The musixmatch app works well, but the musixmatch setting has stopped working for me, from update 3.0 until today it worked well for me but no longer

**Comment by whoeevee** [comment]
did you try to update the token in EeveeSpotify settings?

**Comment by Kalamardo69** [comment]
I have deleted the token and I have put it back on, it has not worked for me, I have uninstalled musixmatch and I have reinstalled it and I have put the token back in case but it still does not work for me

**Comment by whoeevee** [comment]
Open Musixmatch, go to settings > Get help > Copy debug info, paste it somewhere, select the token, and paste it in EeveeSpotify settings. It doesn’t work, and you see original Spotify lyrics for all the songs, right?

**Comment by trevmont65** [comment]
Works for me but I just started using it

**Comment by Kalamardo69** [comment]
Es lo que he estado haciendo pero ya no me funciona

**Comment by alany08** [comment]
I'm getting the same thing, I've tried my user token and also an API token already

**Comment by fugegate** [comment]
Use the premium version, I've had no issues

**Comment by Kalamardo69** [comment]
At the moment putting the premium token does work for me.

**Comment by fugegate** [comment]
> At the moment putting the premium token does work for me.

See issue #79 I have made a tutorial for free premium Musixmatch

**Comment by Kalamardo69** [comment]
It's what I've done to have the premium, and at the moment everything works well.
