### ISSUE TITLE
Spotify crashes when opening on iOS 14.8.1

### ISSUE THREAD

**Issue by TwoJayCee** [whoeevee/EeveeSpotify#112]
Hello,

I’ve installed the latest .ipa file on my iPhone X on iOS 14.8.1 via TrollStore.

However, the app crashes instantly upon launching. If the version of Spotify is too high, can a downgraded version be uploaded for those on older iOS versions?

Thank You,

Also, does the .ipa have Apple CarPlay entitlements?

**Comment by whoeevee** [comment]
The latest Spotify IPA requires iOS 15, while EeveeSpotify requires iOS 14.

I would install Taurine jailbreak and EeveeSpotify tweak with the latest available Spotify version for iOS 14 from the App Store. You can also get the latest available Spotify IPA and inject EeveeSpotify, SwiftProtobuf, and Orion into it to install with TrollStore.

The IPA on GitHub Releases has all the entitlements, and CarPlay should work if you install it using TrollStore.
