### ISSUE TITLE
Empty Lyrics

### ISSUE THREAD

**Issue by fugegate** [whoeevee/EeveeSpotify#114]
https://github.com/whoeevee/EeveeSpotify/assets/46111388/a004f81c-28cb-46e5-8fa8-1ffa4b6d07bf

**Comment by fugegate** [comment]
also while the color issues are somewhat fixed, the colors for the lyrics still are washed out and the same as the original from Spotify

**Comment by whoeevee** [comment]
You may see empty lyrics in rare cases if, for example, the tweak picks an instrumental version from LRCLIB or there are unreleased lyrics on Genius. EeveeSpotify 3.1 has improved song search algorithm. I've just tested it, and this song has the correct lyrics in 3.1.

I also improved lyrics colors in 3.1 to not look washed out and more like the original. Wait for the release.
