### ISSUE TITLE
Change the colors

### ISSUE THREAD

**Issue by FredGithubYEAH** [whoeevee/EeveeSpotify#116]
I’m not a big fan of the lyrics colors being “normalized”
Is there a way to change it back to original colors and if not could you add that as feature Please and Thank you

**Comment by fugegate** [comment]
> I’m not a big fan of the lyrics colors being “normalized”
> 
> Is there a way to change it back to original colors and if not could you add that as feature Please and Thank you 

Check out issue #114

**Comment by FredGithubYEAH** [comment]
Oh ok Thanks 👍
