### ISSUE TITLE
Spotify resetting to free subscription

### ISSUE THREAD

**Issue by crustycean** [whoeevee/EeveeSpotify#118]
A few seconds after installing and eeveespotify being applied, Spotify goes into reload animation and reverts to free subscription: Premium tab shows up in bottom menu, account settings page shows free plan, and the occasional premium pop up shows up. Premium features have been working fine though, I can still skip, play any song, no audio ads, etc. Restarting the app doesn't get rid of the premium button, and even deleting and reinstalling didn't. I also don't get the pop up saying Spotify reloaded data and the button to reset data/restart. Overall not an app breaking issue at all (since the app features work as intended), just wanted to bring it up in case you would like to investigate it further.

**Comment by crustycean** [comment]
![image](https://github.com/whoeevee/EeveeSpotify/assets/170390156/c14c9b9a-f8d2-4c94-af6a-12a9b5c4f19b)
![image](https://github.com/whoeevee/EeveeSpotify/assets/170390156/c2c3098a-ce48-4848-9b92-dbccbaba5703)

**Comment by crustycean** [comment]
I'm on iOS 16.6.1 and using a repack of eeveespotify + spotilife (unfortunately spotilife seems to not be compatible, currently waiting for my app IDs to expire). I've tried using the vanilla 3.0 eeveespotify ipa and it has the same issue.

**Comment by crustycean** [comment]
> I'm on iOS 16.6.1 and using a repack of eeveespotify + spotilife (unfortunately spotilife seems to not be compatible, currently waiting for my app IDs to expire). I've tried using the vanilla 3.0 eeveespotify ipa and it has the same issue. 

*sorry i meant eevee + sposify

**Comment by asdfzxcvbn** [comment]
yeah it happens to me too, however making the premium persistent is really difficult, i’ve already looked into it however i can’t find any info about the struct that spotify uses to determine active features

likely won’t be fixed. maybe one day.
