### ISSUE TITLE
Remove Download Popup for Local File Playlists

### ISSUE THREAD

**Issue by BB4LIFE** [whoeevee/EeveeSpotify#121]
Can you remove the popup you added in Swift 1.3 when selecting to download playlists or at least remove it for playlists with only local files? The problem I am having is that I sync my local files from my Desktop, but I can't "download" them from my PC. This is a free feature, so anyone can use the download button for local file playlists.

**Comment by whoeevee** [comment]
might look into this in next update

**Comment by asdfzxcvbn** [comment]
huh? you have to “download” stuff that’s already on your phone?

anyway, you can just turn on Do Not Patch Premium, download the playlist, then turn the tweak back on

**Comment by BB4LIFE** [comment]
Yeah I'll do that. What I meant is download files from my PC by syncing it over Wi-Fi. However, in order to that I have to click the download playlist button.
