### ISSUE TITLE
Disable Premium For Those That Have It

### ISSUE THREAD

**Issue by TheNightRider12** [whoeevee/EeveeSpotify#127]
Would it be possible to disable the premium spoofing for those that have premium? I would like to use the other aspects of the tweak. However, I am not able to download and all of that despite me having premium but the tweak still spoofing it causing downloads, etc., not to work.

**Comment by yodaluca23** [comment]
> Then why do you need the tweaked Spotify?

Probably different lyric providers.

**Comment by whoeevee** [comment]
will look into it in the next update

**Comment by asdfzxcvbn** [comment]
implemented in v4.0
