### ISSUE TITLE
Add option to trigger "Spotify Reloaded" pop up manually

### ISSUE THREAD

**Issue by crustycean** [whoeevee/EeveeSpotify#129]
Could you maybe add a button to manually trigger the pop up for restarting the app/reset data? After a while my ipa reverts to showing the premium menu tab but doesn't show the pop up and thought this could just be a potential fix.

**Comment by samuelawachie** [comment]
Just restart the app yourself. That pop-up is triggered when user-data changes. If you restart the application yourself, you’re achieving the same functionality. 
Unless I’m totally wrong..

**Comment by whoeevee** [comment]
I will probably implement reset data option in the next update

**Comment by asdfzxcvbn** [comment]
implemented in v4.0
