### ISSUE TITLE
Songs don't play/skip themselves

### ISSUE THREAD

**Issue by JaredHared2** [whoeevee/EeveeSpotify#13]
Sometimes, whether in albums or playlists, songs will skip themselves/not play.  I haven't seen any rhyme or reason; it just happens.  I'm on the latest release, and most of the "common fixes" haven't worked.

**Comment by asdfzxcvbn** [comment]
so making a new account hasnt worked? what about a vpn to america?

**Comment by JaredHared2** [comment]
Huh, I guess I should try those  
That's my bad, sorry about that and probably wasting your time 💀
