### ISSUE TITLE
Spotify randomly crashing when loading lyrics

### ISSUE THREAD

**Issue by kvse** [whoeevee/EeveeSpotify#130]
Sometimes when i tap on the bottom to bring up the full screen player and it tries to load lyrics it just crashes. This happens a lot and seemingly randomly as it’ll crash on a song but when i reopen the app and play the same song it loads the lyrics just fine. Only crashes when using Musixmatch or lrclib for lyrics.

**Comment by asdfzxcvbn** [comment]
#106
