### ISSUE TITLE
Spotify randomly stop playing 

### ISSUE THREAD

**Issue by lolipop88** [whoeevee/EeveeSpotify#132]
![IMG_8187](https://github.com/whoeevee/EeveeSpotify/assets/75317057/c3c1faf1-3f80-4f5e-be75-085038a4fb06)
 Instead of continuing playing the playlist it just turns into this black bar 

maybe I am the only one who has this issue 

Thank you for the dark pop ups 🙏

**Comment by trevmont65** [comment]
I get it too

**Comment by forzaportante** [comment]
Today it happened to me too

**Comment by asdfzxcvbn** [comment]
this could happen occasionally, however playing any song or restarting the app should fix the issue
