### ISSUE TITLE
The app repeatedly prompts that it needs to be restarted

### ISSUE THREAD

**Issue by daniloy** [whoeevee/EeveeSpotify#134]
![image](https://github.com/whoeevee/EeveeSpotify/assets/133594572/578de711-89c1-464d-b4b5-33d38655a475)

**Comment by asdfzxcvbn** [comment]
please test v4.0 @daniloy

**Comment by daniloy** [comment]
> please test v4.0 @daniloy 

I'm trying version 4.0 and everything works fine now
