### ISSUE TITLE
Frequently app crashes while on player

### ISSUE THREAD

**Issue by GrayNeel** [whoeevee/EeveeSpotify#135]
I face a lot of app crashes while using the Spotify player, for example while trying to disable shuffle if next song just started or randomly when trying to close the player. 

iOS 17.5 iPhone 14 Pro

**Comment by f1r3lohaz** [comment]
Same

**Comment by JudeTheTechSavvyDude** [comment]
> Same

Same with me as well

**Comment by asdfzxcvbn** [comment]
dupe #106
