### ISSUE TITLE
Can you create an altstore/sidestore source?

### ISSUE THREAD

**Issue by ElliotCHEN37** [whoeevee/EeveeSpotify#136]

**Comment by asdfzxcvbn** [comment]
okay, i will work on this

however keep in mind altstore sucks and the repo made won't be compatible with AltStore (and probably sidestore), but it will work with esign/scarlet/all the other signing apps

**Comment by asdfzxcvbn** [comment]
you can now add https://raw.githubusercontent.com/whoeevee/EeveeSpotify/swift/repo.json to esign/scarlet/any other signing apps you use
