### ISSUE TITLE
Smart shuffle/regular shuffle shows the same list of songs every time it is shfuffled so it basically doesn't even shuffle

### ISSUE THREAD

**Issue by fugegate** [whoeevee/EeveeSpotify#138]

**Comment by asdfzxcvbn** [comment]
🤫🧏‍♂️

**Comment by fugegate** [comment]
> 🤫🧏‍♂️

can it be fixed...?

**Comment by crustycean** [comment]
> > 🤫🧏‍♂️
> 
> can it be fixed...?

Spotify shuffle generally seems to suck. The devs have said that implementing true shuffle is outside the scope of the tweak, so I've been using this: http://spotify-true-shuffle.pages.dev
