### ISSUE TITLE
Getting widgetExtension crashed 

### ISSUE THREAD

**Issue by rezakashkoul** [whoeevee/EeveeSpotify#141]
Thanks for your great work! I love it so much. It’s the best ever Spotify tweak in all the time!
My iPhone is on iOS 16.0 jailbreak with dopamine 2 and using debug IPA version.
When I close the app I get widgetExtension crashed .

![FF4C7EA8-CCEC-4572-9EAF-EBED2CDEFBF6](https://github.com/whoeevee/EeveeSpotify/assets/76540607/abd99d11-65b2-4bb3-88e9-bed51c530c41)

**_heres a log from one of these crashes:_**

[Crash log.txt](https://github.com/whoeevee/EeveeSpotify/files/15466646/Crash.log.txt)

**Comment by asdfzxcvbn** [comment]
just use deb

**Comment by asdfzxcvbn** [comment]
> > just use deb
> 
> 
> 
> Can't install deb files on rootless Dopamine [tried both of them]; please take look.I also tried to convert the deb by scripts but there's no way.
> 
> 
> 
> ![61C8B111-D4DF-4256-8228-C936435805BC](https://github.com/whoeevee/EeveeSpotify/assets/76540607/a0d9c573-a2b2-4b1c-bb0d-17f04d58cf3c)
> 
> ![F480C7EF-EC12-424D-853A-D2467ADA9068](https://github.com/whoeevee/EeveeSpotify/assets/76540607/7821392b-b980-4897-ad3c-240f3a6def68)
> 
> 

you need to install both eeveespotify deb and swiftprotobuf deb, use the ones with iphoneos-arm64 in the name

**Comment by asdfzxcvbn** [comment]
uninstall the swiftprotobuf deb you already have installed from cypwn

**Comment by rezakashkoul** [comment]
It worked finally thanks for your help.
But widget extensions error seems to happen again even with using couple deb files.

**Comment by asdfzxcvbn** [comment]
okay, weird, honestly i have no idea why this happens, it might just be a spotify stock issue
