### ISSUE TITLE
request for equalizer customization

### ISSUE THREAD

**Issue by 3pcie** [whoeevee/EeveeSpotify#142]
Spotify Deluxe by Jack Cracks has a customized equalizer that allows the user to adjust a greater amount of frequencies than allowed by default. I know that the modification gets applied when one of the eq presets are selected.
I know this version:
https://appdb.to/details/324e0387ea28eb308503e6d34be1712e7e650243
has that modification.

Spotify Deluxe by Jack Cracks is a combination of a bunch of different mods so I don't know how difficult it would be to identify which mod allows this Equalizer modification to take place. 

What I am asking, however, is for any information on the eq mod and hopefully implementation into EeveeSpotify 3.1.

I will attach an image of what the implementation of the modification used to look like:

![IMG_0314](https://github.com/whoeevee/EeveeSpotify/assets/68384204/c231bd3d-67a9-4408-950c-b1c75a8f0883)

**Comment by asdfzxcvbn** [comment]
no

**Comment by 3pcie** [comment]
bruh

**Comment by level3tjg** [comment]
Pretty sure this is my tweak SpotifyEqualizerEnhancer, it should still work if you add it to the ipa using pyzule or similar tools. There's a bug that causes the menu icon in the equalizer view to be invisible, you can still tap in the top right to add frequencies and save presets unless something has changed since the last time I tried it. I haven't updated it in years and probably never will because Spotify sucks. Hope that helps

**Comment by benswolo** [comment]
I wasn't able to get this tweak to work with the latest app (swift 4.1), used sideloady and pyzule for ipa generation but kept crashing whenever I tried to go to equalizer settings inside spotify. Is there something I should be modifying other than adding the ipa and the deb tweak?

**Comment by 3pcie** [comment]
i have no clue. i looked into old versions of spotify deluxe from jack cracks. specifcially the legacy version on appdb. but even when i use the SpotifyEqualizerEnhancer file that i found directly on there, it still crashes. it probably is because of the spotify version. i dont think the creator of SpotifyEqualizerEnhancer will update it. i would pay good money for a SpotifyEqualizerEnhancer update.

**Comment by 3pcie** [comment]
i have no clue. i looked into old versions of spotify deluxe from jack cracks. specifically the legacy version on appdb. but even when i use the SpotifyEqualizerEnhancer file that i found directly on there, it still crashes. it probably is because of the spotify version. i would pay for a SpotifyEqualizerEnhancer update at this point.
