### ISSUE TITLE
[Feature request] Experimental Features

### ISSUE THREAD

**Issue by lolipop88** [whoeevee/EeveeSpotify#144]
Hello as the title says would it be possible to add the option to enable the Experimental Features of Spotify I don’t know if the mobile app even has them but it should.

as far as I understood fun options like change color, pled mode or even themes etc won’t be added (which is sad) 

but anyways incredible work you have done thank you 🙏

**Comment by yodaluca23** [comment]
I've wondered about this too, though I've never heard of an iOS Spotify A/B menu..

**Comment by asdfzxcvbn** [comment]
> as far as I understood fun options like change color, pled mode or even themes etc won’t be added

like said before, EeveeSpotify is a tweak to give you free premium, that's it

99% of feature requests **are** going to be denied, we don't need them

**Comment by Finealex** [comment]
> 🙏

Grow up
