### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by Fi-tz** [whoeevee/EeveeSpotify#147]
All my network just working fine ,any idea?! Bro Version 4'1 

![image](https://github.com/whoeevee/EeveeSpotify/assets/73329003/e73aac35-8d16-457c-be59-b14efcf150c1)

**Comment by Fi-tz** [comment]
Plus when I typed the correct password and tap login,the notice is popping out right there

**Comment by whoeevee** [comment]
can you show log messages? 
`idevicesyslog | grep "EeveeSpotify"`

**Comment by Fi-tz** [comment]
> messages?

I want to,bro ,but honestly I don't know how to operate that ,and btw ,the problem is solved by tap my vpn client off ,I don't know what relationship between thsi tweak and my shadowshocket ,
