### ISSUE TITLE
Lyrics Colors Update

### ISSUE THREAD

**Issue by fugegate** [whoeevee/EeveeSpotify#148]
![image](https://github.com/whoeevee/EeveeSpotify/assets/46111388/36ac1777-c50d-46bd-ae52-da063a7b23cc)

![image](https://github.com/whoeevee/EeveeSpotify/assets/46111388/392d6cf9-4f55-4a42-9f23-7df1db9cb079)

Would it possible to change the lyrics colors so they match the original Spotify colors? And if certain songs that Spotify doesn't have lyrics for, it would just default to the lyrics colors that was implemented by developer

**Comment by lolipop88** [comment]
Would appreciate such a feature aswell the light colors are just bad a nice Spotify themed lyric window would be great also instead of changing the color to something else if it has not found lyrics just hide the window completely

**Comment by whoeevee** [comment]
I’ve just implemented original colors with https://github.com/whoeevee/EeveeSpotify/commit/f98b019. You can get the debs from [GitHub Actions](https://github.com/whoeevee/EeveeSpotify/actions/runs/9302178730).

**Comment by Cosmic1212** [comment]
> ![image](https://github.com/whoeevee/EeveeSpotify/assets/46111388/36ac1777-c50d-46bd-ae52-da063a7b23cc)
> 
> ![image](https://github.com/whoeevee/EeveeSpotify/assets/46111388/392d6cf9-4f55-4a42-9f23-7df1db9cb079)
> 

Here's a more drastic issue of the colors:
![image](https://github.com/whoeevee/EeveeSpotify/assets/171290658/99f75450-031b-4bdf-97e5-078eaeb15cb2)
![image](https://github.com/whoeevee/EeveeSpotify/assets/171290658/13915faf-a669-4f78-a1c3-4a8380119f38)
> Would it possible to change the lyrics colors so they match the original Spotify colors? And if certain songs that Spotify doesn't have lyrics for, it would just default to the lyrics colors that was implemented by developer
