### ISSUE TITLE
Lyrics at the top

### ISSUE THREAD

**Issue by GuestedKun** [whoeevee/EeveeSpotify#149]
if i remember correctly lyrics are always at the top so it would be awesome if this client has it when we use the Custom lyrics

![CC591EF9-BE9B-4ACF-9C70-FFA880E83D2F](https://github.com/whoeevee/EeveeSpotify/assets/108152019/2f96377f-9b00-436e-8f0d-cc6307bee864)

**Comment by Finealex** [comment]
> mine is random

**Comment by asdfzxcvbn** [comment]
afaik we just place the lyrics in Spotify's existing window, meaning we don't modify the position of that window

this is a stock spotify "issue" anyway -- live events are always on top
