### ISSUE TITLE
Is there a way to make Spotify CarPlay work?

### ISSUE THREAD

**Issue by GrayNeel** [whoeevee/EeveeSpotify#151]
Hello,

Not sure if this is just my issue or not but on CarPlay the Spotify icon does not show up, so I cannot use that in any way apart from streaming the music from the phone.

Is there by any chance any way to fix/workaround this?

**Comment by sprites69** [comment]
I was just about to write about this too.

I'm using E-Sign for the signer, and a MapleSign cert.

It shows CarPlay when I plug in my phone into my unit, and reflects in eeveespotify also during playback. A car icon is present in the song title previews and such.

There are no CarPlay entitlements AFAIK with MapleSign certs, but I recall with certain modified Spotify IPAs (older versions) in which it was possible to control playback via the "Now Playing" app during CarPlay usage. However, now it just shows a blank screen when pressing it. Also deleted the Music app also to see if it would resolve the issue. No dice.

**Comment by Cosmic1212** [comment]
Yes would appreciate it. Also could you create a tutorial on how to get the CarPlay working? Especially on appdb

**Comment by asdfzxcvbn** [comment]
trollstore is required for carplay
