### ISSUE TITLE
Just skips every song for me

### ISSUE THREAD

**Issue by Escanor-87** [whoeevee/EeveeSpotify#152]
Bump

https://github.com/whoeevee/EeveeSpotify/assets/94392088/52825872-5813-4fef-af91-2872c99668e0

**Comment by Cosmic1212** [comment]
> Bump
> 
> https://github.com/whoeevee/EeveeSpotify/assets/94392088/52825872-5813-4fef-af91-2872c99668e0

Turn off high audio quality that fixed it for me

**Comment by Escanor-87** [comment]
> > Bump
> > 
> > https://github.com/whoeevee/EeveeSpotify/assets/94392088/52825872-5813-4fef-af91-2872c99668e0
> 
> Turn off high audio quality that fixed it for me

Doesn't work for me

**Comment by 0nexx** [comment]
try to turn on vpn if you are from russia (it worked for me (i’m from russia))

**Comment by Escanor-87** [comment]
> try to turn on vpn if you are from russia (it worked for me (i’m from russia))

LoL it worked. I tried with vpn before, but nothing helped. It impossible to find good vpn service for free nowadays 😅
