### ISSUE TITLE
Smart Shuffle not turning on

### ISSUE THREAD

**Issue by Cosmic1212** [whoeevee/EeveeSpotify#153]
![image](https://github.com/whoeevee/EeveeSpotify/assets/171290658/99905932-d49c-4c42-a221-d08c1d721b70)

**Comment by Hellboy2018** [comment]
Ami it works for me![image](https://github.com/whoeevee/EeveeSpotify/assets/171330187/226e4573-f1dd-4a34-b179-45fbf4f99f4f)

**Comment by asdfzxcvbn** [comment]
unrelated to EeveeSpotify
