### ISSUE TITLE
AppDB help

### ISSUE THREAD

**Issue by Cosmic1212** [whoeevee/EeveeSpotify#156]
![image](https://github.com/whoeevee/EeveeSpotify/assets/171290658/cc245139-459f-46fc-aa2c-d56eb371653a)

I was trying to install eevee Spotify but this pops up on AppDB anyone know how to fix?

Everything was working before and now it stopped

**Comment by asdfzxcvbn** [comment]
this has nothing to do with EeveeSpotify, look into signing certificates
