### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by mrafieefard** [whoeevee/EeveeSpotify#157]
![image](https://github.com/whoeevee/EeveeSpotify/assets/54307278/7961971f-ffac-4eb0-ba39-d7f778a47930)

The username and password are correct

**Comment by whoeevee** [comment]
have you VPN enabled?

**Comment by hugeBlack** [comment]
Same here. I can login in version 8.9.38, but not in version 8.9.42. The original Spotify worked fine.

**Comment by mrafieefard** [comment]
Yeah I installed another premium version and it works fine also I didn't uninstall that spotify and try to update that one with this spotify it logged in but not premium and also when I close it, it will logout from account

That's weird

**Comment by mrafieefard** [comment]
> have you VPN enabled?

Yes because spotify blocked my country so in any way I should use vpn

**Comment by asdfzxcvbn** [comment]
try using another vpn

**Comment by Blockr22** [comment]
Happened to me aswell but removing original spotify app & resetting password from within tweaked spotify & signing from email option, where it says go back to Spotify. Made it work

**Comment by mrafieefard** [comment]
> try using another vpn

My vpn is ok because I can use it in desktop or even other spotify premium / original versions

**Comment by mrafieefard** [comment]
> Happened to me aswell but removing original spotify app & resetting password from within tweaked spotify & signing from email option, where it says go back to Spotify. Made it work

Are you on latest version?

**Comment by mrafieefard** [comment]
How I can debug app to see whats wrong?

**Comment by asdfzxcvbn** [comment]
so disabling it even just once wont work?

**Comment by mrafieefard** [comment]
> so disabling it even just once wont work?

Nah spotify and my gov both blocked spotify 
I even debug http requests and everything fine I think something wrong from the app because I get all http requests 200 also I saw authentication token in debug but it failed in app

**Comment by mrafieefard** [comment]
If you can help me how to debug the it will be great

**Comment by asdfzxcvbn** [comment]
maybe you should try another vpn

**Comment by mrafieefard** [comment]
> maybe you should try another vpn

As I said, I check http requests and nothing wrong also I use another vpn and still I get same error so it means something wrong with the app

**Comment by mrafieefard** [comment]
I fixes it 
If you face this problem install old version of spotify ( I test it in old premium version ) then after install it login in to your account, now install "EeveeSpotify-4.0-8.9.42" ( I tested this version ) then replace it with old spotify ( it's automatically replace you don't need do anything ) 
And you are good to go
