### ISSUE TITLE
update notifier

### ISSUE THREAD

**Issue by bachig26** [whoeevee/EeveeSpotify#161]
@asdfzxcvbn hi, i just saw you have an repo: zxUpdateNotifier for sideloaded apps.
if possible, could you include it in the future EeveeSpotify ipa's?

**Comment by asdfzxcvbn** [comment]
no, it's not needed, you can inject it yourself if you need it; plus, new EeveeSpotify versions are released alongside spotify updates

there really is no need to update spotify anyway, just use the versions where EeveeSpotify is confirmed to work fine (github releases & the official telegram)
