### ISSUE TITLE
sharing music to another devices (google home) is fucked up

### ISSUE THREAD

**Issue by Kajnolerx** [whoeevee/EeveeSpotify#165]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

if you are trying to choose song while sharing to google home, a random ass song is playing

**Comment by asdfzxcvbn** [comment]
this might be related to #4 ,, please refer to that issue
