### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by NON1919** [whoeevee/EeveeSpotify#166]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

the song suggestions of spotify won’t work after i reache the limit of song picking and it won’t let me to select a song from artist after that too (sorry for my bad english)

**Comment by asdfzxcvbn** [comment]
weird, we cant help
