### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by meepyboii** [whoeevee/EeveeSpotify#169]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

Genius fallback doesnt work for some songs, even though they have genius lyrics..
Musixmatch with Genius Fallback
![IMG_1643](https://github.com/whoeevee/EeveeSpotify/assets/78036865/534d079a-e60e-41f2-b5b6-8815e1f17b81)
Genius
![IMG_1644](https://github.com/whoeevee/EeveeSpotify/assets/78036865/06d2e8fd-fc44-4510-9ae6-bac669d1fbc3)

**Comment by whoeevee** [comment]
it looks like you have lyrics with Genius, but you see the "Couldn't load the lyrics for this song" message with Musixmatch. it's really weird, I've just tested, and this song has lyrics on Musixmatch, so the fallback should not occur at all. when testing with fallback, it gives me the correct Genius lyrics

try common solutions like updating the Musixmatch token, connecting to a VPN server, restarting the app, etc

**Comment by meepyboii** [comment]
@asdfzxcvbn, when i go into the musixmatch app it says it’s not authorized to show the lyrics, and also how do i update the token?

**Comment by asdfzxcvbn** [comment]
> when i go into the musixmatch app it says it’s not authorized to show the lyrics, and also how do i update the token?

what? can you send a screenshot?

**Comment by meepyboii** [comment]
> what? can you send a screenshot?

this is what happens in musixmatch even tho eevee says it has lyrics in musixmatch:
![IMG_1714](https://github.com/whoeevee/EeveeSpotify/assets/78036865/18381ebb-b452-412b-beca-349b9b48274c)

**Comment by meepyboii** [comment]
and then in spotify i get the lyrics error

**Comment by yodaluca23** [comment]
> and then in spotify i get the lyrics error

What country is your ip in the only thing I could think this could be would be a Musixmatch licensing thing...

**Comment by yodaluca23** [comment]
> What country is your ip in the only thing I could think this could be would be a Musixmatch licensing thing...
> 
> Edit: Hmm not working for me though same song in US.
> 
> Edit 2: setting my VPN to Brazil it shows, so I think this is a licensing thing:
> 
> ![image](https://github.com/whoeevee/EeveeSpotify/assets/67206487/8f403308-577d-4ef9-91ca-0a1efff4cdc0)
> 
> Edit 3: this is also replicatable in the Spotify app, also I believe why the genius fallback is not working is because the Musixmatch API is not responding with the standard no lyrics found error and so EeveeSpotify just displays what it receives anyways because it doesn't realize that it is still an error and it does not have the lyrics.
> 
> US (Genius Fallback enabled):
> 
> ![image](https://github.com/whoeevee/EeveeSpotify/assets/67206487/b0486351-e223-4683-8d70-e4bd66d6cbf1)
> 
> Brazil (Genius Fallback enabled):
> 
> ![image](https://github.com/whoeevee/EeveeSpotify/assets/67206487/83f9a318-3109-4bab-8919-07eb87877d2d)
> 
> Lyric provider selected as Genius (US):
> 
> ![image](https://github.com/whoeevee/EeveeSpotify/assets/67206487/ebd62208-6914-4831-9ea4-08669625d2d8)

For anyone following only via E-mail, I believe I found the issue, refer to my original comment that I edited.

**Comment by meepyboii** [comment]
yes i’m using a us ip, but i can’t change my ip address since i’m using dns method to keep eeveespotify signed

**Comment by yodaluca23** [comment]
@whoeevee I think a solution (I don't know what you have implemented right now..) check the [status code](https://developer.musixmatch.com/documentation/status-codes) received from API received from if it's ANYTHING but 200 then consider it has no lyrics and continue with fallback if enabled. If that is already what it's doing, then Musixmatch API is really dumb...

**Comment by whoeevee** [comment]
> @whoeevee I think a solution (I don't know what you have implemented right now..) check the [status code](https://developer.musixmatch.com/documentation/status-codes) received from API received from if it's ANYTHING but 200 then consider it has no lyrics and continue with fallback if enabled. If that is already what it's doing, then Musixmatch API is really dumb...
> 
> Edit: I don't have time to test API responses rn...

If the tweak is unable to decode the lyrics from the Musixmatch response, it will fall back to Genius. It’s weird that the "Couldn't load the lyrics for this song" message appears with a US IP address. Send the API responses and EeveeSpotify console messages when you have time.

**Comment by yodaluca23** [comment]
> If the tweak is unable to decode the lyrics from the Musixmatch response, it will fall back to Genius. It’s weird that the "Couldn't load the lyrics for this song" message appears with a US IP address. Send the API responses and EeveeSpotify console messages when you have time.

When using this cURL Request, (converted from the request EeveeSpotify uses [here](https://github.com/whoeevee/EeveeSpotify/blob/swift/Sources/EeveeSpotify/Lyrics/DataSources/MusixmatchLyricsDataSource.swift)), with a US IP the "lyrics_body" response is completely blank. With a Brazil IP, it is the correct lyrics of the song. Other than the "lyrics_body" (and other variables expected to change every request), the only other fields that are different are the copywrite field going from ```lyrics_copyright": "Copyright: Downtown Dmp Songs\n",``` to ```lyrics_copyright": "Unfortunately we're not authorized to show these lyrics."``` but also the "restricted" changes from ```restricted": 0,``` to ```restricted": 1,``` could you check the "restricted" value from each response, and in addition if it can't decode the lyrics to if "restricted" has a value other than 0, to also trigger the fallback?

cURL request template used:

```curl -G \
     --url "https://apic.musixmatch.com/ws/1.1/macro.subtitles.get" \
     --data-urlencode "track_spotify_id=1uxiaf3DUS4vpOqNGu4MzL" \
     --data-urlencode "subtitle_format=mxm" \
     --data-urlencode "q_track= " \
     --data-urlencode "usertoken=YOUR_MUSIXMATCH_USER_TOKEN" \
     --data-urlencode "app_id=mac-ios-v2.0"```

**Comment by whoeevee** [comment]
should be fixed with d71f0b8
check https://github.com/whoeevee/EeveeSpotify/actions/runs/9603452109

**Comment by yodaluca23** [comment]
> should be fixed with [d71f0b8](https://github.com/whoeevee/EeveeSpotify/commit/d71f0b8e9ac39a4bd2842f3faee38507dfc573d8) check [whoeevee/EeveeSpotify/actions/runs/9603452109](https://github.com/whoeevee/EeveeSpotify/actions/runs/9603452109)

It looks like musixmatch just added lyrics for that song in the US, but another song [Fallen in Deep by gyrofield](https://open.spotify.com/track/5BWzriKynmGuHT1e4HayRH) is also restricted here in the US, but not Brazil. When using Genius fallback playing that song, it does successfully fallback, and show the popup! But, could you make the popup less intrusive though? Or maybe add like a notice in the lyrics card instead, because, I wouldn't want to have it popup every time a restricted song comes up, I would just like to be able to read it somewhere unobtrusive, and go "Oh, I guess that's why this song doesn't have Musixmatch Lyrics".

**Comment by whoeevee** [comment]
the popup appears just once

**Comment by yodaluca23** [comment]
> the popup appears just once

Oh hmm... Then maybe add an indicater somewhere else too? So we can Identify which songs are not showing Musixmatch lyrics because of restrictions?

**Comment by meepyboii** [comment]
yeah like an exclamation mark like this one -> ⚠️ by the lyrics

**Comment by whoeevee** [comment]
implemented
check out afbc8d5 (https://github.com/whoeevee/EeveeSpotify/actions/runs/9620092970)

**Comment by yodaluca23** [comment]
> implemented check out [afbc8d5](https://github.com/whoeevee/EeveeSpotify/commit/afbc8d597eb6674a9b38e0cb6a93099652f45f3b) ([whoeevee/EeveeSpotify/actions/runs/9620092970](https://github.com/whoeevee/EeveeSpotify/actions/runs/9620092970))

Where is it? I don't see any difference?

**Comment by yodaluca23** [comment]
> > implemented check out [afbc8d5](https://github.com/whoeevee/EeveeSpotify/commit/afbc8d597eb6674a9b38e0cb6a93099652f45f3b) ([whoeevee/EeveeSpotify/actions/runs/9620092970](https://github.com/whoeevee/EeveeSpotify/actions/runs/9620092970))
> 
> 
> 
> Where is it? I don't see any difference?

Never minds, I'm blind, yea, that looks really good!

**Comment by meepyboii** [comment]
@yodaluca23 can u send a screenshot of it? i cant download it since i’m not jb

**Comment by yodaluca23** [comment]
> @yodaluca23 can u send a screenshot of it? i cant download it since i’m not jb

![IMG_0011](https://github.com/whoeevee/EeveeSpotify/assets/67206487/eb0fb22e-351b-4c44-a7b8-809218a546cb)
![IMG_0012](https://github.com/whoeevee/EeveeSpotify/assets/67206487/3a404395-497c-4bbe-b1d3-f89ddc365e63)

**Comment by meepyboii** [comment]
whens this tweak planning to come out??

**Comment by yodaluca23** [comment]
> whens this tweak planning to come out??

I believe they're usually launched alongside Spotify releases. You can just get the deb from the action and inject it yourself though.

**Comment by meepyboii** [comment]
can u show me how to do this?

**Comment by yodaluca23** [comment]
> can u show me how to do this?

Get the .deb from the linked actions.
Get a Vanilla decrypted Spotify .ipa from somewhere (*cough* ArmConverter *cough*)
Use [Pyzule](https://github.com/asdfzxcvbn/pyzule), [Sideloadly](https://sideloadly.io/), etc to inject the eeveeSpotify .deb into the Spotify .ipa.
Sideload the output patched file with whatever method you want...

**Comment by asdfzxcvbn** [comment]
> > can u show me how to do this?
> 
> Get the .deb from the linked actions. Get a Vanilla decrypted Spotify .ipa from somewhere (_cough_ ArmConverter _cough_) Use [Pyzule](https://github.com/asdfzxcvbn/pyzule), [Sideloadly](https://sideloadly.io/), etc to inject the eeveeSpotify .deb into the Spotify .ipa. Sideload the output patched file with whatever method you want...

just to put this out there

the official IPAs are made with pyzule, and decrypted with the apptesters decrypt bot (free) or [femboy.party](https://femboy.party) (paid)

imo using pyzule would be easier than using sideloadly thanks to the new update, you no longer need to specify Orion deb to inject, just the EeveeSpotify and SwiftProtobuf debs

**Comment by meepyboii** [comment]
so i sign through esign dns method. how do i do that there?

**Comment by asdfzxcvbn** [comment]
> so i sign through esign dns method. how do i do that there?

don't even try, use a PC to inject

**Comment by whoeevee** [comment]
v4.3 is out
