### ISSUE TITLE
Still getting ads

### ISSUE THREAD

**Issue by timfea926** [whoeevee/EeveeSpotify#17]
Getting ads when using this app version 8.9.32. 

iOS 17.4.1, iPhone 13.

**Comment by asdfzxcvbn** [comment]
provide more info please? how'd you install? do all other premium features work?

**Comment by timfea926** [comment]
Honestly I already uninstalled because I hate Spotify with ads and the only premium feature I really know of is no ads. The ads started playing after I played one song and I was unable to skip. I soon uninstalled.

**Comment by timfea926** [comment]
I installed via ESign via SwaggyP36000 IPA repo.

**Comment by asdfzxcvbn** [comment]
did you try the v1.2 release from this repo?
