### ISSUE TITLE
video ad in search page [version Swift 4.0]

### ISSUE THREAD

**Issue by bachig26** [whoeevee/EeveeSpotify#170]
I saw this ad section on the search page right after the installation of v4.0, I have switched the patching method to Dynamic and still this ad was there.
But I can still use all the available premium features by the patch and it also shows me that i have Premium account when checked in the profile right after seeing this ad.

I have re-installed v3.1 which doesn't show this ad when I tried after uninstalling v4.0.

Please have a look at this if there's any possible solution.

### Screenshot

![IMG_1043](https://github.com/whoeevee/EeveeSpotify/assets/96393348/507d5145-dc42-47b9-85dc-8ef3fe12cc6e)

**Comment by whoeevee** [comment]
is the ad still here after resetting the data in EeveeSpotify settings with Dynamic method enabled?

**Comment by bachig26** [comment]
> is the ad still here after resetting the data in EeveeSpotify settings with Dynamic method enabled?

yes, i tried restarting the app multiple times since i found it few days before and even after changing to dynamic method, i still saw this ad.
and i didn't see any other ads, just this one.

**Comment by whoeevee** [comment]
and you don’t see it with static method?

**Comment by bachig26** [comment]
> and you don’t see it with static method?

no, I still see it with static method.

**Comment by whoeevee** [comment]
try to install the deb from https://github.com/whoeevee/EeveeSpotify/actions/runs/9374957820 and enable Configuration Overwrite

is ad still here?

**Comment by bachig26** [comment]
> try to install the deb from https://github.com/whoeevee/EeveeSpotify/actions/runs/9374957820 and enable Overwrite Configuration

i use altstore to sideload, can you let me know how to install it, or maybe injecting it into the ipa?

**Comment by bachig26** [comment]
@whoeevee or if you could make an workflow for injecting and building the ipa similar to this: https://github.com/YTLitePlus/YTLitePlus/blob/main/.github/workflows/buildapp.yml

it might be much more easier.

**Comment by asdfzxcvbn** [comment]
> @whoeevee or if you could make an workflow for injecting and building the ipa similar to this: https://github.com/YTLitePlus/YTLitePlus/blob/main/.github/workflows/buildapp.yml
> 
> it might be much more easier.

we aren't going to make a workflow. building your own ipa isnt necessary, we update them on github releases and our telegram. i wouldn't recommend staying up to date anyway.. spotify is removing basic QoL features (see #173 for example)

in this case you could use [pyzule](https://github.com/asdfzxcvbn/pyzule). just install it, download the debs somewhere, and use it like so:

`pyzule -i /path/to/Spotify.ipa -o ~/LatestEevee.ipa -uwsgf latestEeveeCommit.deb swiftprotobuf.deb ~/.config/pyzule/CydiaSubstrate.framework`

**Comment by whoeevee** [comment]
try v4.1 and enable Overwrite Configuration
does it fix the ad?

**Comment by bachig26** [comment]
> try v4.1 and enable Overwrite Configuration does it fix the ad?

the ad is still there and it doesn't disappear. even if i close it and restart the app, it still re-appears.

| Search page      | Eevee settings |
| :---        |          ---: |
| ![IMG_1044](https://github.com/whoeevee/EeveeSpotify/assets/96393348/b4c01832-e2be-4263-af8d-7031c04eb9a9)      | ![IMG_1045](https://github.com/whoeevee/EeveeSpotify/assets/96393348/9dae86ce-9312-4ae6-9834-8658153a73c0)       |

**Comment by asdfzxcvbn** [comment]
we don't know what the issue is then
