### ISSUE TITLE
[Bug] Battery Drain 

### ISSUE THREAD

**Issue by sdburrows** [whoeevee/EeveeSpotify#171]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

I am experiencing high battery usage when using v4.0 dynamic patching. The phone runs hot too. I am using iPhone 15 Pro and on the latest iOS. Not sure if anyone else is experiencing this.

**Comment by QPMXPGY** [comment]
Thanks, I haven't experienced these situations in ios16.3 iPhone13


在 2024年6月3日，14:17，sdburrows ***@***.***> 写道：

﻿

Is this issue appropriate?

  *    I have read the document in its entirety

Is this issue unique to EeveeSpotify?

  *    I was unable to reproduce my issue using the stock Spotify app

Have you searched the existing issues?

  *    This is a unique issue

Describe the bug.

I am experiencing high battery usage when using v4.0 dynamic patching. The phone runs hot too. I am using iPhone 15 Pro and on the latest iOS. Not sure if anyone else is experiencing this.

**Comment by asdfzxcvbn** [comment]
this really shouldnt be possible. data is only modified when spotify reloads data, can you not reproduce this with static patching?

although likely not, i'm curious to hear if anyone else has battery drain

**Comment by Finealex** [comment]
> not really. But on spotilife I noticed battery drain

**Comment by samuelawachie** [comment]
> this really shouldnt be possible. data is only modified when spotify reloads data, can you not reproduce this with static patching?

This got me curious. Is the battery usage different for dynamic as opposed to static patching? @asdfzxcvbn @whoeevee

**Comment by asdfzxcvbn** [comment]
> > this really shouldnt be possible. data is only modified when spotify reloads data, can you not reproduce this with static patching?
> 
> This got me curious. Is the battery usage different for dynamic as opposed to static patching? @asdfzxcvbn @whoeevee 

it really shouldnt.

dynamic: modify network responses (only happens once every app startup i think)

static: modify offline.bnk on app startup
