### ISSUE TITLE
[Ask a question]  sileo Jailbreak source

### ISSUE THREAD

**Issue by WelsKinG** [whoeevee/EeveeSpotify#172]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

where is sileo Jailbreak source?

**Comment by asdfzxcvbn** [comment]
we don't have a jailbreak source and we won't make one, just get the debs from github releases
