### ISSUE TITLE
[Bug] Music duration display

### ISSUE THREAD

**Issue by manstyB4III** [whoeevee/EeveeSpotify#173]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

When you play music and it lasts for example 3 minutes, two display ways will be offered, if you are 30 seconds into the song:
`0:30 -2:30`
`0:30  3:00`

The second option, where the duration of the music remains fixed, is no longer available (normally you just have to click on -2:30 to alternate between the two displays). I hope I was clear in my problem.

**Comment by asdfzxcvbn** [comment]
this can be reproduced on the stock spotify app, please actually test on the stock app like the issue template tells you to next time
