### ISSUE TITLE
[Bug] Musixmatch Lyrics with token works perfectly on iPhone, but it works without syncing on iPad mini 6

### ISSUE THREAD

**Issue by demouser007** [whoeevee/EeveeSpotify#175]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

There is no lyrics synchronization on the iPad. EeveeSpotify-4.0-8.9.42.ipa installed via TrollStore on iOS 15 and iPadOS 15, respectively.

**Comment by whoeevee** [comment]
@hugeBlack do you have such issue?

**Comment by hugeBlack** [comment]
I haven't used Musixmatch yet. Other sources, LRCLIB and Genius, worked fine on both iPhone and iPad.

**Comment by asdfzxcvbn** [comment]
can you test v4.2 @demouser007 ?

**Comment by demouser007** [comment]
@asdfzxcvbn It's working now, thank you @whoeevee!
