### ISSUE TITLE
[Bug] Tapping on Song Makes Popup Appear

### ISSUE THREAD

**Issue by Hexafluorine** [whoeevee/EeveeSpotify#176]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

![IMG_0145](https://github.com/whoeevee/EeveeSpotify/assets/110123144/a65e4910-36fa-4962-a08d-a27f21c57bb6)
Tapping on a song to play makes this popup appear and the desired song doesn’t play

Although, resetting data does remove this issue temporarily

iPhone 15 | iOS 17.4.1

**Comment by Hexafluorine** [comment]
I am also using Dynamic Patching

**Comment by asdfzxcvbn** [comment]
but do all other premium features work?

**Comment by Hexafluorine** [comment]
> but do all other premium features work?

Yeah, I'm pretty sure they still work

**Comment by asdfzxcvbn** [comment]
yeah that’s weird then idk
