### ISSUE TITLE
Perfect but need one important feature ( offline playback )

### ISSUE THREAD

**Issue by iMahmoudz** [whoeevee/EeveeSpotify#177]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

App is very perfect perfect perfect and thank you for your great effort!
But we need one important feature ( offline playback ) , please try your best to make it!❤️

**Comment by libr2** [comment]
it's literally NOT POSSIBLE AT ALL. this feature is a server-sided feature, this means that it cannot get **modified/bypassed in any way**.

**Comment by yodaluca23** [comment]
> it's literally NOT POSSIBLE AT ALL. this feature is a server-sided feature, this means that it cannot get **modified/bypassed in any way**.

Spoofing the native Spotify download feature is not possible as you said. However it is potentially possible, though I'm pretty sure they've already said it's way out the scope of this project to create a third-party downloader that would do all the downloading clients sided (like ZSpotify) and then create some sort of organization system for those downloads, to play them back offline through playlists and such.

**Comment by asdfzxcvbn** [comment]
ticked the "i have read the document in its entirety" without reading it. likely will get banned from repo.
