### ISSUE TITLE
Liked songs lists on Artist's page is missing

### ISSUE THREAD

**Issue by Briandisease** [whoeevee/EeveeSpotify#179]
Hi guys I am not sure if this feature is something outdated and no one has it anymore or its just on my end. 
![IMG_2329](https://github.com/whoeevee/EeveeSpotify/assets/171970935/b1c86259-011e-4add-a021-17021e758495)
![IMG_2328](https://github.com/whoeevee/EeveeSpotify/assets/171970935/5abdbc88-fadf-46d6-9f1d-7eaf6a2a0004)

Thanks 🍀

**Comment by asdfzxcvbn** [comment]
use issue template
