### ISSUE TITLE
Liked songs lists on Artist's page is missing

### ISSUE THREAD

**Issue by Briandisease** [whoeevee/EeveeSpotify#180]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

Hi guys I am not sure if this feature is something outdated and no one has it anymore or its just on my end.

![IMG_2329](https://github.com/whoeevee/EeveeSpotify/assets/171970935/97e10d57-9491-43af-a27f-adc8f6e552d9)
![IMG_2328](https://github.com/whoeevee/EeveeSpotify/assets/171970935/612ee08c-a605-456b-8350-e5c5c47d6917)

Thanks 🍀

**Comment by asdfzxcvbn** [comment]
spotify removed it, are you sure you couldn’t reproduce the issue on the stock spotify app?
