### ISSUE TITLE
[Possible bug] Ads inside application

### ISSUE THREAD

**Issue by bphucc** [whoeevee/EeveeSpotify#181]
Hi, i'm using the tweak without any problem, but few days ago, it started appear ads on the application main page. All other functionalities worked as normal, just this one. 

![image](https://github.com/whoeevee/EeveeSpotify/assets/42881433/250ae09c-fa60-4d41-887b-1cc9e651c2a2)

Spotify: v8.9.42.597
Eeeve: lastest 4.0
Device: iPhone 13 Pro Max iOS 15.7 19H12
TrollStore: 2.0.15
Location: US

**Comment by yodaluca23** [comment]
Yep, this happens to me to, its only that one type of small video ad...

**Comment by whoeevee** [comment]
try v4.1 and enable Overwrite Configuration
does it fix the ad?

**Comment by bphucc** [comment]
I think it's fixed now by downloading the lastest version. But i'm not sure because I've not turned the option 'Overwrite Configuration' in settings on and the ads automatically disappears.

**Comment by yodaluca23** [comment]
With override configuration enabled, the ad is shown for like a millisecond and then disappears.

**Comment by asdfzxcvbn** [comment]
listening without ads should still work and we dont know about this issue so
