### ISSUE TITLE
[Bug] Endless Listening doesn't work.

### ISSUE THREAD

**Issue by rights4a** [whoeevee/EeveeSpotify#183]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

If i search up songs like Static - Steve Lacy, without repeat it should have recommend songs, but its just repeating the song.

**Comment by RishiSuthar** [comment]
I have the same problem here

**Comment by whoeevee** [comment]
disable shuffle

**Comment by rights4a** [comment]
nope, doesn't work. ill send a screenrecording of what happens

**Comment by RishiSuthar** [comment]
yeah still does not work for me too, the autoplay is on and shuffle disabled. The same song repeats itself

**Comment by RishiSuthar** [comment]
![IMG_8242](https://github.com/whoeevee/EeveeSpotify/assets/77315331/ea5444cd-cc14-48ff-8441-06f9153daf76)

https://github.com/whoeevee/EeveeSpotify/assets/77315331/a382ce67-4ec5-433a-9790-bfaba9dea62d

**Comment by asdfzxcvbn** [comment]
ok skill issue

**Comment by rights4a** [comment]
is that whats suppose to happen? spotlife had endless listening

**Comment by RishiSuthar** [comment]
> is that whats suppose to happen? spotlife had endless listening

they cant figure the solution out.....
