### ISSUE TITLE
[Bug] lyrics sometimes not appearing

### ISSUE THREAD

**Issue by KHng0284** [whoeevee/EeveeSpotify#185]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

Like the title, the lyrics sometimes doesn’t appear while choosing musixmatch as my lyrics provider and genius as fallback

**Comment by RishiSuthar** [comment]
For what song ?

**Comment by KHng0284** [comment]
Any. For 1 song, the lyrics wouldn’t appear while the lyrics for the same song would appear in the next restart of Spotify or the second time entering now playing view

**Comment by RishiSuthar** [comment]
> Any. For 1 song, the lyrics wouldn’t appear while the lyrics for the same song would appear in the next restart of Spotify or the second time entering now playing view

I see, is it maybe your internet connection, maybe it takes time for the lyrics to load ?

**Comment by KHng0284** [comment]
Maybe, but usually it wouldn’t load until the next restart or reentering now playing view

**Comment by asdfzxcvbn** [comment]
this is a known issue and we have no clue on how to fix it

**Comment by asdfzxcvbn** [comment]
@KHng0284 can you reproduce this on stock spotify

**Comment by KHng0284** [comment]
> @KHng0284 can you reproduce this on stock spotify
I can't reproduce this issue on stock Spotify

**Comment by whoeevee** [comment]
should be fixed in 4.7
