### ISSUE TITLE
[Bug] Ads still occurring when playing podcasts 

### ISSUE THREAD

**Issue by gray-morley** [whoeevee/EeveeSpotify#189]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

Ads still occur when playing podcasts, it occurs a few seconds into the podcast: 

Screenshots: 

![IMG_7558](https://github.com/whoeevee/EeveeSpotify/assets/54858242/4aae6711-59d7-4dff-aebf-df7c395a1329)
![IMG_7559](https://github.com/whoeevee/EeveeSpotify/assets/54858242/5495c6f9-08c7-4fed-a848-e8e553f05060)

**Comment by whoeevee** [comment]
try to enable Overwrite Configuration in settings
is ad still here?

**Comment by gray-morley** [comment]
Yes, ads are still there after enabling Overwrite Configuration
