### ISSUE TITLE
[suggestion] add tweak version in eeveespotify settings + switch lyric source button 

### ISSUE THREAD

**Issue by Joshua-18** [whoeevee/EeveeSpotify#191]
Please add information about which version is currently installed in eeveespotify settings that way is easier to tell after its installed 🙏

for lyrics:
Maybe a button somewhere to switch which lyric source instead of having to go to the settings? Although you’d still have to somehow refresh the song so that it picks up the new lyric source…. At least thats how its currently done right now.

**Comment by JackPlaysGames0510** [comment]
Isn’t that the whole point of the genius fallback?

**Comment by Joshua-18** [comment]
> Isn’t that the whole point of the genius fallback?

Not what I’m asking,  songs are not synced in genius but can be in LRCLIB or musixmatch. But having to go to the menu and switch is annoying. So why not have a setting in the player or in the lyrics section to choose a source?

**Comment by JackPlaysGames0510** [comment]
oh I see what you mean now yeah that would be cool I wounder if that would be possible but the fact that you got to refresh it every time might not be but lets hope

**Comment by asdfzxcvbn** [comment]
version info will be added but no button for switching lyric providers

**Comment by yodaluca23** [comment]
> > Isn’t that the whole point of the genius fallback?
> 
> 
> 
> Not what I’m asking,  songs are not synced in genius but can be in LRCLIB or musixmatch. But having to go to the menu and switch is annoying. So why not have a setting in the player or in the lyrics section to choose a source?

Or there could just be a better fallback menu letting you order what you want to fall back for example I could have it set Genius at bottom, LRCLIB on top of that (middle) and Musixmatch on top. This would then when loading lyrics first check Musixmatch, if that fails, check LRCLIB, if that fails then check Genius...
