### ISSUE TITLE
Remove lyrics tab if lyrics aren't available instead of showing couldn't load lyrics for the song.

### ISSUE THREAD

**Issue by 3xynos7** [whoeevee/EeveeSpotify#194]
In Spotify app from AppStore, lyrics tabs are hidden if it was unable to fetch or find lyrics.

**Comment by asdfzxcvbn** [comment]
this would be difficult as the method used to determine if a song has lyrics is called before we fetch lyrics ourselves, and it’s a pretty rare case that songs don’t have lyrics on genius
