### ISSUE TITLE
[Bug] search local network devices explicitly Sonos

### ISSUE THREAD

**Issue by ATran-DevOne** [whoeevee/EeveeSpotify#195]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

The problem is when you want to play on a Sonos device it would not pop-up in the EeveeSpotify version. Is this expected behavior or a bug in my opinion. The app can not see Sonos devices.

https://github.com/whoeevee/EeveeSpotify/assets/33416070/c230dd11-de23-45ae-b541-b4be90d660cd

**Comment by asdfzxcvbn** [comment]
there is no way for us to test this
