### ISSUE TITLE
[Bug] Tiles under music player sometimes refuse to load.

### ISSUE THREAD

**Issue by yodaluca23** [whoeevee/EeveeSpotify#197]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

Tiles under the music player sometimes refuse to load, you can force them to load by closing and reopening the app, or by minimizing and maximizing the player. The screen recording I have attached, explains/shows it better.

https://streamable.com/lksmu6

Edit: forgot to mention it only seems to happen if you let Spotify naturally go to the next song not if you skip.

**Comment by whoeevee** [comment]
duplicate #185

**Comment by asdfzxcvbn** [comment]
@yodaluca23 can you still reproduce this on EeveeSpotify **and** stock spotify

**Comment by yodaluca23** [comment]
> @yodaluca23 can you still reproduce this on EeveeSpotify **and** stock spotify

It's seemingly random when it happens, even with EeveeSpotify, but I will try to see.

**Comment by whoeevee** [comment]
well it should be fixed in 4.7
