### ISSUE TITLE
[Bug] OpenSpotify Extension prompt shows up on Spotify Charts website

### ISSUE THREAD

**Issue by TeaselUwU** [whoeevee/EeveeSpotify#201]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

I noticed the OpenSpotify extension also shows up prompt on https://charts.spotify.com/ website. I don’t know if it’s related to this app or the extension itself, but wanted to let you know that :)

**Comment by TeaselUwU** [comment]
> so nothing happens if you open the link in spotify?

Nope, just says it couldn’t open anything in Spotify

**Comment by TeaselUwU** [comment]
I seem to be unclear on the actual issue, a week late lol, but it can get quite annoying to get the prompt up every time you select a chart to look at. The site also knows to log me off randomly, so I gotta press cancel before I can log back in. It gets spammy. I wondered if it could be possible to exclude the website from the extension or at least make the prompt appear just once.

**Comment by asdfzxcvbn** [comment]
@whoeevee

**Comment by asdfzxcvbn** [comment]
@TeaselUwU please test v4.3

**Comment by TeaselUwU** [comment]
> @TeaselUwU please test v4.3

It’s perfect now, no prompt is showing :D
