### ISSUE TITLE
Spicetify port possible?

### ISSUE THREAD

**Issue by Cosmic1212** [whoeevee/EeveeSpotify#202]
It would would be lovely to have spicetify in this tweak as it enables a whole suite of possibilities and since it already works on windows and macOS

https://spicetify.app/

**Comment by yodaluca23** [comment]
> It would would be lovely to have spicetify in this tweak as it enables a whole suite of possibilities and since it already works on windows and macOS
> 
> https://spicetify.app/

Doubt it's possible to directly port it over. It would have to be like a completely different thing and I'm sure it's way out of the scope of this project. You're welcome to make a post on like r/tweakbounty. lol

**Comment by asdfzxcvbn** [comment]
yeah read above
