### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by khoatranzxcqwe** [whoeevee/EeveeSpotify#204]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

I'm using Iphone 11 pro max 64GB , jailbroken with unCover. I sideload Eevee Spotify with trollstore. The app crash when I open it.

**Comment by Cosmic1212** [comment]
Use the debug version

**Comment by Cosmic1212** [comment]
Or try sideloadly or appdb

**Comment by asdfzxcvbn** [comment]
disable tweak injection with choicy

**Comment by khoatranzxcqwe** [comment]
Date: 6/20/24, 10:13 AM
Process: Spotify
Bundle id: com.spotify.clienteevee
Device: iPhone 11 Pro Max, iOS 14.4
Bundle version: 8.9.48
Exception type: EXC_SOFTWARE (SIGABRT)
Exception subtype: EXC_UNIX_ABORT
Exception codes: 0x0000000000010002, 0x0000000000000000
Culprit: Unknown
Termination Reason: dyld: Using shared cache: 0B7D65F0-E3CC-3727-A3E6-5D6827109324
Library not loaded: /System/Library/Frameworks/AVFAudio.framework/AVFAudio
 Referenced from: /private/var/containers/Bundle/Application/32EBE179-9BBE-4B3D-83F3-B80E521314D2/Spotify-Eevee.app/Spotify
 Reason: image not found
Triggered by thread: 0
Thread name:
Call stack:
0   dyld                           0x000000010947f440 0x109428000 + 357440     // __abort_with_payload
1   dyld                           0x00000001094876e0 0x109428000 + 390880     // abort_with_payload_wrapper_internal
2   dyld                           0x0000000109487714 0x109428000 + 390932     // __unw_set_reg.cold.1
3   dyld                           0x000000010942d05c 0x109428000 + 20572       // dyld::fastBindLazySymbol(ImageLoader**, unsigned long)
4   dyld                           0x00000001094300b8 0x109428000 + 32952       // dyld::_main(macho_header const*, traaunsigned long, int, char const**, char const**, char const**, unsigned long*)
5   dyld                           0x0000000109429258 0x109428000 + 4696       // dyldbootstrap::start(dyld3::MachOLoaded const*, int, char const**, dyld3::MachOLoaded const*, unsigned long*)
6   dyld                           0x0000000109429038 0x109428000 + 4152       // _dyld_start
Register values:
PC: 0x16f5ce690         LR: 0x16f5ce6d0         CPSR: 0x947f440
x0: 0x4400000006        x1: 0x6                 x2: 0x1
x3: 0x16f5ceb00         x4: 0xb5                x5: 0x16f5ce700
x6: 0x0                 x7: 0x0                 x8: 0x0
x9: 0x20                x10: 0x9                x11: 0x1
x12: 0x65               x13: 0xf0               x14: 0xe3
x15: 0xcc               x16: 0x37               x17: 0x209
x18: 0x1094797b4        x19: 0x0                x20: 0x0
x21: 0x16f5ce700        x22: 0xb5               x23: 0x16f5ceb00
x24: 0x1                x25: 0x6                x26: 0x16f5cf818
x27: 0x1094a0000        x28: 0x1094a0000
Loaded images:
0: /var/containers/Bundle/Application/32EBE179-9BBE-4B3D-83F3-B80E521314D2/Spotify-Eevee.app/Spotify
1: /usr/lib/dyld
2: /var/containers/Bundle/Application/32EBE179-9BBE-4B3D-83F3-B80E521314D2/Spotify-Eevee.app/Frameworks/SpotifyShared.framework/SpotifyShared
3: /System/Library/Frameworks/SystemConfiguration.framework/SystemConfiguration
4: /System/Library/Frameworks/QuartzCore.framework/QuartzCore
5: /System/Library/Frameworks/CoreText.framework/CoreText
6: /System/Library/Frameworks/Security.framework/Security
7: /System/Library/Frameworks/MediaToolbox.framework/MediaToolbox
8: /System/Library/Frameworks/CoreMedia.framework/CoreMedia
9: /System/Library/Frameworks/AudioToolbox.framework/AudioToolbox
10: /System/Library/Frameworks/CoreMotion.framework/CoreMotion
11: /System/Library/Frameworks/WebKit.framework/WebKit
12: /usr/lib/libc++.1.dylib
13: /System/Library/Frameworks/AVKit.framework/AVKit
14: /System/Library/Frameworks/MessageUI.framework/MessageUI
15: /System/Library/Frameworks/StoreKit.framework/StoreKit
16: /System/Library/Frameworks/AVFoundation.framework/AVFoundation
17: /System/Library/Frameworks/Accelerate.framework/Accelerate
18: /System/Library/Frameworks/ExternalAccessory.framework/ExternalAccessory

{"ProcessBundleID":"com.spotify.clienteevee","ProcessName":"Spotify","Culprit":"Unknown"}



This is the log from the "Cr4shed" app.

**Comment by khoatranzxcqwe** [comment]
> disable tweak injection with choicy



> disable tweak injection with choicy

I tried . Not work.

Thank you.

**Comment by khoatranzxcqwe** [comment]
> Use the debug version
Not work. Still crash.

Thank you

**Comment by asdfzxcvbn** [comment]
> Date: 6/20/24, 10:13 AM Process: Spotify Bundle id: com.spotify.clienteevee Device: iPhone 11 Pro Max, iOS 14.4 Bundle version: 8.9.48 Exception type: EXC_SOFTWARE (SIGABRT) Exception subtype: EXC_UNIX_ABORT Exception codes: 0x0000000000010002, 0x0000000000000000 Culprit: Unknown Termination Reason: dyld: Using shared cache: 0B7D65F0-E3CC-3727-A3E6-5D6827109324 Library not loaded: /System/Library/Frameworks/AVFAudio.framework/AVFAudio Referenced from: /private/var/containers/Bundle/Application/32EBE179-9BBE-4B3D-83F3-B80E521314D2/Spotify-Eevee.app/Spotify Reason: image not found Triggered by thread: 0 Thread name: Call stack: 0 dyld 0x000000010947f440 0x109428000 + 357440 // __abort_with_payload 1 dyld 0x00000001094876e0 0x109428000 + 390880 // abort_with_payload_wrapper_internal 2 dyld 0x0000000109487714 0x109428000 + 390932 // __unw_set_reg.cold.1 3 dyld 0x000000010942d05c 0x109428000 + 20572 // dyld::fastBindLazySymbol(ImageLoader**, unsigned long) 4 dyld 0x00000001094300b8 0x109428000 + 32952 // dyld::_main(macho_header const*, traaunsigned long, int, char const**, char const**, char const**, unsigned long*) 5 dyld 0x0000000109429258 0x109428000 + 4696 // dyldbootstrap::start(dyld3::MachOLoaded const*, int, char const**, dyld3::MachOLoaded const*, unsigned long*) 6 dyld 0x0000000109429038 0x109428000 + 4152 // _dyld_start Register values: PC: 0x16f5ce690 LR: 0x16f5ce6d0 CPSR: 0x947f440 x0: 0x4400000006 x1: 0x6 x2: 0x1 x3: 0x16f5ceb00 x4: 0xb5 x5: 0x16f5ce700 x6: 0x0 x7: 0x0 x8: 0x0 x9: 0x20 x10: 0x9 x11: 0x1 x12: 0x65 x13: 0xf0 x14: 0xe3 x15: 0xcc x16: 0x37 x17: 0x209 x18: 0x1094797b4 x19: 0x0 x20: 0x0 x21: 0x16f5ce700 x22: 0xb5 x23: 0x16f5ceb00 x24: 0x1 x25: 0x6 x26: 0x16f5cf818 x27: 0x1094a0000 x28: 0x1094a0000 Loaded images: 0: /var/containers/Bundle/Application/32EBE179-9BBE-4B3D-83F3-B80E521314D2/Spotify-Eevee.app/Spotify 1: /usr/lib/dyld 2: /var/containers/Bundle/Application/32EBE179-9BBE-4B3D-83F3-B80E521314D2/Spotify-Eevee.app/Frameworks/SpotifyShared.framework/SpotifyShared 3: /System/Library/Frameworks/SystemConfiguration.framework/SystemConfiguration 4: /System/Library/Frameworks/QuartzCore.framework/QuartzCore 5: /System/Library/Frameworks/CoreText.framework/CoreText 6: /System/Library/Frameworks/Security.framework/Security 7: /System/Library/Frameworks/MediaToolbox.framework/MediaToolbox 8: /System/Library/Frameworks/CoreMedia.framework/CoreMedia 9: /System/Library/Frameworks/AudioToolbox.framework/AudioToolbox 10: /System/Library/Frameworks/CoreMotion.framework/CoreMotion 11: /System/Library/Frameworks/WebKit.framework/WebKit 12: /usr/lib/libc++.1.dylib 13: /System/Library/Frameworks/AVKit.framework/AVKit 14: /System/Library/Frameworks/MessageUI.framework/MessageUI 15: /System/Library/Frameworks/StoreKit.framework/StoreKit 16: /System/Library/Frameworks/AVFoundation.framework/AVFoundation 17: /System/Library/Frameworks/Accelerate.framework/Accelerate 18: /System/Library/Frameworks/ExternalAccessory.framework/ExternalAccessory
> 
> {"ProcessBundleID":"com.spotify.clienteevee","ProcessName":"Spotify","Culprit":"Unknown"}
> 
> This is the log from the "Cr4shed" app.

your iOS version does not support the latest version of spotify, make an old ipa
