### ISSUE TITLE
[Bug] Spotify shows up warning off how songs play in random order and start playing songs in random order

### ISSUE THREAD

**Issue by rayanshchauhan05** [whoeevee/EeveeSpotify#205]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

When I go to a random playlist and try to switch and play a random song from the list it throws up the warning of how I can do that with premium and then goes onto a play completely different song.

**Comment by whoeevee** [comment]
https://github.com/whoeevee/EeveeSpotify/blob/swift/common_issues.md#if-all-tracks-are-skipped-a-song-stops-as-soon-as-you-play-it-or-you-see-the-you-discovered-a-premium-feature-popup-when-trying-to-play-a-song
