### ISSUE TITLE
Cant play songs in random order

### ISSUE THREAD

**Issue by vedantd25** [whoeevee/EeveeSpotify#206]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

![IMG_4172](https://github.com/whoeevee/EeveeSpotify/assets/95394678/818529c2-792a-4170-b4f7-51943f423ac8)
I have dynamic patching turned on,all the other feature work perfectly but i cant play songs in random order from a playlist.Although this could be solved previously by changing patching to static,restarting the app,changing patching back to dynamic and restarting the app in v4.0,it does not solve the problem in v4.2.

Using eevee spotify version 4.2-8.9.48 on iPhone 13 on iOS 17.4,i faced the same issue on version 4.0-8.9.42

**Comment by asdfzxcvbn** [comment]
unfortunate

**Comment by asdfzxcvbn** [comment]
maybe try https://github.com/whoeevee/EeveeSpotify/blob/swift/common_issues.md#unable-to-play-songs
