### ISSUE TITLE
[Bug] Debs Files (Tweak) not working at all

### ISSUE THREAD

**Issue by franzkekko23** [whoeevee/EeveeSpotify#207]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

I can see EeveeSpotify in the Spotify but free subscription is showing and there are ads. So it seems the tweak version doesn’t work at all instead of the ipa version which works just fine.

**Comment by franzkekko23** [comment]
I didn’t set patching method. Now it worksq

**Comment by yodaluca23** [comment]
Yea, for some reason the default patching method is just completely blank...
