### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Marco1250000000** [whoeevee/EeveeSpotify#208]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

Widget show only grey screen and if you click it it open spotify…is it possible to do working widget?

**Comment by Bryceshaw06** [comment]
I think it has to be installed with Trollstore over top of the App Store version for widgets to work.

**Comment by whoeevee** [comment]
widgets only work with TrollStore, it’s mentioned in common issues
