### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by Sp1derling** [whoeevee/EeveeSpotify#209]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

Please help me i download the zip on my iphone but i cant open it i am new to this please help me

**Comment by asdfzxcvbn** [comment]
look into signing services like AppTesters and MapleSign (signulous and the like are a waste of money)
