### ISSUE TITLE
Settings are reset to a default when app is restarted

### ISSUE THREAD

**Issue by samuelawachie** [whoeevee/EeveeSpotify#21]
IOS: 15.8.2
Sideload tool: Sideloadly
Version: Obj-C version 1.2

I tried the Swift v1.2 version, and was getting ads and was unable to skip (basically free spotify). So I am thankful the ObjC version worked for me.
On the one that worked (the ObjC version), I  noticed that some parts of the Settings are reset to a default configuration when you restart the application (Content preferences, Playback). There could be more categories, but those are the two that I noticed that always changed and they're the two that I need to stay put with what I've set. So that means that everytime I load the app, I have to go to settings to set my preferences over and over again.

I also don't know why the Swift version had issues with my device. But I suppose i have to be thankful that at least, one's working.

Good job on this.

Edit: I installed it over my old 8.6.92 version so that I don't lose my cache and settings. 
Edit2: As a matter of interest, how do you guys come up with these names? uYou, whoeevee and now Eevee? I'd like what you guys are smoking lol! :rofl:

**Comment by asdfzxcvbn** [comment]
that's intentional. the file we write to contains some preferences (like autoplay) and the file is overwritten every app launch.

**Comment by asdfzxcvbn** [comment]
we might "fix" this by intercepting settings changes

**Comment by whoeevee** [comment]
resolved in Swift 1.4

**Comment by samuelawachie** [comment]
> resolved in Swift 1.4

So I see. Well done man!
If only this can now be released as ObjC as well, as that version seems to be more stable (for me at least)
