### ISSUE TITLE
Siri support not working [Bug] 

### ISSUE THREAD

**Issue by RishiSuthar** [whoeevee/EeveeSpotify#210]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

Siri does not work with this tweak, tried to ask her to play music and it says "you will need to change spotify account details for this"

**Comment by asdfzxcvbn** [comment]
how did you install the app?

**Comment by RishiSuthar** [comment]
> how did you install the app?

SideStore ipa

**Comment by asdfzxcvbn** [comment]
yeah then it won't work, it should be restricted to trollstore i believe

**Comment by RishiSuthar** [comment]
> yeah then it won't work, it should be restricted to trollstore i believe

Oh I see, the problem is that there’s no troll store for iOS 17.0.1 and above

**Comment by asdfzxcvbn** [comment]
shouldn't have updated

**Comment by RishiSuthar** [comment]
> shouldn't have updated

Fr
