### ISSUE TITLE
[Feature Request] hide podcasts and audiobooks in home

### ISSUE THREAD

**Issue by goof320** [whoeevee/EeveeSpotify#212]
either through disabling them in the "all" tab or just defaulting to selecting the "music" tab in spotify via a toggle in settings, this would be cool. spotify keeps trying to show me stupid shit like joe rogan and smosh at the top of the app despite never clicking on a podcast in my life. it's annoying! sorry if this is out of scope for this mod :p

**Comment by goof320** [comment]
nvm i just saw the other closed issue about this :PP

**Comment by asdfzxcvbn** [comment]
out of scope :3
