### ISSUE TITLE
[Bug] resuming a song with repeat on restarts the song at the point of the resume

### ISSUE THREAD

**Issue by limited-smh** [whoeevee/EeveeSpotify#218]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

basically, once you reopen the app, the repeat system for some reason caches to the point that the app was opened. this causes the repeat point at the end of the song to repeat at the point the song was when you opened the app.

https://github.com/whoeevee/EeveeSpotify/assets/122931112/eaff1b56-b1cf-4315-9eb7-329fdee146c1

**Comment by Cosmic1212** [comment]
I've had this issue happen to me sometimes too. How did you install it with? Sideloadly? Appdb?

**Comment by whoeevee** [comment]
it’s actually weird issue and probably not related to EeveeSpotify, as the tweak doesn’t affect playback at all

but it’s definitely not because of the installation method (code signing), and debug IPA primarily helps if you experience a crash, as it includes debug symbols
