### ISSUE TITLE
Crash on iOS 14.8.1 with Checkra1n

### ISSUE THREAD

**Issue by jetblackrx89** [whoeevee/EeveeSpotify#219]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

Uninstalled all prior Spotify-related tweaks, fully uninstalled the Spotify app to clear any only caches and re-downloaded it, then downloaded the latest of the following and imported into Zebra to install. 

com.eevee.spotify_4.3_iphoneos-arm.deb
org.swift.protobuf.swiftprotobuf_1.26.0_iphoneos-arm.deb

Spotify app immediately crashes at start. Tried the maximum version of 8.9.48 that still supports iOS 14 and as old as 8.6.42 (last version to work with Spotilife tweak). Same result -- immediate crash. Uninstalling Eevee let the app work normally on both versions. Ended up restoring Spotiife by:

1) Deleting Spotify (again, this is required to clear some cached data that can cause issues crashes of their own if downgrading.)
2) Manually installing Spotify 8.6.42
3) Reinstalling Spotilife1.8

**Comment by whoeevee** [comment]
have you installed orion runtime as well?
and send the crashlog

**Comment by whoeevee** [comment]
are there Orion console messages? get them using Console.app or `idevicesyslog | grep Orion`

**Comment by whoeevee** [comment]
well, EeveeSpotify really seems broken on iOS 14 due to classes that are not present in the older Spotify versions
can you specify the latest available Spotify version for iOS 14? 8.9.48 requires iOS 15

**Comment by whoeevee** [comment]
try installing this deb from github actions: https://github.com/whoeevee/EeveeSpotify/actions/runs/9730023303
does it resolve the crash?

**Comment by whoeevee** [comment]
install 8.9.8

**Comment by whoeevee** [comment]
tweak doesn’t affect smart shuffle
