### ISSUE TITLE
CarPlay Support

### ISSUE THREAD

**Issue by 3lack5ky** [whoeevee/EeveeSpotify#22]
Is it possible to add CarPlay support for installation via Trollstore?

**Comment by 3lack5ky** [comment]
After some testing, CarPlay seems to be broken, the app appears in the CarPlay interface, but when I tap on the icon, the app opens, loads for a second and then crashes. This also crashes the Spotify app on the phone.

**Comment by ggustavo509** [comment]
are you jailbrocken?

**Comment by 3lack5ky** [comment]
No, I’m using Trollstore 2.0.15, on IOS 17.

**Comment by popeyelau** [comment]
CarPlay works fine for me.

**Comment by 3lack5ky** [comment]
Did you use the ipa from GitHub? Did you use the 1.2 or 1.3 version?

**Comment by fugegate** [comment]
> CarPlay works fine for me.

How did you get the icon to appear? I don't even see the icon. I installed through appdb. Should I install through trollstore? And if so how do I install trollstore?

**Comment by popeyelau** [comment]
resigned  the ipa use myself develop certificates. （has CarPlay capabilities）

> > CarPlay works fine for me.
> 
> How did you get the icon to appear? I don't even see the icon. I installed through appdb. Should I install through trollstore? And if so how do I install trollstore?

resigned  the ipa use myself develop certificates. （has CarPlay capabilities）

**Comment by 3lack5ky** [comment]
CarPlay is working perfectly on version 2.1
