### ISSUE TITLE
[Bug] app always not working after a few days when freshly downloaded

### ISSUE THREAD

**Issue by SkibidiDragonRizz** [whoeevee/EeveeSpotify#220]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

When i first downloaded the ipa it went all super but after a few days the app wasnt working anymore. Then i downloaded again, like normal worked fine, but then again agter few days: app unavaible. Help me with this bug

**Comment by ElliotCHEN37** [comment]
a free apple developer has a 7-day limitation, if you don't want to pay for a new certificate, you can try to re-install the app manually (if you're using tools like sideloadly, alt store, side store. just enable the auto refresh)
