### ISSUE TITLE
[Request] Android Version

### ISSUE THREAD

**Issue by mjustboring** [whoeevee/EeveeSpotify#221]
Would it be possible for you to provide it for android too. In the available mods lyrics aren't working...

**Comment by yodaluca23** [comment]
I think you would be better off asking someone from the revaced team...

**Comment by asdfzxcvbn** [comment]
yeah sure i'll just need your full name, home address, and social security number

**Comment by whoeevee** [comment]
it’s possible to create an Android module that will replace lyrics with different providers in the same way, but it’s better to request it from someone more familiar with Android, like the revanced team mentioned above

**Comment by asdfzxcvbn** [comment]
btw xmanager has confirmed they wont implement lyrics

**Comment by yodaluca23** [comment]
> it’s possible to create an Android module that will replace lyrics with different providers in the same way, but it’s better to request it from someone more familiar with Android, like the revanced team mentioned above

Yeah, I was thinking along the lines of this. I'm pretty sure the implementation would be very similar since I'm fairly certain that the android Spotify application uses protocol buffers just like the iOS app for lyrics.
