### ISSUE TITLE
[Bug] I get ads when listing 

### ISSUE THREAD

**Issue by HOURSSSSSSSSS** [whoeevee/EeveeSpotify#224]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

I’m getting ads every 30 minutes while listing to Spotify be it on my phone or connected to my console etc

**Comment by asdfzxcvbn** [comment]
![image](https://github.com/whoeevee/EeveeSpotify/assets/109937991/e49e5684-fa42-4f16-b0c7-4111aefb1114)
