### ISSUE TITLE
Switching between actual and romaji lyrics for Japanese songs using Genius

### ISSUE THREAD

**Issue by GinyuSpecialForce** [whoeevee/EeveeSpotify#225]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

would be cool idk if possible

**Comment by yodaluca23** [comment]
Should be easy, to add a switch for Romaji lyrics:

Search for the song first here for Romaji lyrics:

https://genius.com/artists/Genius-romanizations/songs

If not present then just do what it does now, and search the rest of genius.

**Comment by yodaluca23** [comment]
> Should be easy, to add a switch for Romaji lyrics:
> 
> Search for the song first here for Romaji lyrics:
> 
> https://genius.com/artists/Genius-romanizations/songs
> 
> If not present then just do what it does now, and search the rest of genius.

Or it could append (Romanized) to the end of the song title when searching for the song, if yields no results then get normal lyrics.

**Comment by yodaluca23** [comment]
> Or it could append (Romanized) to the end of the song title when searching for the song, if yields no results then get normal lyrics.

In my testing, this should work, converting https://github.com/whoeevee/EeveeSpotify/blob/swift4.3/Sources/EeveeSpotify/Lyrics/DataSources/GeniusLyricsDataSource.swift to a cURL request:

```
curl -X GET "https://api.genius.com/search/song?q=your_query" \
-H "X-Genius-iOS-Version: 6.21.0" \
-H "X-Genius-Logged-Out: true" \
-H "User-Agent: Genius/1109 CFNetworkVersion DarwinVersion"
```

Then from here
https://github.com/whoeevee/EeveeSpotify/blob/e8e77f07cfb1e37dbb0837bb44e9f27932ac17a7/Sources/EeveeSpotify/Lyrics/LyricsRepository.swift#L17
we know it constructs the quarry in the form of "{SongName} {Artist}"

So if for example we run

```
curl -X GET "https://api.genius.com/search/song?q=How%20You%20Like%20That%20BlackPink" \
-H "X-Genius-iOS-Version: 6.21.0" \
-H "X-Genius-Logged-Out: true" \
-H "User-Agent: Genius/1109 CFNetworkVersion DarwinVersion"
```

We get the expected result of the non-romaji song info https://pastebin.com/nhD3trNk 
While if we append "(Romanized)" to the end of our quary such

```
curl -X GET "https://api.genius.com/search/song?q=How%20You%20Like%20That%20BlackPink%20(Romanized)" \
-H "X-Genius-iOS-Version: 6.21.0" \
-H "X-Genius-Logged-Out: true" \
-H "User-Agent: Genius/1109 CFNetworkVersion DarwinVersion"
```

We get the song info of the romaji version! https://pastebin.com/EECn78jG

So, it should be simple to add a toggle in settings for Romaji lyrics when available, and add an if statement on line 17 of LyricsRepository.swift, specified above. If that setting is toggled then:
```let query = "\(strippedTitle) \(artist) (Romanized)"```
Else keep it how it is now:
```let query = "\(strippedTitle) \(artist)"```

Then additional logic would need to be added to the error handling, where if it gets an error while it had originally searched with the appended "(Romanized)" then try again without it.

**Comment by yodaluca23** [comment]
I have implemented first searching for it with "(Romanized)" appended then without it, if no song is found, in my fork.
https://github.com/yodaluca23/EeveeSpotify
I just have absoulty no idea how to add a switch to the settings menu, and how to check it's status... But that should be the easy part for someone knowledgeable.
You can get the debs from the workflow https://github.com/yodaluca23/EeveeSpotify/actions/runs/9788525123

**Comment by yodaluca23** [comment]
> I have implemented first searching for it with "(Romanized)" appended then without it, if no song is found, in my fork. [yodaluca23/EeveeSpotify](https://github.com/yodaluca23/EeveeSpotify) I just have absoulty no idea how to add a switch to the settings menu, and how to check it's status... But that should be the easy part for someone knowledgeable. You can get the debs from the workflow [yodaluca23/EeveeSpotify/actions/runs/9788525123](https://github.com/yodaluca23/EeveeSpotify/actions/runs/9788525123)

Here you can see it working:
![IMG_0013](https://github.com/whoeevee/EeveeSpotify/assets/67206487/06aadec6-820c-4498-b6ba-211835c8152a)

Before:
![IMG_8BED9440630D-1](https://github.com/whoeevee/EeveeSpotify/assets/67206487/c7cd375f-1996-496d-b560-2e9cb8759e58)

Also, anyone is free to use implement code from my fork, PR it copy/paste it idc.

**Comment by asdfzxcvbn** [comment]
@GinyuSpecialForce you can use his fork

**Comment by yodaluca23** [comment]
@GinyuSpecialForce I got it working to be togglable, and added a switch in settings, that only appears if Genius is selected as the source. You can get the Debs from the workflow run https://github.com/yodaluca23/EeveeSpotify/actions/runs/9802758520

@asdfzxcvbn would you accept a PR? I know the code is messy, and probably inefficient, you could edit it to be better. But I would love to be able to contribute, and get this in the main branch :)

**Comment by whoeevee** [comment]
open the pr

**Comment by GinyuSpecialForce** [comment]
Whoa thanks so much I didn’t expect this much contribution

**Comment by yodaluca23** [comment]
Btw, Musixmatch Romaji is possible.
```
	curl -G \
     --url "https://apic.musixmatch.com/ws/1.1/crowd.track.translations.get" \
     --data-urlencode "track_spotify_id=4SFknyjLcyTLJFPKD2m96o" \
	 --data-urlencode "selected_language=rkr" \
     --data-urlencode "q_track= " \
     --data-urlencode "usertoken=YOUR_MUSIXMATCH_USER_TOKEN" \
     --data-urlencode "app_id=mac-ios-v2.0"
```
for selected_language is the original language two letter code, in this case Korean "kr" prefixed with a "r" for romaji (so "r{Code}"), its in a weird format, where it matches each line to a translation, so you would have to take the original lyrics and recursively find and replace, or something, it is possible...

**Comment by yodaluca23** [comment]
> Btw, Musixmatch Romaji is possible.

Got it working https://github.com/yodaluca23/EeveeSpotify/tree/952c57683c84d906dd3f342eaadf4fe93929233d
Debs: https://github.com/yodaluca23/EeveeSpotify/actions/runs/9817306830

**Comment by yodaluca23** [comment]
> > Btw, Musixmatch Romaji is possible.
> 
> Got it working [yodaluca23/EeveeSpotify@`952c576`](https://github.com/yodaluca23/EeveeSpotify/tree/952c57683c84d906dd3f342eaadf4fe93929233d) Debs: [yodaluca23/EeveeSpotify/actions/runs/9817306830](https://github.com/yodaluca23/EeveeSpotify/actions/runs/9817306830)

It doesn't work for some songs that do I have it, and I have no idea why...

**Comment by sickleox2** [comment]
Does it work for russian as well?

**Comment by yodaluca23** [comment]
> Does it work for russian as well?

It should work for any for the genius implementation it simply adds "(Romanized)" to the end of the search query. And for the MusixMatch implementation, it takes the first letter of the language and then add an R in front of it, and then uses that to fetch the romanized translation as long as MusixMatch has the Romanization it should work... if you have a specific song you'd like me to test I can.

**Comment by sickleox2** [comment]
Thank you for the reply. 

[https://open.spotify.com/track/3Fm3ksqwSa7QqqdBqsVhnc?si=zoUJCy5_TRCK_bPql6t-iQ](url)

This song has MusixMatch lyrics, could you try? Thank you

**Comment by yodaluca23** [comment]
> Thank you for the reply. 
> 
> 
> 
> [https://open.spotify.com/track/3Fm3ksqwSa7QqqdBqsVhnc](url)
> 
> 
> 
> This song has MusixMatch lyrics, could you try? Thank you

That song, neither any of the Russian songs I could find online have translations with MusixMatch... but it should work if MusixMatch has it.

Also, please make sure in the future anytime you share a link to remove any "?si=" parameters as they are solely for crosssite tracking...

**Comment by sickleox2** [comment]
Weird, here it says that Russian is automatically romanized:

[https://support.musixmatch.com/article/277-which-languages-are-automatically-romanized-can-i-contribute-to-the-romanization](url)

**Comment by yodaluca23** [comment]
> Weird, here it says that Russian is automatically romanized:
> 
> [https://support.musixmatch.com/article/277-which-languages-are-automatically-romanized-can-i-contribute-to-the-romanization](url)

Yes, I realized this, but if you open the MusixMatch app, and go to that song all the translations are at 0%
