### ISSUE TITLE
Unable to deactivate this app in SideStore

### ISSUE THREAD

**Issue by Blockr22** [whoeevee/EeveeSpotify#226]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

Whenever i try to deactivate this app in SideStore i get this error. I didn’t have extensions enabled if that makes a difference though. I can deactivate uYouEnhanced just fine & i always keep extensions disabled for everything i side-load due to limited app id’s
![IMG_2759](https://github.com/whoeevee/EeveeSpotify/assets/96648629/fc24bd3d-25d9-4b2d-907c-31252281dc73)

**Comment by yodaluca23** [comment]
SideStore Bug
https://github.com/SideStore/SideStore/issues/632

**Comment by Blockr22** [comment]
Thnx @yodaluca23, seems like SideStore team has to fix it then. Other sideloaded apps works without issues, don’t know what’s wrong with Spotify. If i remember it correctly old Spotify ipa i used from jackcracks were deactivating just fine. Don’t know what changed

**Comment by yodaluca23** [comment]
> Thnx @yodaluca23, seems like SideStore team has to fix it then. Other sideloaded apps works without issues, don’t know what’s wrong with Spotify. If i remember it correctly old Spotify ipa i used from jackcracks were deactivating just fine. Don’t know what changed

I think it's tweaked apps it has a problem with, idk why.

**Comment by Blockr22** [comment]
Even the older Spotify i was using was tweaked but worked without any issues
