### ISSUE TITLE
[Bug] Autoplay not working

### ISSUE THREAD

**Issue by Lorenzoformi2001** [whoeevee/EeveeSpotify#230]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

Autoplay doesn't work since first releases of this tweak, is it normal or could it be an individual problem?

**Comment by asdfzxcvbn** [comment]
did you disable shuffle

are you sure you have autoplay enabled in spotify settings

explain exactly how it doesnt work

**Comment by Lorenzoformi2001** [comment]
yes I disabled it, plus option in settings is on. I tried to switch it off and then on cause I was thinking it could be a bug, but still didn't manage to make it work. Basically when I'm listening to a single song from search or from a single release, once it finishes Spotify doesn't come up with more similar songs.

**Comment by jfk2424** [comment]
I have the same bug, please fix this its annoying

**Comment by asdfzxcvbn** [comment]
tweak shouldnt change that with dynamic mode so
