### ISSUE TITLE
[Request] Can you make lyrics translate in Spotify using Musixmatch api

### ISSUE THREAD

**Issue by NON1919** [whoeevee/EeveeSpotify#232]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

Can you do it pls

**Comment by yodaluca23** [comment]
With the recent integration with MusixMatch Romaji translations it should be easy and mostly reuse the same code.

**Comment by whoeevee** [comment]
> With the recent integration with MusixMatch Romaji translations it should be easy and mostly reuse the same code.

I'm implementing translation and romanization now, and also refactoring and optimizing your code

**Comment by NON1919** [comment]
ok so i will close this
