### ISSUE TITLE
[feature] add Spotify Dj

### ISSUE THREAD

**Issue by RishiSuthar** [whoeevee/EeveeSpotify#233]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

Feature : add Spotify Dj

**Comment by asdfzxcvbn** [comment]
![image](https://github.com/whoeevee/EeveeSpotify/assets/109937991/d2229162-fca6-47de-a16a-62ff8dc8b1e3)
