### ISSUE TITLE
[Question] What about storing locally?

### ISSUE THREAD

**Issue by acquitelol** [whoeevee/EeveeSpotify#234]
You mentioned in the README that implementing features such as playlist downloading is not possible because it's server sided, but I propose the following idea:

1. Use the lyrics service to get a UUID of the song such that it can be found on YouTube or any service where it can be downloaded without the Widevine DRM to prevent playback
2. Download the song as an MP3 in the highest bitrate allowed by the service, and organize it into a folder in Spotify's Documents directory with the playlist name, or something in that nature
3. When the user goes offline and attempts to start playback, first try to find the song in that Documents directory, and if it exists play that instead, otherwise notify the song wasn't or couldn't be downloaded

This, of course, sounds easy on paper, but I believe it should definitely be possible. If it's too much of a hassle I can look into trying to find a robust way to do this myself :3

**Comment by acquitelol** [comment]
I didn't read the last part - nevermind lmao.

I'll open a PR eventually with my findings.

**Comment by yodaluca23** [comment]
Hey @acquitelol love your work on Discord mods btw.

If you could implement actually downloading from Spotify instead like how [Zotify](https://github.com/zotify-dev/zotify) works, I think this would be better.

https://github.com/whoeevee/EeveeSpotify/issues/177#issuecomment-2151244624

**Comment by whoeevee** [comment]
It would be nice if you could implement the downloading feature as natively as possible. You can add additional settings, etc., but the playback must be seamless and not occur from a third-party menu. Additionally, songs should be shown as downloaded in playlists.

**Comment by acquitelol** [comment]
> It would be nice if you could implement the downloading feature as natively as possible. You can add additional settings, etc., but the playback must be seamless and not occur from a third-party menu. Additionally, songs should be shown as downloaded in playlists.

Yeah, of course. When it's done I'm hoping it'll look exactly the same in the front-end as if it was downloaded natively. I'm not quite sure if an external API will be needed or not yet because I may be able to use the fact that songs can be played at will without premium to download a pure mp3 without DRM, but I'll have to look into it further

**Comment by acquitelol** [comment]
> Hey @acquitelol love your work on Discord mods btw.
> 
> If you could implement actually downloading from Spotify instead like how [Zotify](https://github.com/zotify-dev/zotify) works, I think this would be better.
> 
> [#177 (comment)](https://github.com/whoeevee/EeveeSpotify/issues/177#issuecomment-2151244624)

My idea is to swizzle the download playlist button, and then it'll create a json file in the documents directory that holds the playlist uuid and then each song that is inside the playlist (just an array of UUIDs), then it will save the mp3 itself in a different directory with the name of the file being the UUID itself.

At app start, if there is an internet connection and the user has chosen to do so, the code should try to sync every playlist with the json file to ensure it has the updated information, downloading any new songs as needed. Then, at offline playback time, it will just search for the UUID in the folder of mp3 files. If it finds it, then it will play that instead. If it doesn't, then it'll report an EeveeSpotify error or something.

You should be able to select whether you want playlists to be automatically synced or not, and if so, how often to do so (every app start being the most frequent, once every 6 months being the least frequent).

I believe every song also has a "download this song" button when you have premium but I don't remember if it does or not. If it doesn't then I might add it and it would simply save the song in the folder of mp3 files allowing you to play it whenever you're offline without it needing to be in a playlist.

I'm not sure whether it would be a good idea to be able to delete specific downloaded songs or just delete everything all at once, I may add both.

I'm open to suggestions!

**Comment by TNT599** [comment]
Seems theoretically possible and feasible, only thing I want to mention is Zotify and similar are just python scripts which I don't know how easy that is to run on ios and if they need to be translated into swift or something else to work. Might be easier to use the youtube based online ones especially if there's one with an easy to work with API.

**Comment by yodaluca23** [comment]
> Seems theoretically possible and feasible, only thing I want to mention is Zotify and similar are just python scripts which I don't know how easy that is to run on ios and if they need to be translated into swift or something else to work.

Well yes, the implementation would have to be ported to swift, but the logic should be the same...

> Might be easier to use the youtube based online ones especially if there's one with an easy to work with API.

Cobalt tools has a good API, but I think it would be infinitely better to download directly from Spotify, as that will have higher quality, ensure your getting the right song, and have the lyrics match properly (as YouTube downloads probably have intros and stuff), as well as others...

**Comment by Richard-NDC** [comment]
Hi there, i just find out some project that can help you with native download (download from youtube)

**Comment by NotDarkn** [comment]
> Hi there, i just find out some projects that can help you with native download (download from youtube)

tbf, downloading from YouTube is not the best idea mainly due to the fact that you could be downloading songs that have some weird into at the beginning or an outro at the end (depending on the song).

as @yodaluca23 said, "it would be infinitely better to download directly from Spotify"

**Comment by Richard-NDC** [comment]
> > Hi there, i just find out some projects that can help you with native download (download from youtube)
> 
> tbf, downloading from YouTube is not the best idea mainly due to the fact that you could be downloading songs that have some weird into at the beginning or an outro at the end (depending on the song).
> 
> as @yodaluca23 said, "it would be infinitely better to download directly from Spotify"

but we don’t know how to download it directly from spotify so youtube is the easiest way

**Comment by yodaluca23** [comment]
> > > Hi there, i just find out some projects that can help you with native download (download from youtube)
> 
> > 
> 
> > tbf, downloading from YouTube is not the best idea mainly due to the fact that you could be downloading songs that have some weird into at the beginning or an outro at the end (depending on the song).
> 
> > 
> 
> > as @yodaluca23 said, "it would be infinitely better to download directly from Spotify"
> 
> 
> 
> but we don’t know how to download it directly from spotify so youtube is the easiest way

Go look at Zotify source code... 

https://github.com/zotify-dev/zotify

**Comment by yodaluca23** [comment]
> Go look at Zotify source code...
> 
> [zotify-dev/zotify](https://github.com/zotify-dev/zotify)

Mainly https://github.com/zotify-dev/zotify/blob/21ef30844b2b2588f9e6db8e6e86423699730f92/zotify/track.py#L145

**Comment by Richard-NDC** [comment]
> > Go look at Zotify source code...
> > [zotify-dev/zotify](https://github.com/zotify-dev/zotify)
> 
> Mainly https://github.com/zotify-dev/zotify/blob/21ef30844b2b2588f9e6db8e6e86423699730f92/zotify/track.py#L145 to the end of that file...

i can read python but i can’t code swift, so can your team do it?

**Comment by igor199592** [comment]
problem spotify not working, Even the usual version of spotify 8.9.64, music has become not available everywhere, even in favorites

**Comment by An0n-00** [comment]
Hey Everyone
> it would be infinitely better to download directly from Spotify
I totally agree. What I've noticed in the last weeks, is that Spotify cashes songs locally and waits for internet connection to "release" the song from cash. I think this would be possible to circumvent. One would have to implement a local server and when the server recognizes that the user is offline, it jumps into action and acts as Spotify's backend. [That this works, you would have to listen the song before going offline oc.] 
What do y'all think?

**Comment by Kassra1** [comment]
I don't have anywhere to put my downloaded mp3s into on my files app there's no Spotify document so I have no where to put it in and I don't have local files anymore. Reply is appreciated. Thank you

**Comment by yodaluca23** [comment]
> I don't have anywhere to put my downloaded mp3s into on my files app there's no Spotify document so I have no where to put it in and I don't have local files anymore. Reply is appreciated. Thank you

That's not related to this and you already made an issue.

**Comment by Kassra1** [comment]
> > I don't have anywhere to put my downloaded mp3s into on my files app there's no Spotify document so I have no where to put it in and I don't have local files anymore. Reply is appreciated. Thank you
> 
> That's not related to this and you already made an issue.

Why's it not related the post is about downloaded mp3s which is what my issue is based around

**Comment by ElliotCHEN37** [comment]
We are talking about Spotify’s native downloading (A server-side Premium
feature), not downloading our own MP3 into Spotify (A freeware feature).
They’re different.

Kassra1 ***@***.***>於 2024年10月7日 週一，07:22寫道：

**Comment by littleblack111** [comment]
I want to propose an idea. What about since they need to download/cache the player, we just don't remove the cache, and as for downloading, we can just trick the server into thinking we're listening to the music, and never remove the cached music.

I know it's cached Becuz I was on a flight where the WiFi can only access their internal service(movie etc) and Spotify says it's offline but some music that I'm previously listening to still plays

**Comment by nyakokitsu** [comment]
Zotify uses Librespot to download tracks, it receives streams and saves them into audio files

**Comment by An0n-00** [comment]
> I want to propose an idea. What about since they need to download/cache the player, we just don't remove the cache, and as for downloading, we can just trick the server into thinking we're listening to the music, and never remove the cached music.

lol that is literally what i said here: 

https://github.com/whoeevee/EeveeSpotify/issues/234#issuecomment-2333404367

but I totally agree. it should be possible somehow...

**Comment by littleblack111** [comment]
oh i see, sry for the dupe lol

**Comment by TLAflash** [comment]
Use spot-dlp that uses Spotify

**Comment by An0n-00** [comment]
> Use spot-dlp that uses Spotify

can you be more specific? i cannot find anything on spot-dlp...

**Comment by nyakokitsu** [comment]
> > Use spot-dlp that uses Spotify
> 
> can you be more specific? i cannot find anything on spot-dlp...
@An0n-00, zspotify(uses librespot-python)

**Comment by abcdefghi39664** [comment]
Has there been a pr yet? I could try doing this with the info provided

**Comment by asdfzxcvbn** [comment]
> Has there been a pr yet? I could try doing this with the info provided

not yet. in fact i haven't seen any fork opened to try implementing this

**Comment by An0n-00** [comment]
> Has there been a pr yet? I could try doing this with the info provided

I would say go ahead and see where it leads too. (dont listen to mee tho 💀 ) 

@whoeevee ?

**Comment by asdfzxcvbn** [comment]
> > Has there been a pr yet? I could try doing this with the info provided
> 
> I would say go ahead and see where it leads too.

ofc, theres no harm in trying, and feedback will be provided in the PR if necessary

p.s. don't ping administrators

**Comment by yodaluca23** [comment]
> what if downloading was from qobuz? there would be easier downloads and higher quality music. this can be done through qobuz-dl or something

Qobuz is missing a lot of tracks Spotify has, if anything use Tidal with HIFI TUI. But that still doesn't solve the problem of finding the right track... Unless you want to start messing with APIs and use Tidal's search by ISRC, and use the ISRC from Spotify. I don't know if that route would be good though.
