### ISSUE TITLE
spotify crashes after injecting both debs into todays spotify update 8.9.54

### ISSUE THREAD

**Issue by mohkg1017** [whoeevee/EeveeSpotify#235]
crashes on opening with today's new spotify update version 8.9.54

**Comment by yodaluca23** [comment]
Both? You have to inject obviously the Eevee Spotify .deb swiftprotobuf and Orion…

**Comment by mohkg1017** [comment]
yes the com.eevee.spotify_4.3_iphoneos-arm.deb and org.swift.protobuf.swiftprotobuf_1.26.0_iphoneos-arm.deb like i always do

**Comment by yodaluca23** [comment]
> yes the com.eevee.spotify_4.3_iphoneos-arm.deb and org.swift.protobuf.swiftprotobuf_1.26.0_iphoneos-arm.deb like i always do

Yea, you forgot Orion make sure to also inject Orion. You can get it from here.

https://chariz.com

**Comment by mohkg1017** [comment]
orions already included in one of those debs, I checked the dylibs

**Comment by yodaluca23** [comment]
Ok, just tried on my Jailbroken XR 15.4, it does indeed crash on startup but produces no crash log. @whoeevee could you take a look?

This is the error from console.
```/Users/runner/work/orion/orion/orion/Sources/Orion/Tweak.swift:80: Fatal error: Error in tweak EeveeSpotify: Could not compute target class for hook SPTEncorePopUpDialogHook (targetNotFound)```
looks like Spotify just changed some views?

**Comment by Cosmic1212** [comment]
> Ok, just tried on my Jailbroken XR 15.4, it does indeed crash on startup but produces no crash log. @whoeevee could you take a look?
> 
> 
> 
> This is the error from console.
> 
> ```/Users/runner/work/orion/orion/orion/Sources/Orion/Tweak.swift:80: Fatal error: Error in tweak EeveeSpotify: Could not compute target class for hook SPTEncorePopUpDialogHook (targetNotFound)```
> 
> looks like Spotify just changed some views?

Y'all just wait until whoeeevee drops next update

**Comment by whoeevee** [comment]
should be fixed in 4.4

**Comment by asdfzxcvbn** [comment]
by the way @mohkg1017 

i suggest updating pyzule, orion is now autofixed so you only need eeveespotify and swiftprotobuf deb

**Comment by mohkg1017** [comment]
> by the way @mohkg1017
> 
> i suggest updating pyzule, orion is now autofixed so you only need eeveespotify and swiftprotobuf deb

yes I'm using the latest pyzule, orion was already installed, it was an issue with eevee and the latest spotify but the dev fixed the issue in 4.4
