### ISSUE TITLE
[Bug] Translation is available on Musixmatch but Eeveespotify doesn't display it

### ISSUE THREAD

**Issue by ElliotCHEN37** [whoeevee/EeveeSpotify#236]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

Translation is available on Musixmatch but eeveespotify doesn't display it...
![IMG_2902](https://github.com/whoeevee/EeveeSpotify/assets/109361374/5e6d18a4-b253-4afa-beee-3899fae89220)
![IMG_2904](https://github.com/whoeevee/EeveeSpotify/assets/109361374/3c357da0-bfbd-4c49-8b91-8908c1a02314)
![IMG_2903](https://github.com/whoeevee/EeveeSpotify/assets/109361374/9fc75e70-93aa-4cab-b6cd-939548bae08e)
![IMG_2905](https://github.com/whoeevee/EeveeSpotify/assets/109361374/99e96ea2-ae89-46d1-967c-2b89c2c48f86)

**Comment by whoeevee** [comment]
It's because some languages on Musixmatch don't match the ISO language codes. Chinese (Traditional) is represented as `z1`, not `zh` on Musixmatch. You can use a deb that doesn't block such languages: https://github.com/whoeevee/EeveeSpotify/actions/runs/9888455645

**Comment by ElliotCHEN37** [comment]
thanks

**Comment by ElliotCHEN37** [comment]
> It's because some languages on Musixmatch don't match the ISO language codes. Chinese (Traditional) is represented as `z1`, not `zh` on Musixmatch. You can use a deb that doesn't block such languages: https://github.com/whoeevee/EeveeSpotify/actions/runs/9888455645

which .deb patch file should I use?
