### ISSUE TITLE
[Bug] Spotify FAILS To Install

### ISSUE THREAD

**Issue by luhgarlicbread** [whoeevee/EeveeSpotify#239]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

I got an iPhone 11 iOS 16.3.1 jailbroken with Dopamine installed through TrollStore.
I just marked the second checkbox because I had to, but idk if it even applies here.

After deleting these tweaked Spotify apps, and more, the AppStore Spotify fails to install properly, even in an un jailbroken environment.
It’ll download from the AppStore, but when it’s done it’ll have the little “redownload” cloud next to it, clicking the app won’t launch it, but just start the download process again.

Additionally, any tweaked Spotify iPA installed through TrollStore will fail to launch, unless it is selected, using Choicy, to launch without springboard tweak injection. Never had this issue until I tried upgrading tweaked Spotify apps, after I got Spotify premium back after not having it for a bit. I had Eevee and SpotC++ installed at the same time and OOP I think I just remembered I forced some installation of a tweaked Spotify after getting the prompt on TrollStore. Well that probs messed me up.

What’s the game plan yo? Anyone ever experience this before? Is this even the right place to be posting this?? 😅😂😂
Thanks guys. God bless y’all!!

**Comment by asdfzxcvbn** [comment]
unrelated to eeveespotify

however check if the following solution works: https://www.reddit.com/r/Trollstore/s/Kl0hekzukg

**Comment by luhgarlicbread** [comment]
> unrelated to eeveespotify
> 
> however check if the following solution works: https://www.reddit.com/r/Trollstore/s/Kl0hekzukg

Worked. Thank you!!
