### ISSUE TITLE
[Feature Request] Disscussion AB Settings

### ISSUE THREAD

**Issue by yodaluca23** [whoeevee/EeveeSpotify#240]
Adding an AB settings menu would be very difficult I know, (I would've made this a discussion if it was enabled, feel free to convert) I don't expect this to be implemented anytime soon, this is simply where I am going to put my findings for others to observe and contribute.
My plan was to figure out what the network request is when Spotify sends the AB config, intercept it, show it in a list if the user changes an option, then save that to a variable, on app load incept the AB config, and update it with what the user changed.

The following are my findings so far.

Using MITM Proxy I was able to figure out that user AB settings are fetched from ```https://spclient.wg.spotify.com/user-customization-service/v1/customize``` the response is in protobuf (yay!) of course we don't have the .proto schematic, so we can't decode it directly.

Snippet from response (Hopefully this doesn't have any PII 😖):
```
��
�
�
,redacted-redacted-redacted-redacted-redacted:redacted��ˬ�2W
3
ios-share-foundationswift-impllink_preview_type��
exp-planner��F*	
defaultF
)
ios-feature-carplayv2show_jam_qr_code��exp-planner��G`
C
ios-feature-carplayv2*jam_home_entrypoint_exposure_session_limit��exp-planner��G"]
@
ios-feature-carplayv2'jam_home_entrypoint_exposure_time_limit��exp-planner��G"O
2
ios-feature-carplayv2shows_jam_home_entrypoint��exp-planner��Gk
P
)ios-sociallistening-joingroupsession-impl#is_profile_completion_sheet_enabled��exp-planner�G�
I
```

Another problem is that it uses caching, any requests after the initial return blank with a HTTP code 304, we would have to find where Spotify caches it? Or force it to refetch it? or instruct the user to sign in and out? I don't know.

Somebody reverse-engineered a Spotify protobuf schematic before, this being for podcast transcripts, but this means it is possible.
https://gist.github.com/TomBerger90/53b95d27a6146bfb2fcf83797cdec453

**Comment by yodaluca23** [comment]
I was able to make this MITM proxy script to override the if-none-match header, which checks if the eTag matches the cached one, with random garbage, causing it to fetch new config each time! This could probably be done in Swift as apart of the tweak.

```
import secrets
import string
from mitmproxy import ctx

def request(flow):
    if "spclient.wg.spotify.com/user-customization-service/v1/customize" in flow.request.pretty_url:
        headers = flow.request.headers
        if "If-None-Match" in headers:
            ctx.log.info(f"Replacing If-None-Match header: {headers['If-None-Match']}")
            random_str = ''.join(secrets.choice(string.ascii_letters + string.digits) for _ in range(8))
            headers["If-None-Match"] = "W/" + random_str
            ctx.log.info(f"New If-None-Match header: {headers['If-None-Match']}")
            flow.request.headers = headers
```

**Comment by whoeevee** [comment]
EeveeSpotify can already deserialize and modify data, including the remote configuration (AB settings). You can use the Reset Data option to delete all cached data, so Spotify will fetch it again upon launch.

Look at this function:
https://github.com/whoeevee/EeveeSpotify/blob/2c556da5cb5d9f832d9283f0dae0db24bdb4a977/Sources/EeveeSpotify/Premium/DynamicPremium%2BModifyFunctions.swift#L3-L10

You can debug it and modify anything you want. I don’t plan on adding any settings sections related to this.

**Comment by yodaluca23** [comment]
> EeveeSpotify can already deserialize and modify data, including the remote configuration (AB settings). 
> Look at this function:
> 
> https://github.com/whoeevee/EeveeSpotify/blob/2c556da5cb5d9f832d9283f0dae0db24bdb4a977/Sources/EeveeSpotify/Premium/DynamicPremium%2BModifyFunctions.swift#L3-L10

Oooo this is very intriguing, thank you for bringing this to my attention so if we can modify it, we just need a way to be able to read the current one at least the features off of it so the user can choose to override them. I guess we don't need to read the value, at least not with the first version.


> You can use the Reset Data option to delete all cached data, so Spotify will fetch it again upon launch.

OK, yeah I just tested it. This does work. It returns 304 Codes until I press the reset button then the first time after that, it successfully gives a 200 code and a response with the configuration. I didn't think about this sooner probably because I thought that wiped all data not just the cache.

> You can debug it and modify anything you want. I don’t plan on adding any settings sections related to this.

If I were to get this working, where would you want the settings section? Would you want it as another section next to customize, lyrics, and patching or would you want it inside one of those? probably customization?

**Comment by asdfzxcvbn** [comment]
> If I were to get this working, where would you want the settings section? Would you want it as another section next to customize, lyrics, and patching or would you want it inside one of those? probably customization?

if you make this, it should have its own section

however we aren't (currently) too interested in this, so you should leave the implementation in your fork if you finish (don't open PR)

**Comment by drpoutine** [comment]
this could be a good thing to have in order to add functions that spotify seem to just remove on a whim, i.e audio on external app share, especially when the lyrics feature gets updated and changed from time to time which tends to happen quite a bit on the alpha builds from testflight. there's a built in translator button (sourced from musixmatch i believe) that doesn't seem to be available for everyone
