### ISSUE TITLE
[Bug] AI DJ causes crash

### ISSUE THREAD

**Issue by goestohollywood** [whoeevee/EeveeSpotify#241]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

Forgive me if this has been mentioned in the "common issues" list but I didn't see it.

Currently using EeveeSpotify-4.4-8.9.54 and when attempting to use the AI DJ, the app crashes. iOS 17.5.1, iPhone 12.

**Comment by asdfzxcvbn** [comment]
dj is server-sided

**Comment by goestohollywood** [comment]
> dj is server-sided

Ah, okay. Wasn't sure. Thanks!
