### ISSUE TITLE
LRCLIB Fallback

### ISSUE THREAD

**Issue by Cosmic1212** [whoeevee/EeveeSpotify#242]
Create a LRCLIB fallback so we can still keep the syncing of the lyrics.

**Comment by yodaluca23** [comment]
Or, even even better idea have a option to enable fallback if it's enabled then open up a menu that lets you drag all three sources around whatever is on top will be primary and then if that fails then just go to one below that if that fails go to the one below it letting the user configure what to fall back and allow for all three sources as a fallback.

**Comment by asdfzxcvbn** [comment]
No

it would be a pretty rare case
