### ISSUE TITLE
[Bug] When playing pure music, the lyrics appear blank

### ISSUE THREAD

**Issue by ElliotCHEN37** [whoeevee/EeveeSpotify#246]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

When playing pure music, the lyrics appear blank. But the lyrics part should be hidden or displayed with prompts like this is pure music, please enjoy it.
![IMG_2953](https://github.com/user-attachments/assets/3b94d5ae-94c8-469a-b4d3-a27a52f8a82a)
![IMG_2952](https://github.com/user-attachments/assets/28defa9d-150a-4687-aeae-b4484a23d588)
![IMG_2951](https://github.com/user-attachments/assets/a74380d1-855e-4475-a55b-58cfb5f54eef)

**Comment by whoeevee** [comment]
implemented the prompt with cf6614a
It's a challenge to hide the lyrics card, see #253
