### ISSUE TITLE
[Feature Request] Beautiful Lyrics lyric provider

### ISSUE THREAD

**Issue by yodaluca23** [whoeevee/EeveeSpotify#252]
Beautiful Lyrics is a Spicetify extension that makes lyrics better, and fetches lyrics from its own API, (that gets it from a bunch of different sources)
https://github.com/surfbryce/beautiful-lyrics

This is how the request looks:
```
curl --request GET \
  --url https://beautiful-lyrics.socalifornian.live/lyrics/SPOTIFYTRACKID \
  --header 'authorization: Bearer litterallyAnythingCanGoHereItJustTakesItLOL'
  ```

If "Type" is "Line" its line-by-line lyrics, (ex. 1QxYHMZo3F2vyoIqbJl1P8) if "Type" is "Syllable" then it's syllable-timed lyrics, and we will have to splice it together to be one line... (ex. 1XZy2eprbATl4AnL9Fpsw1).

Outputs Somthing like this (Line):
https://pastebin.com/5y3UE7Uq

Syllable:
https://pastebin.com/sumJpJYR

If it doesn't have lyrics for a song (ex. 1eXjWnz7I5y7Cek7bro07s), then the body is empty, response header "content-length" is 0.

The extension supports Romainization but this is done locally on the client, the API still returns plain lyrics, and it doesn't make any extra calls, so unless we implement local processed Romainization, that will not be possible. (And that would be a separate project, that could probably apply to all the lyric sources).

I haven't come across any other possibilities for ether "Type" or anything other than what I've mentioned, if anyone does, or has any other insight please say so here.

I will work on implementing this on [my fork](https://github.com/yodaluca23/EeveeSpotify) and then open a PR.

**Comment by asdfzxcvbn** [comment]
.. another lyric provider? imo we already have a lot.. please don't open a PR, we don't need this

**Comment by yodaluca23** [comment]
> .. another lyric provider? imo we already have a lot.. please don't open a PR, we don't need this

Why not? The more options the better, no?

**Comment by asdfzxcvbn** [comment]
> Why not? The more options the better, no?

except theres already a significant amount of available options, musixmatch is literally used by spotify, genius has lyrics for almost every song, and lrclib is open and anyone can submit lyrics to it

really the only "needed" providers now are regional ones, like petitlyrics

**Comment by yodaluca23** [comment]
I was bored so I added it to my fork anyway. It'll just be sitting there if y'all ever wanna do anything with it it works great, has a lot of lyrics for a bunch of songs, all time synced... But I think if we do get any more, we should definitely add the feature of being able to let the user drag around a list of all of the sources for fallback priority, allowing it to fall back to each of them in whatever order the user wants.

Debs: https://github.com/yodaluca23/EeveeSpotify/actions/runs/9986621639

**Comment by NotDarkn** [comment]
> I was bored so I added it to my fork anyway, it was pretty easy (at least a lot easier then PetitLyrics). It'll just be sitting there if y'all ever wanna do anything with it it works great, has a lot of lyrics for a bunch of songs, all time synced... But I think if we do get any more, we should definitely add the feature of being able to let the user drag around a list of all of the sources for fallback priority, allowing it to fall back to each of them in whatever order the user wants.
> 
> Debs: https://github.com/yodaluca23/EeveeSpotify/actions/runs/9986621639



> .. another lyric provider? imo we already have a lot.. please don't open a PR, we don't need this

could change LRCLIB out for this instead then, i don't think anyone really uses LRCLIB but this would work well

**Comment by whoeevee** [comment]
> > I was bored so I added it to my fork anyway, it was pretty easy (at least a lot easier then PetitLyrics). It'll just be sitting there if y'all ever wanna do anything with it it works great, has a lot of lyrics for a bunch of songs, all time synced... But I think if we do get any more, we should definitely add the feature of being able to let the user drag around a list of all of the sources for fallback priority, allowing it to fall back to each of them in whatever order the user wants.
> > Debs: https://github.com/yodaluca23/EeveeSpotify/actions/runs/9986621639
> 
> > .. another lyric provider? imo we already have a lot.. please don't open a PR, we don't need this
> 
> then maybe LRCLIB could be changed out for this instead then? i don't think anyone really uses LRCLIB but this would work well

LRCLIB has been the default lyrics provider in EeveeSpotify for a while, and it's actively used. It has lyrics for numerous international songs and is the most open, allowing anyone to publish lyrics. I honestly prefer it over Beautiful Lyrics.

**Comment by yodaluca23** [comment]
> > then maybe LRCLIB could be changed out for this instead then? i don't think anyone really uses LRCLIB but this would work well
> 
> LRCLIB has been the default lyrics provider in EeveeSpotify for a while, and it's actively used. It has lyrics for numerous international songs and is the most open, allowing anyone to publish lyrics. I honestly prefer it over Beautiful Lyrics.

I'm not completely positive, but I'm pretty sure it gets lyrics from a bunch of different sources probably including libLRC...

**Comment by samuelawachie** [comment]
> 
> then maybe LRCLIB could be changed out for this instead then? i don't think anyone really uses LRCLIB but this would work well
>
LRCLIB is actually so good that a campaign had to be embarked upon to get it added to Spicetify. Some people with Spotify Premium even installed this ipa just because of LRCLIB. I personally prefer it to the default Musixmatch and find it to have more accurate lyrics and lyrics for obscure niche genres and songs. 
You're sadly VERY mistaken

**Comment by NotDarkn** [comment]
> > then maybe LRCLIB could be changed out for this instead then? i don't think anyone really uses LRCLIB but this would work well
> 
> LRCLIB is actually so good that a campaign had to be embarked upon to get it added to Spicetify. Some people with Spotify Premium even installed this ipa just because of LRCLIB. I personally prefer it to the default Musixmatch and find it to have more accurate lyrics and lyrics for obscure niche genres and songs. You're sadly VERY mistaken

fair enough, my apologies lol i'm just used to using Musixmatch as it has more lyrics for songs that i have on my playlists

**Comment by yodaluca23** [comment]
Just an update in case anyone cares.

- Added support for "Background" lyrics, the API has them labeled differently, I process them the same, just put "()" around them indicating background lyrics.
- Made it check the difference between one line's endTime and the next line's startTime, if there are more than 5 seconds I made it in between add a Music note line, indicating an instrumental section.
- I then later made the 5 seconds adjustable in settings.
- Rebased from this repo, and added support for the new romanized lyrics for all sources.

Debs: https://github.com/yodaluca23/EeveeSpotify/actions/runs/10023017983

**Comment by yodaluca23** [comment]
Just wanted to say, that BeautifulLyrics uses lyrics from Apple Music, which does have excellent lyrics, and that the dev of it is planning to also added Musixmatch.

Also, right now my fork just submits crap as auth bearer instead of an actual Spotify token, but the BeautiulLyrics API requires one if the lyrics for that song are not cached on their server already. If someone knows how to take the one from the iOS client, it'd be appreciated.
