### ISSUE TITLE
[BUG] App gets laggy for seemingly no reason

### ISSUE THREAD

**Issue by mxrecki** [whoeevee/EeveeSpotify#254]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

The app gets **really** laggy after using it for a minute or two, for me

**Comment by asdfzxcvbn** [comment]
please describe your hardware

**Comment by mxrecki** [comment]
> please describe your hardware

i’m using a iphone 12, ios 18 beta, with the current version of eevee spotify

**Comment by asdfzxcvbn** [comment]
if anything i blame the iOS beta, nobody else reports this and the tweak itself shouldnt slow down the app
