### ISSUE TITLE
[Bug] Premium Tab on iPad

### ISSUE THREAD

**Issue by wlxxd** [whoeevee/EeveeSpotify#255]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

Would it be possible to hide the premium tab on the left of the screen that shows that you dont have Spotify Premium?
Its a cosmetic feature rather than a real bug but I think its worth saying.

iPad: iPad Air 5th Gen
iOS: iPad-iOS 18.0

![Screenshot1](https://github.com/user-attachments/assets/0e97baa3-fe94-40ce-88ba-3d9e43b56006)
![Screenshot2](https://github.com/user-attachments/assets/eb0df327-3ebb-4c1e-9d4f-14a7f5d3e3e6)

**Comment by asdfzxcvbn** [comment]
does enabling overwrite configuration help

**Comment by wlxxd** [comment]
> does enabling overwrite configuration help

Sorry, i forgot to mention.
-> At the time I did the screenshot, the dynamic method and the **overwrite config was enabled**.

**Comment by asdfzxcvbn** [comment]
and you're using the latest version?

**Comment by wlxxd** [comment]
> and you're using the latest version?

**Yes**, I downloaded it from the appdb site, the **version is: 4.4**.

**Comment by asdfzxcvbn** [comment]
well then we dont know, i cant reproduce this anyway

**Comment by Cosmic1212** [comment]
provide the link for the appdb

**Comment by wlxxd** [comment]
> provide the link for the appdb

https://appdb.to/details/cc6f21f2fffe7495099649d4bfb58d85b0969d10

**Comment by Cosmic1212** [comment]
try using the debug .ipa file

**Comment by yodaluca23** [comment]
This happened to me once, clicking the clear data button in EeveeSpotify settings worked...
