### ISSUE TITLE
Question about the apple watch app

### ISSUE THREAD

**Issue by Nasstyle771** [whoeevee/EeveeSpotify#262]
Hi! Just a small question. Do you guys ever plan on getting the app on the apple watch like the one on the app store? That would be cool 

Thanks, 
Nasstyle

**Comment by yodaluca23** [comment]
That would require decrypting the watchOS app, which would require a watchOS jailbreak which the only one that's ever exist was very limited did not allow for any apps from the App Store to be installed and only allowed for SSH access...

**Comment by Nasstyle771** [comment]
Ohh thats a bummer. Well thank you  for answering
