### ISSUE TITLE
[Feature Request] Romanized lyrics for songs partially in supported languages.

### ISSUE THREAD

**Issue by yodaluca23** [whoeevee/EeveeSpotify#263]
The latest commits added local translations for Romanized lyrics. It works great when using sources that don't support Romanized lyrics natively, like lrclib. But it doesn't work for songs that are only partially in a supported Romanized language... Such as many BLACKPINK songs. I think this would be very nice to have.

**Unrealated:**
Is there a reason PetitLyrics is geo-locked? I understand that it mostly has Japanese songs, but I don't see any reason to force it to be geo-locked.
Also, new Spotify version came out 8.9.58, will their be EeveeSpotify update for this version or no?

**Comment by asdfzxcvbn** [comment]
should be fixed with above commit

anyway petitlyrics is geolocked as there are better alternatives if you're not in japan, like genius, so no one really needs it other than japanese users
