### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by JackPlaysGames0510** [whoeevee/EeveeSpotify#266]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

When I use local file music the lyrics come up grey (unless i change the colour using Static colour) is their a way to fix that or not

**Comment by asdfzxcvbn** [comment]
known issue, no fix
