### ISSUE TITLE
[FEATURE REQUEST] Downloading songs via YouTube

### ISSUE THREAD

**Issue by nothonxhina** [whoeevee/EeveeSpotify#267]
Instead of the download button having to download the songs straight from the Spotify servers, it should instead send a search request on YouTube like "<song name> Official Audio", then it selects and downloads the audio from the first video the search results gave. Something similar in the downloading feature in [SoundBound](https://soundbound.app/), where they fetch the music through searching videos through YouTube and downloads the audio and stores it in a local folder.

**Comment by asdfzxcvbn** [comment]
no
