### ISSUE TITLE
[Feature Request] Live lyrics LiveActivity

### ISSUE THREAD

**Issue by yodaluca23** [whoeevee/EeveeSpotify#269]
This would probably be a lot of work, but, it would be really cool if we could see the live time synced lyrics on the lock screen with a live activity similar to this Reddit post:

https://www.reddit.com/r/iOSProgramming/s/AIqrGu1TYn

Obviously, free developer accounts do not have the necessary entitlements, so this would only be available for paid developer accounts, Jailbroken Devices, and TrollStore.

I believe it would also require modifying the apps .plist (I don't know if that's possible with a tweak...), to allow for the ActivityKit entitlement...

**Comment by asdfzxcvbn** [comment]
would you make a PR for this?

**Comment by yodaluca23** [comment]
> would you make a PR for this?

Ehhh, I can try... idk if I'll get anywhere...

I was able to make lyrics repository's, because the code was already there and multiple examples for outlines, to be completely honest, I'm not that good with swift...

**Comment by asdfzxcvbn** [comment]
well, please remember eeveespotify does not take huge feature requests, you can open a PR if you succeed in doing this

**Comment by yodaluca23** [comment]
I just remembered that LiveActivies is only in 16.0< my jailbroken device is on iOS 15, so It will be extremely difficult for me to inject it into a .ipa every time, send it over to my main device, and sideload it... I may look into this more whenever I buy a 16.1-16.5.1 device, until then, I guess this will be here if anyone else wants to take a shot at this...

**Comment by samuelawachie** [comment]
If you can make it so that when one is viewing lyrics in the app, the screen does not turn off. It's tedious having to tap the screen every few seconds (depending on timeout settings set for device) when lyrics are being viewed. This could also be done for those with full entitlements.

**Comment by yodaluca23** [comment]
> If you can make it so that when one is viewing lyrics in the app, the screen does not turn off. It's tedious having to tap the screen every few seconds (depending on timeout settings set for device) when lyrics are being viewed. This could also be done for those with full entitlements.

For one, this has nothing to do with this issue, two, Spotify already disables idle timeout if the lyrics are full screened...

**Comment by samuelawachie** [comment]
> For one, this has nothing to do with this issue, two, Spotify already disables idle timeout if the lyrics are full screened...
>
You need to ease off on the tone my dear. I'm not a developer to know of the disabled timeout by Spotify (now that I do, I understand). And I thought this was close enough to the topic of discussion here, so I didn't want to start another thread. I'm not fighting, or saying this is about the issue being discussed in this thread...
