### ISSUE TITLE
[Bug] Video ad appearing sometimes on home page

### ISSUE THREAD

**Issue by sickleox2** [whoeevee/EeveeSpotify#270]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

is it possible to remove it? Screenshot form EeveeSpotify 4.3

![Screenshot](https://github.com/user-attachments/assets/f7ac8728-0bbb-4ceb-8d25-c6a8a4500aa7)

**Comment by asdfzxcvbn** [comment]
no

**Comment by srinivasb99** [comment]
> ### Is this issue appropriate?
> 
> - [X] I have read the document in its entirety
> 
> ### Is this issue unique to EeveeSpotify?
> 
> - [X] I was unable to reproduce my issue using the stock Spotify app
> 
> ### Have you searched the existing issues?
> 
> - [X] This is a unique issue
> 
> ### Describe the bug.
> 
> is it possible to remove it? Screenshot form EeveeSpotify 4.3
> 
> 
> 
> ![Screenshot](https://github.com/user-attachments/assets/f7ac8728-0bbb-4ceb-8d25-c6a8a4500aa7)
> 
> 

Update to 4.5
