### ISSUE TITLE
[FEATURE REQUEST] Add spotify ai dj 

### ISSUE THREAD

**Issue by RishiSuthar** [whoeevee/EeveeSpotify#271]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

would it be possible to integrate the spotify ai dj in the next update ?

**Comment by yodaluca23** [comment]
Duplicate https://github.com/whoeevee/EeveeSpotify/issues/233 literally of your own issue...

+ Server Sided

+ Quick Google search tells you it's server sided...

**Comment by RishiSuthar** [comment]
i didn't see the reason on the previous one, thats why i made a new one.
