### ISSUE TITLE
[Bug] Widgets not showing while playing

### ISSUE THREAD

**Issue by Izuru15** [whoeevee/EeveeSpotify#273]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

![2024-07-23 ](https://github.com/user-attachments/assets/ae474028-379c-400e-bd19-fdbe45c7cae3)

Widgets not showing now playing song. I'm using sidestore currently.

**Comment by Izuru15** [comment]
> TrollStore only lol

What do u mean it only works on trollStore?

**Comment by samuelawachie** [comment]
I'm on TrollStore, and that's how it shows on mine too. Just all black.
