### ISSUE TITLE
CarPlay support?

### ISSUE THREAD

**Issue by Dievale** [whoeevee/EeveeSpotify#274]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

CarPlay integration? It is possible to add entitlements to the app so it can show up in CarPlay?
Please see link about entitlement
https://github.com/opa334/TrollStore/issues/158

**Comment by asdfzxcvbn** [comment]
you ticked "this is a unique issue" while there are already like at least 3 other issues about this.. please read.

**Comment by asdfzxcvbn** [comment]
by the way, the entitlements are not stripped in the ipas we release
