### ISSUE TITLE
[Bug] Inaccurate Japanese Romanization in LRCLIB

### ISSUE THREAD

**Issue by sakiaya** [whoeevee/EeveeSpotify#275]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

Japanese romanized lyrics while using LRCLIB as the lyric provider are incorrect. Seems to be a mixture of pinyin (mandarin chinese) and Japanese. Not sure if this is fixable as it may break other accurate romanization for other languages. Occurs on every Japanese song on my playlist that doesn't fall back to Genius. Unable to test with Petitlyrics since the option does not show up in my app (v4.5).

Example song: Yorushika - ただ君に晴れ
Japanese region Spotify account
![IMG_0625](https://github.com/user-attachments/assets/9193413a-248a-4e45-a79e-cbce6c2063bb)
Incorrect romanization from LRCLIB
![IMG_0626](https://github.com/user-attachments/assets/75b91541-cb96-41a3-8c46-f6f2726a5843)
Correct Lyrics from Genius
![IMG_0628](https://github.com/user-attachments/assets/ba7c8bba-d0a8-4590-8159-737909ce4a03)

**Comment by asdfzxcvbn** [comment]
this is an issue with `Foundation`'s `TransformToLatin`, you should just use another lyrics provider
