### ISSUE TITLE
[Bug] APP8.9.8 Japan user can‘t play the music unless he has a premium

### ISSUE THREAD

**Issue by AmberRighd** [whoeevee/EeveeSpotify#276]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [ ] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

I am a user in Japan, and there is a problem that I can't play music. Spotify prompts me that I need a premium. I found the same problem as me in the issue, but he solved the problem by switching between English and Japanese, but I couldn't solve it. I hope the developer can solve the problem.

**Comment by asdfzxcvbn** [comment]
https://github.com/whoeevee/EeveeSpotify/blob/swift/common_issues.md#unable-to-play-songs

**Comment by AmberRighd** [comment]
> https://github.com/whoeevee/EeveeSpotify/blob/swift/common_issues.md#unable-to-play-songs

oh That's what I do. This is the restriction of not being able to listen to music abroad for 15 days. I thought eevee lifted this (sad

**Comment by asdfzxcvbn** [comment]
sorry
