### ISSUE TITLE
[Bug] Playing music shuffles and plays a different song

### ISSUE THREAD

**Issue by HyptexPvP** [whoeevee/EeveeSpotify#277]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

When trying to play a song on a playlist of some sort, it will shuffle and play a different song from the playlist and give a pop up saying "Songs play in a random order"

**Comment by HyptexPvP** [comment]
![image](https://github.com/user-attachments/assets/930bc497-92ed-4ed9-b1a1-ec28738178e9)

A work around ive found was adding the song you wanna play to the queue or just searching up the song itself although itll still give me that pop up.

**Comment by asdfzxcvbn** [comment]
https://github.com/whoeevee/EeveeSpotify/blob/swift/common_issues.md#unable-to-play-songs

**Comment by HyptexPvP** [comment]
> https://github.com/whoeevee/EeveeSpotify/blob/swift/common_issues.md#unable-to-play-songs

That worked, didn't expect it to be that.
Thank you!

**Comment by soggyramennoodle** [comment]
Wait, I just got the same issue, and I've tried enabling smart shuffle, but it's still not fixing the issue...
