### ISSUE TITLE
[Feature Request] Stream Local Files / Local Playlists To Bluetooth Devices Like Alexa

### ISSUE THREAD

**Issue by TheNightRider12** [whoeevee/EeveeSpotify#279]
Would it be possible to make Spotify to be able to play Local music / Local Playlists over an Alexa or similar device? I have local songs that I have imported, however I am not able to get my Alexa device to play them. It can only stream songs that are from Spotify and only Spotify, not local.

**Comment by krono244** [comment]
I am also trying to play music on my Alexa device within the local network, but in this case, like non-premium members, I can’t play the music I want and there are limits on the number of skips, which is frustrating. While playback via Bluetooth works fine, it’s tough not being able to use it for playback over the local network via Wi-Fi.

**Comment by asdfzxcvbn** [comment]
idk lol just use bluetooth

**Comment by krono244** [comment]
I don’t see what’s interesting about it, and I don’t think there’s any reason to be mocked. Also, Bluetooth doesn’t support multi-room playback.

**Comment by asdfzxcvbn** [comment]
> I don’t see what’s interesting about it, and I don’t think there’s any reason to be mocked. Also, Bluetooth doesn’t support multi-room playback.

too bad then, we won't fix this, of course you can open a PR to be reviewed if **you** fix it 😉
