### ISSUE TITLE
Lyrics 

### ISSUE THREAD

**Issue by Zabooby** [whoeevee/EeveeSpotify#28]
Firstly, thank you for all the effort you put into this tweak, the updated ui looks great.

For me lyrics are hit or miss, they usually work for newly released songs only, this is true for other tweaks too. I vaguely remember a while ago Spotify changed how they handle lyrics, which broke the feature for a lot of tweaks. 

Are lyrics server-side or is there a workaround to make them work consistently? 

Also, this is quickly gaining attention, in the event that Spotify tries to shut it down do you have any backups in place?

**Comment by asdfzxcvbn** [comment]
> Are lyrics server-side or is there a workaround to make them work consistently?

we don't know, this issue does seem to affect everyone though iirc

> Also, this is quickly gaining attention, in the event that Spotify tries to shut it down do you have any backups in place?

no.

**Comment by Zabooby** [comment]
> no.

You could upload to [appdb.to](https://appdb.to/) and GitHub alternatives like GitLab.

**Comment by asdfzxcvbn** [comment]
> You could upload to [appdb.to](https://appdb.to/) 

i already do. i upload the objc branch (zx's repo)

> and GitHub alternatives like GitLab. 

i thought you meant in the event spotify patched this. if the repo gets taken down then obviously it will still work, but theres nothing we can do to prevent this thing itself from being patched
