### ISSUE TITLE
[Bug] Version 4.4+ doesnt work in IOS 18 Beta 4

### ISSUE THREAD

**Issue by Roigo21** [whoeevee/EeveeSpotify#281]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

Basically, using any version prior to 4.4 in IOS 18 Beta 4 doesnt patch the data, so no premium on the spotify.
Things I tried:

- Changing Bundle ID of the app
- Using the default bundle ID
- Installing an older version (4.2 is working, the one im using right now)
- Trying to patch the data in an older version and going to the updated one
- Changing device language
- Log in and log out multiple times

**Comment by yodaluca23** [comment]
Did you try the override configuration option? Or reset data option?

**Comment by Roigo21** [comment]
> Did you try the override configuration option? Or reset data option?

how can i do that?

**Comment by yodaluca23** [comment]
> how can i do that?

Spotify App > Profile Pic in top left > Settings and privacy > EeveeSpotify > Reset Data
If that doesn't work then
Spotify App > Profile Pic in top left > Settings and privacy > EeveeSpotify > Patching Overwrite configuration then do the above steps to reset again after turning it on.

**Comment by Roigo21** [comment]
> > how can i do that?
> 
> Spotify App > Profile Pic in top left > Settings and privacy > EeveeSpotify > Reset Data If that doesn't work then Spotify App > Profile Pic in top left > Settings and privacy > EeveeSpotify > Patching Overwrite configuration then do the above steps to reset again after turning it on.

Yea i did that, forgot the name of the options

**Comment by asdfzxcvbn** [comment]
did you also try [this](https://github.com/whoeevee/EeveeSpotify/blob/swift/common_issues.md#if-all-tracks-are-skipped-a-song-stops-as-soon-as-you-play-it-songs-play-in-a-random-order-you-see-the-you-discovered-a-premium-feature-popup-when-trying-to-play-a-song-or-encounter-other-restrictions)?

**Comment by Roigo21** [comment]
With this you mean using a vpn and changing my account region?

zx ***@***.***> escreveu em dom., 28/07/2024 às 02:11 :

**Comment by asdfzxcvbn** [comment]
exactly

**Comment by srinivasb99** [comment]
> ### Is this issue appropriate?
> 
> - [X] I have read the document in its entirety
> 
> ### Is this issue unique to EeveeSpotify?
> 
> - [X] I was unable to reproduce my issue using the stock Spotify app
> 
> ### Have you searched the existing issues?
> 
> - [X] This is a unique issue
> 
> ### Describe the bug.
> 
> Basically, using any version prior to 4.4 in IOS 18 Beta 4 doesnt patch the data, so no premium on the spotify.
> 
> Things I tried:
> 
> 
> 
> - Changing Bundle ID of the app
> 
> - Using the default bundle ID
> 
> - Installing an older version (4.2 is working, the one im using right now)
> 
> - Trying to patch the data in an older version and going to the updated one
> 
> - Changing device language
> 
> - Log in and log out multiple times

Im using beta 4 as well and 4.5 works fine lol its something to do with your region prolly

**Comment by Roigo21** [comment]
> > ### Is this issue appropriate?
> > 
> > * [x]  I have read the document in its entirety
> > 
> > ### Is this issue unique to EeveeSpotify?
> > 
> > * [x]  I was unable to reproduce my issue using the stock Spotify app
> > 
> > ### Have you searched the existing issues?
> > 
> > * [x]  This is a unique issue
> > 
> > ### Describe the bug.
> > Basically, using any version prior to 4.4 in IOS 18 Beta 4 doesnt patch the data, so no premium on the spotify.
> > Things I tried:
> > 
> > * Changing Bundle ID of the app
> > * Using the default bundle ID
> > * Installing an older version (4.2 is working, the one im using right now)
> > * Trying to patch the data in an older version and going to the updated one
> > * Changing device language
> > * Log in and log out multiple times
> 
> Im using beta 4 as well and 4.5 works fine lol its something to do with your region prolly

Well, i dont know then. It used to work just fine.

**Comment by Roigo21** [comment]
Using version 4.2 seems fine for now
