### ISSUE TITLE
how can i install/update it?

### ISSUE THREAD

**Issue by callmissin** [whoeevee/EeveeSpotify#282]
i currently have the 4.3 version of the spotify tweak you made but it says update available which is the 4.5 you recently made, and i just want to know how can i install/update it??

**Comment by callmissin** [comment]
by the way im kind of new to like all of this so i would greatly appreciate the help on how to.

**Comment by asdfzxcvbn** [comment]
just install it like how you originally installed it

**Comment by callmissin** [comment]
yeah the thing is i installed it through eonhub, if u dont know what it is its basically a app where you can install jailbroken apps, hacked games, hacked apps, etc u get the point soo i dont really know how originally install it @asdfzxcvbn

**Comment by asdfzxcvbn** [comment]
> yeah the thing is i installed it through eonhub, if u dont know what it is its basically a app where you can install jailbroken apps, hacked games, hacked apps, etc u get the point soo i dont really know how originally install it @asdfzxcvbn 

then wait for them to update it or look for the various sideloading guides on r/sideloaded or something

**Comment by srinivasb99** [comment]
> > yeah the thing is i installed it through eonhub, if u dont know what it is its basically a app where you can install jailbroken apps, hacked games, hacked apps, etc u get the point soo i dont really know how originally install it @asdfzxcvbn 
> 
> then wait for them to update it or look for the various sideloading guides on r/sideloaded or something

Use a dns + ESign so you get no revoke

**Comment by srinivasb99** [comment]
> > > > yeah the thing is i installed it through eonhub, if u dont know what it is its basically a app where you can install jailbroken apps, hacked games, hacked apps, etc u get the point soo i dont really know how originally install it @asdfzxcvbn 
> > > 
> > > then wait for them to update it or look for the various sideloading guides on r/sideloaded or something
> > 
> > Use a dns + ESign so you get no revoke
> 
> ![image](https://github.com/user-attachments/assets/e83060d3-9f6c-4dfc-bc6d-58cd9cd4a81a)
> 
> ![image](https://github.com/user-attachments/assets/68c5f806-ba19-4083-aa71-3c89e100e42e)
> 
> yeah i already do have it active it just wont let me idk 🤷‍♂️

https://drive.google.com/file/d/1I2SMPM5m70Q5l5fB8PQHzwt-mUDZVxZw/view?usp=drivesdk

https://drive.google.com/file/d/1z27jSZi2n1nDRzqEKLWDYNoY9L-VvSbQ/view?usp=drivesdk

**Comment by callmissin** [comment]
> > > > > yeah the thing is i installed it through eonhub, if u dont know what it is its basically a app where you can install jailbroken apps, hacked games, hacked apps, etc u get the point soo i dont really know how originally install it @asdfzxcvbn 
> > > > 
> > > > then wait for them to update it or look for the various sideloading guides on r/sideloaded or something
> > > 
> > > Use a dns + ESign so you get no revoke
> > 
> > ![image](https://github.com/user-attachments/assets/e83060d3-9f6c-4dfc-bc6d-58cd9cd4a81a)
> > 
> > ![image](https://github.com/user-attachments/assets/68c5f806-ba19-4083-aa71-3c89e100e42e)
> > 
> > yeah i already do have it active it just wont let me idk 🤷‍♂️
> 
> https://drive.google.com/file/d/1I2SMPM5m70Q5l5fB8PQHzwt-mUDZVxZw/view?usp=drivesdk
> 
> https://drive.google.com/file/d/1z27jSZi2n1nDRzqEKLWDYNoY9L-VvSbQ/view?usp=drivesdk

what i do with those?😭
