### ISSUE TITLE
Can’t open Spotify App

### ISSUE THREAD

**Issue by Saifullahkhan31** [whoeevee/EeveeSpotify#283]
Hey, after using the app for couple of days now when i click to open it, it says “unable to verify” and goes on about it needs to verify the trust of the developer with an internet connection. Can anyone guide me what that means? Like do i have to so something to make it work? As it was working all good when I initially downloaded. And yes i deleted and installed again but it didn’t work.

**Comment by yodaluca23** [comment]
This is nothing to do with the app. This has to do with whatever sideloadeding method you're using. If you're using a leaked enterprise certificate then it probably got revoked. Search the r/sideloaded subreddit for information..

**Comment by Saifullahkhan31** [comment]
Yes, I figured that it had nothing to do with the app but an error on my end. Also, I have been looking in the subreddit and have gotten the answer. Thanks for the help, much appreciated.
