### ISSUE TITLE
[Bug] Hindi or Urdu Romaji Lyrics

### ISSUE THREAD

**Issue by annamaranthine** [whoeevee/EeveeSpotify#286]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

Just like you can choose to view Korean, Chinese, and Japanese Romaji, could I display Hindi or Urdu?

**Comment by asdfzxcvbn** [comment]
if someone opens a PR sure
