### ISSUE TITLE
[Bug] New versions not installing in iOS 17.6

### ISSUE THREAD

**Issue by DhanushSantosh** [whoeevee/EeveeSpotify#287]
I've had this issue since iOS 17.5.1, it only installs Spotify of version 8.9.42-40. I've tried updating and reinstalling but it didn't fix the issue. I hope this gets fixed soon by someone.

**Comment by asdfzxcvbn** [comment]
it literally works for everyone else can you please explain more in detail and send screenshots or something

**Comment by DhanushSantosh** [comment]
Okay, I don't know what the bug was but after multiple tries I've installed the latest version unlike before where I try to update (shows old version) or reinstall the app just wouldn't install. Anyways, thanks for the support 👍🏻
