### ISSUE TITLE
[Bug] Premium Patching not working 

### ISSUE THREAD

**Issue by Zxck092** [whoeevee/EeveeSpotify#290]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

I downloaded the latest version of eevee 4.6-8.9.60 and the Premium patch does not work I tired static and dynamic with overwrite configuration and resting data and have yet to make it work. Switching app language did not work either

**Comment by sergio-nadal** [comment]
Hi

I have the same problem and some information to share. Today my friend installed the ipa with altstore and it works without problems. He has an iPhone 15 Pro Max with iOS 17.5.1. I have an iPhone 12 Pro Max with iOS 17.6.

Is it possible that it is due to the iOS version?

Thanks!

**Comment by asdfzxcvbn** [comment]
probably not iOS version

tbh we dont know what the issue is lol it works fine for us

**Comment by sergio-nadal** [comment]
F*ck XD. Well, I'll keep trying. I'm even able to restore iOS cleanly.

Thanks for the work :)
