### ISSUE TITLE
Problem with ALEXA

### ISSUE THREAD

**Issue by francesco3208** [whoeevee/EeveeSpotify#292]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

If I connect to Alexa, the song I'm listening to from the iPhone continues correctly with Alexa. But the moment I click on any new song, it happens to bug and play me a random song.

**Comment by francesco3208** [comment]
ps thanks for the work 🙌

**Comment by asdfzxcvbn** [comment]
spotify connect is unavailable, use bluetooth

**Comment by francesco3208** [comment]
with spotilife I remember that it worked correctly

**Comment by asdfzxcvbn** [comment]
![idk](https://github.com/user-attachments/assets/1753c7bf-b59e-470d-afe1-75669eaa9123)
