### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by elnarovexx** [whoeevee/EeveeSpotify#294]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

Not showing lyrics
![IMG_6412](https://github.com/user-attachments/assets/ff7caf6c-62f6-42be-b632-8943ef5c02e1)

**Comment by elnarovexx** [comment]
In every song

**Comment by elnarovexx** [comment]
![IMG_6417](https://github.com/user-attachments/assets/21172841-7a58-46e6-a019-c10ac984af16)
Didnt work

**Comment by elnarovexx** [comment]
But i have spotify premium and when i listen there then it works

**Comment by ElliotCHEN37** [comment]
which source are you using now? If Musixmatch, check if you entered the correct user token, or using US VPN

**Comment by asdfzxcvbn** [comment]
skill issue lol
