### ISSUE TITLE
Help 

### ISSUE THREAD

**Issue by Aousad** [whoeevee/EeveeSpotify#295]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

After using eevespotify ipa.. for 4 days this happens in latest ipa mods 
![IMG_7280](https://github.com/user-attachments/assets/2dd13418-e592-40de-a9b4-e8458c36e51d)

**Comment by yodaluca23** [comment]
Are you using dynamic patching? Did you try reset data option? Or the override configuration option? Did you try changing your language to something else then back?

**Comment by asdfzxcvbn** [comment]
change region, read common issues
