### ISSUE TITLE
[Bug] Lyrics never appear

### ISSUE THREAD

**Issue by Myst2312** [whoeevee/EeveeSpotify#296]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

The lyrics never appear at all for me. Even after multiple restarts/re-install it is still the same.

**Comment by Myst2312** [comment]
![image_2024-08-06_224838763](https://github.com/user-attachments/assets/baef96c6-d5b8-477b-857e-119f91130ed6)

After restart
![image_2024-08-06_224853494](https://github.com/user-attachments/assets/f82544ca-2499-4ab7-b7cf-3a57ad09f15c)

**Comment by ElliotCHEN37** [comment]
which source are you using now? If Musixmatch, check if you entered the correct user token, or using US VPN

**Comment by Myst2312** [comment]
I tried using Musixmatch with usertoken and it doesn't work and I'm not using a VPN that can select the US rn

**Comment by asdfzxcvbn** [comment]
test latest deb from github actions

**Comment by younyokel** [comment]
Same, used to work before. All I did was refresh the app

**Comment by younyokel** [comment]
I just fixed it by turning on and off Display Original Colors in Customanisation options. Now it shows properly

**Comment by whoeevee** [comment]
should be fixed in 4.7
