### ISSUE TITLE
Unable to find local files folder[Bug] 

### ISSUE THREAD

**Issue by ToothEh** [whoeevee/EeveeSpotify#297]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

I was having trouble updating the app using scarlet. I update and even download the ipa but it just “downloads” the app just to be on the same version i was prior. The only way to update would be to delete the app entirely and redownload the ipa. Afraid of losing my local files, i went to the files app to check and it seems that after the failed updated prior, the local files folder is gone. Although i can’t find the local files folder (which had been there before i tried updating) the local files appears inside the app and still plays audio, so they must be somewhere? Disable and re-enabling local files doesn’t change anything and the local files songs are still playable but the folder is no longer available.

**Comment by asdfzxcvbn** [comment]
try using esign and enable the "documents support' option or whatever, we will fix this in future ipas
