### ISSUE TITLE
[Bug] Spotify Is No Longer Available After a Few Days

### ISSUE THREAD

**Issue by sophacuna** [whoeevee/EeveeSpotify#299]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

I'm not sure if this is a bug or normal, but I haven't found anything on this. a few days after I update/refresh spotify using sideloadly, I will randomly get a notification on my phone saying something to the effect of "spotify is no longer available" and when I try to open the app, I just get an error message. this goes away when I refresh it again with sideloadly, but comes back a few days later. it's not just me having this issue, my partner is having the same thing as well. thank you!

**Comment by asdfzxcvbn** [comment]
this is unrelated to eeveespotify, look into buying a cert as this issue is a limitation with your sideloading method

**Comment by srinivasb99** [comment]
Use ESign + DNS profile
