### ISSUE TITLE
Installed with Trollstore 2.0.15 Issue

### ISSUE THREAD

**Issue by Kirzuo** [whoeevee/EeveeSpotify#30]
Installing with Trollstore wont activate premium. Versions 1.1 and 1.0 doesn’t show premium tab at the bottom but it still acts like the account is using free version. Tried having new account with these versions also, same outcome. 1.2 and 1.3 just acts like i’m using free version. The popup does workin all versions but no premium. The only way i’ve gotten it to work is using a different sideloading method like altstore or a appdb to install it with their/my certificate.

**Comment by JackPlaysGames0510** [comment]
Install the latest version it will fix that problem

**Comment by JackPlaysGames0510** [comment]
Delete and reinstall

**Comment by Kirzuo** [comment]
Trollstore or Spotify? I dont think i can reinstall it as i did delayota. Already tried with spotify.

**Comment by JackPlaysGames0510** [comment]
Spotify deleting it and reinstalling it fixed it for me when I had this problem

**Comment by TheDoctor200** [comment]
For trollstore install, install the ipa first as normally, then go into trollstore long press on spotify and tap switch user registration. This fixed it for me, if you want to make it launchable even after a reboot or restart, just restart go in trollstore long press on spotify and tap switch to ...
After that restart again

**Comment by asdfzxcvbn** [comment]
please try the above fix @Kirzuo

**Comment by Kirzuo** [comment]
Nope, didnt work either. Tried installing official app and installing the ipa over it. Tried the reverse of that and did user registration in combination too, all didnt work. Slightly frustrating that sideloading with altstore and others work fine.

**Comment by asdfzxcvbn** [comment]
as mentioned in another issue, installation method really should not affect anything, you are free to read the source code which will just prove that

ps it works for me on trollstore, so idk what the exact issue is here

**Comment by Kirzuo** [comment]
Well, i dont understand why it just doesnt work with trollstore for me… The issue is installing with trollstore doesnt enable premium…. Everything else works BESIDES premium being enabled, dude. Regardless, I dont even know what i’m looking at in source code if i was trying to find an issue or even compare lol.. Anyway, If other people have an issue with trollstore not working i’m using IPhone 13 Pro IOS 17 and downgraded from IOS 17.1 using Delay OTA with trollstore 2.
