### ISSUE TITLE
[FEATURE REQUEST] - Choosing devices to play music on

### ISSUE THREAD

**Issue by 1vvyyy** [whoeevee/EeveeSpotify#301]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

For example, whenever i connect to a Amazon alexa, the premium features are no longer in place.

Is it possible to implement this so it works when connecting to other devices that's not with bluetooth?

**Comment by srinivasb99** [comment]
> ### Is this issue appropriate?
> 
> - [X] I have read the document in its entirety
> 
> ### Is this issue unique to EeveeSpotify?
> 
> - [X] I was unable to reproduce my issue using the stock Spotify app
> 
> ### Have you searched the existing issues?
> 
> - [X] This is a unique issue
> 
> ### Describe the bug.
> 
> For example, whenever i connect to a Amazon alexa, the premium features are no longer in place.
> 
> 
> 
> Is it possible to implement this so it works when connecting to other devices that's not with bluetooth?

Probably not possible because it's a separate device but idk

**Comment by yodaluca23** [comment]
No, This is because when using Alexa cast, or anything similar it tells that device to play it through the Spotify API, and turns your phone or whatever into a simple remote. Meaning it is not possible to spoof the premium status, please use bluetooth, this is not possible to fix.

**Comment by Diowboss** [comment]
The app on the Alexa is a completely different app then on your phone.
