### ISSUE TITLE
[Bug] Romanization Inaccurate

### ISSUE THREAD

**Issue by alany08** [whoeevee/EeveeSpotify#302]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

![IMG_6998](https://github.com/user-attachments/assets/b3fc8555-597c-4fa6-96e3-0f97ca973e56)

Romanization disagrees with what is seen in musixmatch, often being incorrect/wrong. From sniffing the requests, it seems like eeveespotify only requests for lyrics in the `en` locale, and I wasn’t able to find how the romanized lyrics were acquired.

Replaying your formatted API request, but changing `en` to `rj` (ja -> rj for romanized) doesn’t work either. Here is a comparison of the api request URLs between yours and musixmatch’s native app

https://apic.musixmatch.com/ws/1.1/macro.subtitles.get?track_spotify_id=6MCjmGYlw6mQVWRFVgBRvB&selected_language=en&subtitle_format=mxm&part=subtitle_translated&app_id=mac-ios-v2.0&q_track=%20&usertoken=TOKEN_REDACTED

https://apic.musixmatch.com/ws/1.1/macro.subtitles.get?app_id=mac-ios-v2.0&usertoken=TOKEN_REDACTED&q_duration=259&f_tracking_url=html&page_size=1&track_spotify_id=6MCjmGYlw6mQVWRFVgBRvB&itunes_storefront_id=&questions_id_list=track_esync_action,track_sync_action,track_translation_action,lyrics_ai_mood_analysis_v3&tags=playing&richsync_force_ai_autosync=0&f_subtitle_length_max_deviation=1&part=track_lyrics_translation_status,lyrics_crowd,user,subtitle_translated,lyrics_translated,attribution,itunes_commontrack_ids,lyrics_verified_by,labels,track_structure,artist,track_performer_tagging&track_fields_set=ios_track_list&q_artist=YOASOBI&optional_calls=crowd.track.actions,track.richsync&language_iso_code=1&q_artists=&f_subtitle_length=259&track_id=206453347&format=json&q_track=%E5%A4%9C%E3%81%AB%E9%A7%86%E3%81%91%E3%82%8B&commontrack_id=105014636&richsync_compact_type=words&lyrics_id=35544342&subtitle_format=dfxp&q_album=THE%20BOOK&selected_language=rj&q_album_artist=&user_language=en_US&signature=ilxnMfdQ+adl7b//qtS+8lIT+Dw=&signature_protocol=sha1

Sorry, this is about as much information as I can provide (currently only have access to mobile)

**Comment by alany08** [comment]
Setting my lyrics language to rj is much better, but then I am not able to view english translations.

**Comment by asdfzxcvbn** [comment]
that’s local romanization, you can disable translation by entering nothing

**Comment by alany08** [comment]
I want english translations, which work if I enter `en` into the musixmatch language. However if I do that, and enable romanization, the romanization disagrees with musixmatch’s romanization which is more accurate. What do you mean by local romanization? The screenshot is with language set to `en`, and with romanization on.

**Comment by whoeevee** [comment]
in 4.7 release, musixmatch romanization and translation now work simultaneously

**Comment by alany08** [comment]
Same issue still occurring. The romanization is only correct in some sections of songs, but it significantly differs from the romanization provided within the musixmatch app

**Comment by alany08** [comment]
TYSM! I love developers who are really responsive, I’m thinking of contributing to this, as soon as i pick up enough swift
