### ISSUE TITLE
next update eta...?

### ISSUE THREAD

**Issue by srinivasb99** [whoeevee/EeveeSpotify#303]
Just wondering when the next update coming

**Comment by whoeevee** [comment]
eta today

**Comment by Infinitay** [comment]
> eta today

Thanks for your work. I was wondering if it would be possible to automate IPA build releases with GitHub actions so that we could get the latest commit build when they happen?

**Comment by yslthug** [comment]
Hi, I'm a beginner on github and can't sort out where I can find what I need. Can someone please send me direct link to download eevee ipa(I use sideloadly)? Thanks

**Comment by TeaselUwU** [comment]
> Hi, I'm a beginner on github and can't sort out where I can find what I need. Can someone please send me direct link to download eevee ipa(I use sideloadly)? Thanks

It’s here :)
https://github.com/whoeevee/EeveeSpotify/releases/tag/swift4.6

**Comment by yslthug** [comment]
> > Hi, I'm a beginner on github and can't sort out where I can find what I need. Can someone please send me direct link to download eevee ipa(I use sideloadly)? Thanks
> 
> It’s here :) https://github.com/whoeevee/EeveeSpotify/releases/tag/swift4.6

Thank you very much! <3

**Comment by asdfzxcvbn** [comment]
> > eta today
> 
> Thanks for your work. I was wondering if it would be possible to automate IPA build releases with GitHub actions so that we could get the latest commit build when they happen?

no, you can easily make your own ipas with something like pyzule (which is how the official IPAs are made)

if you choose to use pyzule, just pass both the swiftprotobuf and eeveespotify deb to `-f`, and it will handle everything else for you

for other injectors, make sure eeveespotify, swiftprotobuf, orion, and cydiasubstrate are included

we will also **not** accept a PR to make ipas through a workflow, as it's easy enough to make your own

**Comment by Infinitay** [comment]
> no, you can easily make your own ipas with something like pyzule (which is how the official IPAs are made)
> 
> if you choose to use pyzule, just pass both the swiftprotobuf and eeveespotify deb to `-f`, and it will handle everything else for you

Got it thank you for the indepth reply. I'm not familiar with pyzule so I'll look into it more. Thanks
