### ISSUE TITLE
[Bug] Unable to select songs when using Spotify Connect

### ISSUE THREAD

**Issue by suiminn** [whoeevee/EeveeSpotify#308]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

When using Spotify Connect, a different song is played than the selected song.

https://github.com/user-attachments/assets/4c9adef3-bf9a-4131-a570-c47b65c8f32f

**Comment by srinivasb99** [comment]
> ### Is this issue appropriate?
> 
> - [X] I have read the document in its entirety
> 
> ### Is this issue unique to EeveeSpotify?
> 
> - [X] I was unable to reproduce my issue using the stock Spotify app
> 
> ### Have you searched the existing issues?
> 
> - [X] This is a unique issue
> 
> ### Describe the bug.
> 
> When using Spotify Connect, a different song is played than the selected song.
> 
> 
> 
> https://github.com/user-attachments/assets/4c9adef3-bf9a-4131-a570-c47b65c8f32f

Yes this is because you have switched back to free version.
