### ISSUE TITLE
Unable to verify app

### ISSUE THREAD

**Issue by FireDemonic** [whoeevee/EeveeSpotify#31]
I have a stable internet connection and have checked under settings>general>VPN & Device Management to see if I could verify it there, but no luck.
IOS: 17.4.1
iPhone 14 Pro Max
Installed via appdb

**Comment by asdfzxcvbn** [comment]
can you send the exact error message? or preferably a screenshot?

**Comment by FireDemonic** [comment]
![image](https://github.com/whoeevee/EeveeSpotify/assets/168257046/9507dfa5-a759-46f5-9a67-166385ff649d)

**Comment by jinchunyou** [comment]
This is the problem with your signature certificate   Has absolutely nothing to do with this project.

**Comment by jinchunyou** [comment]
“sun shine”Is free to share the enterprise certificate is its problem

**Comment by FireDemonic** [comment]
Is there a way to reset or fix my signature certificate?
