### ISSUE TITLE
[Bug] The AirPod automatic ear detection doesnt work

### ISSUE THREAD

**Issue by nocoolingkit** [whoeevee/EeveeSpotify#310]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

The song should pause when i remove my airpod from my ear and resume if i put it in again and if i remove both at the same time it disconnects my airpods from iphone.
I Signed the app with Esign.

**Comment by whoeevee** [comment]
change the app and bundle identifiers to match your provisioning profile (https://github.com/whoeevee/EeveeSpotify/issues/32)

**Comment by Kr1m4eto** [comment]
how to do that exactly?
