### ISSUE TITLE
MAC version

### ISSUE THREAD

**Issue by Bigleeeo** [whoeevee/EeveeSpotify#311]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

When will the MAC version be released

**Comment by yodaluca23** [comment]
Use SpotX/Block The Spot + Spictify

**Comment by asdfzxcvbn** [comment]
No
