### ISSUE TITLE
Side/AltStore source not working

### ISSUE THREAD

**Issue by wyldcrd** [whoeevee/EeveeSpotify#314]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

After inputing the alt/sidestore [source](https://raw.githubusercontent.com/whoeevee/EeveeSpotify/swift/repo.altsource.json) in the sources page sidestore throws: `The data couldn't be read because it isn't in the correct format.
E downloadURL:String or downloadURLs: [[Platform:URL]] key required.`

AFAIK this is an issue with the source and not side/altstore. (yes I have checked the issues)

**Comment by asdfzxcvbn** [comment]
yeah, i believe i found the issue and i'll have to fix it in altSourceConverter

side note, i really really really fucking hate altstore and its shitty outdated docs which literally spreads misinformation, i shouldnt have to copy other sources to get this thing working, i really wish everybody just had trollstore or at least a cert :sob:

**Comment by asdfzxcvbn** [comment]
fixed
