### ISSUE TITLE
Unable to Verify App

### ISSUE THREAD

**Issue by randomperson21398** [whoeevee/EeveeSpotify#317]
I woke up this morning and I tried to open Spotify but it said "Unable to Verify App"
![5030824571560897617](https://github.com/user-attachments/assets/2236284f-000f-48c3-954f-0294ac128de6)

Is there any way to fix this? I used Appdb to download it. I tried downloading IPAs, deleting the app and downloading again but no luck. Also I'm a noob at this so pls be nice.

**Comment by asdfzxcvbn** [comment]
this is unrelated to eeveespotify, take a look at some of the numerous guides on places like r/sideloaded

**Comment by srinivasb99** [comment]
> I woke up this morning and I tried to open Spotify but it said "Unable to Verify App"
> 
> ![5030824571560897617](https://github.com/user-attachments/assets/2236284f-000f-48c3-954f-0294ac128de6)
> 
> 
> 
> Is there any way to fix this? I used Appdb to download it. I tried downloading IPAs, deleting the app and downloading again but no luck. Also I'm a noob at this so pls be nice.

Nah try using ESign + DNS profile google it
