### ISSUE TITLE
Opening from dynamic island doesn't work

### ISSUE THREAD

**Issue by officiallor** [whoeevee/EeveeSpotify#32]
While trying to open the app from dynamic island, it just magnifies, you can press the buttons but not open the app to look for other songs. 
From the official one it works as expected. Is there any fix?
Thanks

**Comment by asdfzxcvbn** [comment]
this is because the app & bundle id needs to match your cert. certain functionality requires this (like clicking on the song title on the lock screen)

you'll need a **development** cert, and [signtools](https://github.com/signtools/signtools) can easily do this process for you.

**Comment by officiallor** [comment]
I haven't changed anything at least manually. I just signed the app and that's all.  Everything looks not modified. It happens on yt too because it's sideloaded.

**Comment by asdfzxcvbn** [comment]
exactly. you **need** to modify it for it to work. take a look at using signtools like i suggested

**Comment by DimaSheiko** [comment]
> this is because the app & bundle id needs to match your cert. certain functionality requires this (like clicking on the song title on the lock screen)
> 
> you'll need a **development** cert, and [signtools](https://github.com/signtools/signtools) can easily do this process for you.

Can you give me a hint on how to make the match you are talking about? I have my certificate and I use ESign, but how do I know which bundle id I should place

**Comment by asdfzxcvbn** [comment]
> > this is because the app & bundle id needs to match your cert. certain functionality requires this (like clicking on the song title on the lock screen)
> 
> > 
> 
> > you'll need a **development** cert, and [signtools](https://github.com/signtools/signtools) can easily do this process for you.
> 
> 
> 
> Can you give me a hint on how to make the match you are talking about? I have my certificate and I use ESign, but how do I know which bundle id I should place

use signtools. only changing the bundle id wont work.

**Comment by surferbb** [comment]
Can anyone help with the signtools installation process? I tried following the [installation guide](https://github.com/SignTools/SignTools/blob/master/INSTALL.md) to setup signtools on my mac but I haven't been able to figure it out and I can't find any tutorials anywhere

**Comment by hongphuc95** [comment]
> Can anyone help with the signtools installation process? I tried following the [installation guide](https://github.com/SignTools/SignTools/blob/master/INSTALL.md) to setup signtools on my mac but I haven't been able to figure it out and I can't find any tutorials anywhere

Where do get stuck? I can help you navigate through the process

**Comment by officiallor** [comment]
@surferbb if you need help you can ping

**Comment by Evslol** [comment]
Does signtools still work?

**Comment by asdfzxcvbn** [comment]
yes

**Comment by wlxxd** [comment]
What needs to be changed in order to enable these features?

I’ve read bundle id and something in the app so far.

**Comment by J2TR1PPY** [comment]
> > Can anyone help with the signtools installation process? I tried following the [installation guide](https://github.com/SignTools/SignTools/blob/master/INSTALL.md) to setup signtools on my mac but I haven't been able to figure it out and I can't find any tutorials anywhere
> 
> 
> 
> Where do get stuck? I can help you navigate through the process

can you help me can i download it on windows?

**Comment by J2TR1PPY** [comment]
so do i need to use the apps original bundle id or my provision bundle id thing

**Comment by officiallor** [comment]
> can you help me can i download it on windows?

Setup the folders as explained in Custom provisioning profile section
![image](https://github.com/user-attachments/assets/6c261c37-765a-468c-a84f-96f714dbb963)
![image](https://github.com/user-attachments/assets/3042cd2a-ae00-4032-b4e2-eb88f45ad3a7)

https://github.com/SignTools/SignTools-CI setup github actions so you can put the key in to the generated signer-cfg.yml
download cloudflared and signtools.exe and place them as shown in the above pictures

runBoth.bat
`start /b cloudflared tunnel -url http://localhost:8080 -metrics localhost:8989 
start /b signtools -cloudflared-host localhost:8989
pause`

**Comment by TheAnubi** [comment]
is there any way you could sign other apps?
