### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by otrool** [whoeevee/EeveeSpotify#322]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

Unable to verify app?
![IMG_5285](https://github.com/user-attachments/assets/0984c856-408d-4b67-8623-404002318930)

**Comment by asdfzxcvbn** [comment]
unrelated to eeveespotify, duplicate issue
