### ISSUE TITLE
[FEATURE REQUEST] True Shuffle without Spotify's Ass Algorithm

### ISSUE THREAD

**Issue by BB4LIFE** [whoeevee/EeveeSpotify#324]
It would be awesome to be able to shuffle playlists (not just the queue) instead of relying on Spotify's algorithm which seems to only play the last few songs added to a playlist on repeat.

**Comment by asdfzxcvbn** [comment]
we will not implement this ourselves,

someone can open a PR for this if they wish to, though

**Comment by BB4LIFE** [comment]
Ok, thanks for the response.

**Comment by Richard-NDC** [comment]
you can inject sposify for true shuffer

**Comment by asdfzxcvbn** [comment]
> you can inject sposify for true shuffer

we aren't 100% sure if this works (the individual TrueShuffle tweak doesnt), give us some time to check

**Comment by asdfzxcvbn** [comment]
> you can inject sposify for true shuffer

i just inspected sposify behavior, it does not have working true shuffle

**Comment by yodaluca23** [comment]
> > you can inject sposify for true shuffer
> 
> 
> 
> i just inspected sposify behavior, it does not have working true shuffle

I don't believe it works on the modern versions...

**Comment by asdfzxcvbn** [comment]
> > > you can inject sposify for true shuffer
> > 
> > 
> > 
> > i just inspected sposify behavior, it does not have working true shuffle
> 
> I don't believe it works on the modern versions...

yeah thats what i meant
