### ISSUE TITLE
[Bug] Spotify doesn’t open in notification center

### ISSUE THREAD

**Issue by wlxxd** [whoeevee/EeveeSpotify#333]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

It’s not possible to open Spotify within the notification center (take a look at the video).

Version: 4.8
Installed with ESign and Anti Revoke DNS with Company Cert

https://github.com/user-attachments/assets/37cbd8fb-1cd4-4f2e-b8d0-832b95ee6949

**Comment by wlxxd** [comment]
> #32

So I need SignTools to use these features.
Do I need to refresh it in the 7 day period or can I use it with my cert and anti revoke dns?

Also, SignTools looks pretty hard to install.

**Comment by DimaSheiko** [comment]
> #32

Wouldn't eSign work the same as SignTools?

**Comment by wlxxd** [comment]
> > #32
> 
> Wouldn't eSign work the same as SignTools?

Apparently not, because the bundle id and other things need to be changed in order to access these features.

A way with ESign would be great though.
