### ISSUE TITLE
[Bug] Musixmatch source not working

### ISSUE THREAD

**Issue by ElliotCHEN37** [whoeevee/EeveeSpotify#336]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

Correct user token - Checked!
IP - Taiwan
Using the latest ver from GitHub
The lyric is available on Musixmatch, but the tweak cannot find it. 
![IMG_3562](https://github.com/user-attachments/assets/74898e2a-285c-4db7-9bce-7c45e9625f18)
![IMG_3561](https://github.com/user-attachments/assets/29389166-c11b-442c-8c91-6bbb89882550)
![螢幕擷取畫面 2024-08-22 113033](https://github.com/user-attachments/assets/0b55c4c0-0cb3-43b6-a0fd-f4b7cc02d126)

**Comment by xN1ckuz** [comment]
I can reproduce the same bug, last version 4.8 only

**Comment by whoeevee** [comment]
does it happen with all the songs?

**Comment by ElliotCHEN37** [comment]
> does it happen with all the songs?

yes, I tried many songs

**Comment by ElliotCHEN37** [comment]
> does it happen with all the songs?

I tested again just now, It shows: Unknown Error

**Comment by yodaluca23** [comment]
> Using MITMProxy, This is the response for the lyric fetch to MusixMatch for me
> 
> ```
> {"message":{"header":{"status_code":200,"execute_time":0.183,"pid":405,"surrogate_key_list":[]},"body":{"macro_calls":{"track.lyrics.get":{"message":{"header":{"status_code":404}}},"track.snippet.get":{"message":{"header":{"status_code":404}}},"track.subtitles.get":{"message":{"header":{"status_code":404}}},"matcher.track.get":{"message":{"header":{"status_code":500,"execute_time":0.17126202583313,"exception_id":5000},"body":[]}},"userblob.get":{"message":{"header":{"status_code":404}},"meta":{"status_code":404,"last_updated":"2024-08-22T10:57:48.160Z"}}}}}}
> ```
> 
> The request looks normal though...

Edit: Just realized that it's happening for all songs, MusixMatch probably changed their API, 404 is a not found error usually...

**Comment by yodaluca23** [comment]
Just got another token from a different device, different account. And it works... did MusixMatch somehow detect it and like suspend our accounts or something? 😭😭😭
![image](https://github.com/user-attachments/assets/5ff96a9d-8b32-42d6-b1da-4e643c02b8ff)

**Comment by ElliotCHEN37** [comment]
> > Using MITMProxy, This is the response for the lyric fetch to MusixMatch for me
> > ```
> > {"message":{"header":{"status_code":200,"execute_time":0.183,"pid":405,"surrogate_key_list":[]},"body":{"macro_calls":{"track.lyrics.get":{"message":{"header":{"status_code":404}}},"track.snippet.get":{"message":{"header":{"status_code":404}}},"track.subtitles.get":{"message":{"header":{"status_code":404}}},"matcher.track.get":{"message":{"header":{"status_code":500,"execute_time":0.17126202583313,"exception_id":5000},"body":[]}},"userblob.get":{"message":{"header":{"status_code":404}},"meta":{"status_code":404,"last_updated":"2024-08-22T10:57:48.160Z"}}}}}}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The request looks normal though...
> 
> Just realized that it's happening for all songs, MusixMatch probably changed their API, 404 is a not found error usually...
> 
> Edit: MusixMatch app isn't even working for me... Maybe it's just down?

but my musixmatch app works

**Comment by yodaluca23** [comment]
> > Just realized that it's happening for all songs, MusixMatch probably changed their API, 404 is a not found error usually...
> > Edit: MusixMatch app isn't even working for me... Maybe it's just down?
> 
> but my musixmatch app works

Is the app with the same account you got the token from, if not do so and put it into Eevee and try it.

**Comment by ElliotCHEN37** [comment]
! BIG NEWS!
It suddenly works! idk why, i did nothing
so I'm not sure if it is just a temporary issue

**Comment by ElliotCHEN37** [comment]
i tested two songs, they're ころしちゃった! (feat. 初音ミク) by 夏山よつぎ and 七里香(Live) by 周杰倫

**Comment by yodaluca23** [comment]
> ! BIG NEWS! It suddenly works! idk why, i did nothing so I'm not sure if it is just a temporary issue

Still only working for me with a new MusixMatch account/token

**Comment by ElliotCHEN37** [comment]
tested more songs, the lyrics were back, and translations were working for me
but still not sure if it is a temporary issue

**Comment by 3xynos7** [comment]
> > Using MITMProxy, This is the response for the lyric fetch to MusixMatch for me
> > ```
> > {"message":{"header":{"status_code":200,"execute_time":0.183,"pid":405,"surrogate_key_list":[]},"body":{"macro_calls":{"track.lyrics.get":{"message":{"header":{"status_code":404}}},"track.snippet.get":{"message":{"header":{"status_code":404}}},"track.subtitles.get":{"message":{"header":{"status_code":404}}},"matcher.track.get":{"message":{"header":{"status_code":500,"execute_time":0.17126202583313,"exception_id":5000},"body":[]}},"userblob.get":{"message":{"header":{"status_code":404}},"meta":{"status_code":404,"last_updated":"2024-08-22T10:57:48.160Z"}}}}}}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The request looks normal though...
> 
> Just realized that it's happening for all songs, MusixMatch probably changed their API, 404 is a not found error usually...
> 
> Edit: MusixMatch app isn't even working for me... Maybe it's just down?

Yup not working with the existing token/account.

**Comment by xN1ckuz** [comment]
It's not working again on me

**Comment by asdfzxcvbn** [comment]
is this resolved for everyone

**Comment by yodaluca23** [comment]
> is this resolved for everyone

Yes, it's even working for me on the original Account, they probably just had a small outage, would be my guess...

**Comment by 3xynos7** [comment]
> is this resolved for everyone

Yes, it's working now.
