### ISSUE TITLE
where’s the .ipa

### ISSUE THREAD

**Issue by jmjm07m** [whoeevee/EeveeSpotify#339]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

where do i find the .ipa? can i download it on scarlet? someone pls help me

**Comment by diow142** [comment]
You can find it under the release tab:https://github.com/whoeevee/EeveeSpotify/releases

**Comment by jmjm07m** [comment]
> You can find it under the release tab:https://github.com/whoeevee/EeveeSpotify/releases

it shows this :/
![IMG_8321](https://github.com/user-attachments/assets/f29723b9-6eca-4ce1-b9a5-1d65fcc49901)
it says “you can’t install spotify…try it again later”

**Comment by diow142** [comment]
It’s revoked so you can’t install apps.

**Comment by asdfzxcvbn** [comment]
it's in releases and installation is unrelated to the tweak directly
