### ISSUE TITLE
[REQUEST]Lossless audio

### ISSUE THREAD

**Issue by Ers0und** [whoeevee/EeveeSpotify#341]
Before eevee Spotify there was a modded version of Spotify with lossless audio named"Hi-Fi unlocker", I wonder if it possibile to add this tweak instead of high audio quality

**Comment by diow142** [comment]
Spotify doesn’t even have hi-fi for premium users.

**Comment by Ers0und** [comment]
> Spotify doesn’t even have hi-fi for premium users.

So that tweak is a scam, sad
