### ISSUE TITLE
[Bug] Google cast not working 

### ISSUE THREAD

**Issue by RishiSuthar** [whoeevee/EeveeSpotify#342]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

I’m not sure if this is only on my side but devices for google cast is not showing with the tweaked Spotify. Tried it with normal Spotify and is working just fine. The local network is enabled in settings 

![IMG_8766](https://github.com/user-attachments/assets/7b80ce62-b0c4-40b7-a207-a1c226bdbb52)
![IMG_8767](https://github.com/user-attachments/assets/d3d16c5f-6fbf-4beb-8fcf-f8941d8bf688)

**Comment by yodaluca23** [comment]
This is happening to me and menu others as well... what's weird is it worked for me until I reinstalled it at one point... what I'm thinking is maybe trying to download an old version that shows it up and then upgrading it and maybe it'll work.. https://github.com/SpotCompiled/SpotveeC/issues/15

**Comment by asdfzxcvbn** [comment]
can someone test this on trollstore? or maybe try #32

**Comment by yodaluca23** [comment]
> can someone test this on trollstore? or maybe try #32

From my testing it does work with TrollStore....

**Comment by RishiSuthar** [comment]
> > can someone test this on trollstore? or maybe try #32
> 
> From my testing it does work with TrollStore.... But it's weird that it worked before...

yeah it worked very well in the previous versions of eevespotify. Also works on spotilife

**Comment by yodaluca23** [comment]
Yea, ok, so this is what I did to fix it.
Delete whatever you have installed now.
Install the version with EeveeSpotify 4.0, (probably works with others, this is the one I tested)
Use Google cast give permission and whatever.
Upgrade to latest, (don't delete old just install over) and it should work.

**Comment by RishiSuthar** [comment]
> Yea, ok, so this is what I did to fix it. Delete whatever you have installed now. Install the version with EeveeSpotify 4.0, (probably works with others, this is the one I tested) Use Google cast give permission and whatever. Upgrade to latest, (don't delete old just install over) and it should work.

I did this,
-deleted the one i had
- installed 4.0 (casting and everything worked perfect)
- installed 4.8 over it 

did not work, still asks for network settings

**Comment by RishiSuthar** [comment]
I can confirm this is working in the newest (4.9) version. Thanks for the fix

**Comment by RishiSuthar** [comment]
I can confirm this is working in the newest (4.9) version. Thanks for the fix ✅

**Comment by gototheskinny** [comment]
Still happens in 5.0 too.

**Comment by gototheskinny** [comment]
> > Still happens in 5.0 too.
> 
> 
> 
> 5.0 and 5.1 were language updates, they only contained more language translation, no other updates. so this issue won't be fixed in 5.0 or 5.1

OK, I just wanted to let you guys know.

**Comment by asdfzxcvbn** [comment]
EeveeSpotify does not touch the casting feature

**Comment by proxium** [comment]
I confirm that this is an issue in versions: 
EeveeSpotify-4.0-8.9.42.ipa (Google Cast device accept connection but doesn't offer music seek, only shuffling and playing ads)
EeveeSpotify-5.0-8.9.70.ipa (Google Cast device not showing at all)

I downgraded to SpotilifeC.v1.2.3_v8.6.42.ipa (all Casting features working with the luck Lyrics)
