### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Xd69sys** [whoeevee/EeveeSpotify#345]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

I have updated to version 4.9 but the letter with musixmatch still does not appear in the local files, with lrcb it does work but with musixmatch it does not

**Comment by whoeevee** [comment]
can you show screenshots
