### ISSUE TITLE
[Bug] Spotify Autoplay similar content doesn’t work

### ISSUE THREAD

**Issue by Jacon707** [whoeevee/EeveeSpotify#347]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

Queue ends when the playlist runs out of songs instead of looking for similar songs, I have tried with it turned on and off and both options dont do anything

**Comment by ElliotCHEN37** [comment]
Go to settings -> playback -> turn on it
Play any songs, make sure loop was turned off

**Comment by Lorenzoformi2001** [comment]
> ### Is this issue appropriate?
> * [x]  I have read the document in its entirety
> 
> ### Is this issue unique to EeveeSpotify?
> * [x]  I was unable to reproduce my issue using the stock Spotify app
> 
> ### Have you searched the existing issues?
> * [x]  This is a unique issue
> 
> ### Describe the bug.
> Queue ends when the playlist runs out of songs instead of looking for similar songs, I have tried with it turned on and off and both options dont do anything

same here, i already asked about it some time ago but never found a solution. Pls I need to find a way to enable it cause it's very annoying

**Comment by Jacon707** [comment]
> Go to settings -> playback -> turn on it Play any songs, make sure loop was turned off

Still doesn’t work unfortunately, queue still ends on the song.

**Comment by Jacon707** [comment]
Misclick.

**Comment by ElliotCHEN37** [comment]
that's strange, for me, everything works great. maybe try to re-install?

**Comment by Jacon707** [comment]
> that's strange, for me, everything works great. maybe try to re-install?

Already did, had no luck :(

**Comment by RishiSuthar** [comment]
I have the same issue…. Found no fix

**Comment by kym03** [comment]
I have same issues..anyone have solved the problem??

**Comment by asdfzxcvbn** [comment]
EeveeSpotify doesn’t mess with it
