### ISSUE TITLE
[Question] I want to add a new language to the app

### ISSUE THREAD

**Issue by gocciolafr** [whoeevee/EeveeSpotify#349]
Basically on the title i want to add Albanian language to the app because i saw a lot of albanians using spotify and this mod too, and i’m wondering if it is possible to add this language to this app. i will provide all the translation

**Comment by ElliotCHEN37** [comment]
Follow these steps:
1. Fork this repo
2. Go to layout/Library/Application Support/EeveeSpotify.bundle
3. Create a folder named your language's code end with .lproj, for example, Chinese Traditional (Taiwan) is zh-TW, so the folder should be named zh-TW.lproj
4. Create Localizable.strings in the folder, .strings files are .txt files
5. Refer to en.lproj for translation.
6. Commit to your forked repo
7. Open pull request
