### ISSUE TITLE
[Bug] carplay not popping up 

### ISSUE THREAD

**Issue by mokshith2** [whoeevee/EeveeSpotify#350]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

The carplay doesn’t detect eeveespotify as spotify but the iPhone does

**Comment by asdfzxcvbn** [comment]
as mentioned above, it only works on trollstore
