### ISSUE TITLE
[Bug] EeveeSpotify Stopped Working

### ISSUE THREAD

**Issue by 3xynos7** [whoeevee/EeveeSpotify#356]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

I'm experiencing a problem with EeveeSpotify (Swift v4.9, latest version). My network connection is stable, and I'm online, but when I open the app, it says, "You discovered a premium feature." I restarted the app and tried to play music from my playlist, but the songs are grayed out. While the songs appear in my playlist, they won’t play at all. I've attached a video showing the issue for further clarification.

https://github.com/user-attachments/assets/bbabea32-64f8-4c46-91c3-c623ab8d197a

![IMG_2626](https://github.com/user-attachments/assets/46d4282d-12a4-4cab-83ce-2eba9d85a2b6)

**Comment by whoeevee** [comment]
read common issues, it’s region one

**Comment by 3xynos7** [comment]
> read common issues, it’s region one

Wait, But it's working perfectly file on Web browser, Same account, No NPN. Tried just now in my PC.

**Comment by whoeevee** [comment]
to fix the issue in mobile app, you'll need to change your Spotify account region to another one using a VPN, then relogin

**Comment by 3xynos7** [comment]
> to fix the issue in mobile app, you'll need to change your Spotify account region to another one using a VPN, then relogin

Thank You.
