### ISSUE TITLE
[QUESTION] Which one was the version you could download songs and use offline spotify

### ISSUE THREAD

**Issue by jackmkqt5** [whoeevee/EeveeSpotify#360]
I remember like in june, there was a version I downloaded and installed with sideloadly that let me download songs ad use offline spotify. I'm pretty sure there was..

**Comment by RabbyDevs** [comment]
I'm fairly sure that there was also a version that allowed downloading, only on new accounts though...

I unknowingly lost it when I wiped my disk, sadly.

**Comment by yodaluca23** [comment]
Spotify usually gives you premium for free for like 2 weeks when you create a new account, that's usually what you remember...

**Comment by RabbyDevs** [comment]
No, I tried this same trick with EeveeSpotify and it didn't work. Perhaps because the download button is hard-code shut. Not sure.

**Comment by yodaluca23** [comment]
> No, I tried this same trick with EeveeSpotify and it didn't work. Perhaps because the download button is hard-code shut. Not sure.

Make sure they did give trial, then turn off patch premium...
