### ISSUE TITLE
[Error]Musixmatch stops working from time to time

### ISSUE THREAD

**Issue by Xd69sys** [whoeevee/EeveeSpotify#361]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

Musixmatch works well, but every certain hours it stops working, I restart and it doesn't work, but it takes a few minutes and it works again, until after a while it doesn't work again and in a few minutes it works again

**Comment by Diowboss** [comment]
This literally just happened to me

**Comment by ElliotCHEN37** [comment]
Check #336 , it might help

**Comment by asdfzxcvbn** [comment]
musixmatch is just a bit unstable, and we were unable to reproduce this
