### ISSUE TITLE
[Bug] Erm, what do I do??

### ISSUE THREAD

**Issue by ErmWhatTheSigmaLigma** [whoeevee/EeveeSpotify#362]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

![5B600945-0779-409D-89A5-A4ABF9CC0292](https://github.com/user-attachments/assets/fb9f711e-05bb-42f4-babe-efbbe568c5f4)

**Comment by ErmWhatTheSigmaLigma** [comment]
Kill yourself

**Comment by asdfzxcvbn** [comment]
you read the popup
