### ISSUE TITLE
[Suggestion] TrollFools Support

### ISSUE THREAD

**Issue by bathtimethiago** [whoeevee/EeveeSpotify#368]
[EeveeSpotify-5.0-TF.zip](https://github.com/user-attachments/files/16922158/EeveeSpotify-5.0-TF.zip) arm64

**Comment by asdfzxcvbn** [comment]
just extract the deb and inject the necessary things

**Comment by Miroxyz** [comment]
@asdfzxcvbn What's different between arm64.deb and arm.deb?

**Comment by asdfzxcvbn** [comment]
> @asdfzxcvbn What's different between arm64.deb and arm.deb?

-arm.deb is for rootful jailbreaks

-arm64.deb is for rootless jailbreaks
