### ISSUE TITLE
is there any way to change color of the stuff on the app from green to any color? thru the settings

### ISSUE THREAD

**Issue by mesk69** [whoeevee/EeveeSpotify#369]
it would be nice

**Comment by asdfzxcvbn** [comment]
it would be a challenge:

“
The colors in SPTEncoreColor are bits that are accessed using the value property and then encoded to UIColor.

Some colors are simply UIColor, and they are set without any direct calls to SPTEncoreColorTheme, so we need to hook into the setBackgroundColor method. However:

- Switches have an onTintColor (representing the state when they are on), but I don’t know how it’s being set. Again, there are no calls to SPTColorsTheme or anything like initWithRed:green:alpha.

- Buttons like shuffle, like, etc., are animated with Lottie. They use their own framework, colors, and are encoded as Swift double values, etc.

- There are also gradients and chroma views, and I’m not sure how colors are handled in those cases.

- Some images, like the pin icon, are UIImage with a rendering mode of alwaysOriginal, meaning they are green by nature, essentially PNG files.

And so on.
“

**Comment by mesk69** [comment]
dang it
