### ISSUE TITLE
亲爱的朋友，你有越狱源吗？

### ISSUE THREAD

**Issue by canglaoshifu** [whoeevee/EeveeSpotify#37]

**Comment by asdfzxcvbn** [comment]
what?

**Comment by canglaoshifu** [comment]
I mean how do I subscribe in Sileo? What is the subscription address? Haha, I just tried it. After installing it, Spotify can't get into the software. It's stuck in the startup interface.
![3C5AD39A-4761-48FD-8DC0-B15EB781BCF3](https://github.com/whoeevee/EeveeSpotify/assets/58038734/57aef96f-520e-4c7c-9430-a5b315f97836)

**Comment by asdfzxcvbn** [comment]
eeveespotify does not have an (official) jb repo

as for your issue, maybe you can use choicy to only allow eevee to inject into spotify

**Comment by canglaoshifu** [comment]
Thank you very much for running perfectly according to your method. The sound quality can't be set to super high, right?

**Comment by asdfzxcvbn** [comment]
> The sound quality can't be set to super high, right?

exactly, that's impossible
