### ISSUE TITLE
[Bug] App doesn’t have access to local network even after accepting permission through app and settings.

### ISSUE THREAD

**Issue by BurnaBoy12** [whoeevee/EeveeSpotify#374]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

The app doesn’t have access to the local network even after giving it access both in app and in device settings. This makes it impossible to connect to WiFi based speakers, E.G. Sonos Play systems, Sony Systems etc.
![IMG_4376](https://github.com/user-attachments/assets/2c147462-a02a-457f-81eb-3b322be79feb)

**Comment by yodaluca23** [comment]
Duplicate #342
