### ISSUE TITLE
Seek help

### ISSUE THREAD

**Issue by tuantuan-apt** [whoeevee/EeveeSpotify#376]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

Help me, can you write a plugin for Spotify's last version 8.8.2 on iOS 13? My phone is iPhone 11, iOS 13.5.1

**Comment by ElliotCHEN37** [comment]
iOS 13 isn’t supported in the latest version. This tweak is designed for the latest version which requires at least 14.0 or higher

**Comment by asdfzxcvbn** [comment]
true

EeveeSpotify hasn’t, doesn’t, and won’t support iOS 13
