### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Label5red** [whoeevee/EeveeSpotify#378]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

EeveeSpotify does not appear on the carplay display

**Comment by asdfzxcvbn** [comment]
bro when will people start reading
