### ISSUE TITLE
[Feature Request] Dylibs for TrollFools

### ISSUE THREAD

**Issue by hieunv95** [whoeevee/EeveeSpotify#379]
I would like a new build of EeveeSpotify for TrollFools, such as this repo:
https://github.com/bibabibu369/Dylibs-for-TrollFools

I tried to create new GitHub Action workflow for this kind of build but there is no luck to make it injectable with TrollFools.

Could you help me, please?

Thank you in advance! ❤️

**Comment by yodaluca23** [comment]
Just install Nathanlr, and use the rootless .deb
https://ios.cfw.guide/installing-nathanlr/

**Comment by asdfzxcvbn** [comment]
damn a new semi-jailbreak?? didn't even hear about it

anyways thats the appropriate "solution"

**Comment by yodaluca23** [comment]
> damn a new semi-jailbreak?? didn't even hear about it

Yeah, it's based on serotonin, but it's not like stupid roothide that came up with another package architecture. It just uses standard rootless.

**Comment by hieunv95** [comment]
@yodaluca23 @asdfzxcvbn 

So I can not install EeveeSpotify's tweaks with encrypted App Store applications (user registration application) with bare dynamic library.

I do not want to jailbreak my phone.

I am currently using TrollStore to install decrypted App Store applications (TrollStore applications). But it has some limitations:

- OpenWithSpotify extension not working

**Comment by yodaluca23** [comment]
> I am currently using TrollStore to install decrypted App Store applications (TrollStore applications). But it has some limitations:
> 
> 
> 
> - OpenWithSpotify extension not working

If you have TrollStore, just use the compiled .ipa

**Comment by asdfzxcvbn** [comment]
> So I can not install EeveeSpotify's tweaks with encrypted App Store applications (user registration application) with bare dynamic library?

we don't and aren't going to support TrollFools injection, it requires trollstore meaning you can either:

- jailbreak and install the deb
- use the compiled ipa

> I am currently using TrollStore to install decrypted App Store applications (TrollStore applications). But it has some limitations:
> 
> - OpenWithSpotify extension not working

you dont need the extension when installing with trollstore. the app's deeplinks will register with the system correctly and clicking any spotify link should make the sideloaded app open immediately

**Comment by asdfzxcvbn** [comment]
edit: TrollFools zips will now be included in future releases thanks to [TweakZipper](https://github.com/asdfzxcvbn/TweakZipper)
