### ISSUE TITLE
Siri bug

### ISSUE THREAD

**Issue by xflesx69** [whoeevee/EeveeSpotify#381]
When i say something like play music to siri it keeps asking me to verify my account.

**Comment by xflesx69** [comment]
![image](https://github.com/user-attachments/assets/eb2808c8-abec-4ad9-a546-2ac5337382f4)

**Comment by xflesx69** [comment]
> TrollStore only

I installed from altstore. Its a trollstore only feature?

**Comment by xflesx69** [comment]
> > I installed from altstore. Its a trollstore only feature?
> 
> 
> 
> Yes
> 
> https://github.com/whoeevee/EeveeSpotify/issues/210

Ahw.. its for jailbroken devices:(

**Comment by asdfzxcvbn** [comment]
> Ahw.. its for jailbroken devices:(

nope, just devices on old iOS versions
