### ISSUE TITLE
[Suggestion] New version for MacOS

### ISSUE THREAD

**Issue by justwantanswers** [whoeevee/EeveeSpotify#384]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

It would be great if EeveeSpotify could be made for MacOS, or at least the dev creates a newer, more up to date version as the current tweaked version is stuck on Spotify for macOS (Intel) 1.1.95.893.g6cf4d40c

**Comment by yodaluca23** [comment]
Just use BlockTheSpot or SpotX

**Comment by asdfzxcvbn** [comment]
we wanted it however it would be a challenge to due orion possibly not running on macos, over 100+ symbols being hooked, etc

**Comment by bendschs** [comment]
I found that i can just install the ios-ipa on macos via sideloadly, it works well in generell, the only thing is, that constantly get a pup-up message to "adjust my tracking options in ios settings". Would there a way to suppress this?

**Comment by yodaluca23** [comment]
> I found that i can just install the ios-ipa on macos via sideloadly, it works well in generell, the only thing is, that constantly get a pup-up message to "adjust my tracking options in ios settings". Would there a way to suppress this? 

Why are you doing this? There are already solutions on the native macOS Spotify app. Use SpotX or blockthespot.

**Comment by bendschs** [comment]
because blockthespot is no longer maintained and spotx-bash is still letting ads through from time to time. the ios app works perfectly.

**Comment by yodaluca23** [comment]
> because blockthespot is no longer maintained and spotx-bash is still letting ads through from time to time. the ios app works perfectly.

BlockTheSpot, is still maintained just has not updated for 1.2.55. SpotX was in beta for 1.2.55, now it's fully supported reinstall to install the latest.

**Comment by bendschs** [comment]
okay thanks, i will try again.
