### ISSUE TITLE
[Bug] Artist pages does not show liked releases

### ISSUE THREAD

**Issue by TheKivster** [whoeevee/EeveeSpotify#389]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

On regular Spotify Premium, there is a section on the artist page just below the "Music/Merch" section that shows all of your liked releases and songs. EeveeSpotify lacks this feature. I never had a problem with this on the official Spotify app.

**Comment by asdfzxcvbn** [comment]
fixed in https://github.com/whoeevee/EeveeSpotify/commit/eeaa55e4fd32b0660794873bc81073efdfffedab

will be out in next release
