### ISSUE TITLE
appdb

### ISSUE THREAD

**Issue by hihihihihiray** [whoeevee/EeveeSpotify#391]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

i have a suggestion, can you add eevee spotify 5.2 to appdb i want to use it instead of 4.2 @whoeevee

**Comment by asdfzxcvbn** [comment]
our only official forms of release are github releases and our telegram channel, we are not responsible for any other source

**Comment by srinivasb99** [comment]
> ### Is this issue appropriate?
> 
> - [X] I have read the document in its entirety
> 
> ### Is this issue unique to EeveeSpotify?
> 
> - [X] I was unable to reproduce my issue using the stock Spotify app
> 
> ### Have you searched the existing issues?
> 
> - [X] This is a unique issue
> 
> ### Describe the bug.
> 
> i have a suggestion, can you add eevee spotify 5.2 to appdb i want to use it instead of 4.2 @whoeevee

I will upload them for you. Just search for Spotify on app db and download the latest one

**Comment by hihihihihiray** [comment]
oh thanks i appreciate it 🙏 @whoeevee
