### ISSUE TITLE
Question Regarding Spotify Connect (Play on Other Devices)

### ISSUE THREAD

**Issue by stormt9** [whoeevee/EeveeSpotify#396]
Does this IPA have Spotify connect for devices on local network? I have both the settings turned on in the app and iPhone Settings, but my speaker linked to my wifi isn't appearing (like it did on the actual app). Thanks for your service 🫡

**Comment by yodaluca23** [comment]
Yea it's a bug, theirs a workaround

https://github.com/whoeevee/EeveeSpotify/issues/342#issuecomment-2309222627

**Comment by emaschi5** [comment]
The workaround doesn’t work for me, the only fix is to move to another ipa unfortunately

**Comment by asdfzxcvbn** [comment]
i believe we've already told people to use bluetooth countless times, eeveespotify does not touch spotify connect

even then it probably wouldn't work, i believe it connects directly to spotify so premium features wouldnt work anyway
