### ISSUE TITLE
[Question] Eeveespotify carplay!

### ISSUE THREAD

**Issue by alexlearncss** [whoeevee/EeveeSpotify#397]
When I connect my phone to carplay but can't find the app on the car screen, it strange but i can stream my audio via phone to the car 😅

**Comment by yodaluca23** [comment]
Yes, you can use the NowPlaying API that just works on every media playing app and you can airplay it to any airplay capable device... if you want the app to show in CarPlay, you either need a certificate that supports CarPlay entitlement or TrollStore.
