### ISSUE TITLE
Seek bar disabled if using Spotify Connect

### ISSUE THREAD

**Issue by Vetrix68** [whoeevee/EeveeSpotify#4]
If I connect to the Denon receiver, the seek bar turns gray, and skipping a song shows that there are only 6 skips left

![image](https://github.com/whoeevee/EeveeSpotify/assets/75122363/4a23e206-3fce-405d-8937-80825214b0fa)

**Comment by asdfzxcvbn** [comment]
theres likely a subscription recheck when you do that. i plan on updating the objc branch to (hopefully) fix everything

from the README:

> It can stop working just like Spotilife

> Spotify reloads user data from time to time (and on changing network, for example), so if Premium stops working, simply restart the app.

**Comment by whoeevee** [comment]
new releases are pushed
can you test it with v1.2? (objc or swift)

**Comment by Vetrix68** [comment]
Same thing happens, still disabled and ad popups appear too

![image](https://github.com/whoeevee/EeveeSpotify/assets/75122363/6980e0c9-c199-41b2-999b-f85385e0f43a)

**Comment by asdfzxcvbn** [comment]
considering you're seeing ads and you dont have a premium button then the update process likely just broke. uninstall spotify then reinstall the new v1.2 ipa

**Comment by Vetrix68** [comment]
After reinstalling, ads are gone, skips are unlimited (even if connected using Spotify Connect) but unfortunately, the seek bar is still grayed out

**Comment by Vetrix68** [comment]
And this was an issue with newer versions of Spotilife (the older ones still have the seek bar working as expected). I assume it's a bit more complicated.

**Comment by Vetrix68** [comment]
@whoeevee @asdfzxcvbn Currently, it's even worse. While using Connect, Premium disables itself and restarting doesn't do anything - it only plays random songs. Tried reinstalling, works only for one song.

**Comment by asdfzxcvbn** [comment]
is this fixed/bettered in v1.4?

**Comment by Vetrix68** [comment]
Skips fixed, favourite songs play randomly, seek bar still disabled

**Comment by asdfzxcvbn** [comment]
please test v4.0 @Vetrix68

**Comment by Vetrix68** [comment]
> please test v4.0 @Vetrix68 

It's still disabled, unlimited skips sometimes works, and it gives me an ad every time I select a song from a playlist.

**Comment by whoeevee** [comment]
> > please test v4.0 @Vetrix68
> 
> It's still disabled, unlimited skips sometimes works, and it gives me an ad every time I select a song from a playlist.

did you set dynamic premium patching method?

**Comment by Vetrix68** [comment]
> did you set dynamic premium patching method?

I did, only thing I can tell you is that if I play something using your patch, and then open the old spotilife spotify 8.6.42, the seek bar is disabled until I play something else using the spotilife one. Also, the newer versions of spotilife that used to work back then also had the seek bar disabled, only the older ones worked fine.

**Comment by RishiSuthar** [comment]
yeah same for me. Seek bar still disabled in v4.0

**Comment by asdfzxcvbn** [comment]
to be honest maybe this issue should be closed, it's been open for over a month with no resolution

there might be some other way spotify checks for a subscription which we can’t modify

@whoeevee thoughts?

**Comment by asdfzxcvbn** [comment]
unfortunately we don't have a device to test any fixes on, so we really can't help with this anymore
