### ISSUE TITLE
Siri support

### ISSUE THREAD

**Issue by rafaeldamasceno** [whoeevee/EeveeSpotify#40]
Is there a way to get Siri to work when sideloading? Whenever I ask Siri to play something, it just sort of crashes and does nothing. Sideloaded YouTube can still play stuff even with no extensions, so I'm wondering if something could be done about it.

**Comment by Finealex** [comment]
What bundle is do I put?

**Comment by asdfzxcvbn** [comment]
> What bundle id do I put?

you’ll also need to change the app id, just use signtools

**Comment by haomuch** [comment]
So sad that the normal sideloaded EeveeSpotify can't be controlled by siri
