### ISSUE TITLE
Odd error message

### ISSUE THREAD

**Issue by VictoriaTyler-X** [whoeevee/EeveeSpotify#403]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

So I went to open the app this morning, and out of nowhere, got this random error, with the app failing to start:

![IMG_0043](https://github.com/user-attachments/assets/dd2eb273-5a4c-45b2-afa2-a32a03157ac6)

Any idea what this could be caused by?

**Comment by yodaluca23** [comment]
This is whatever signing method you're using having issues nothing to do with EeveeSpotify.

Your certificate probably was revoked or expired.
