### ISSUE TITLE
[Bug] Clicking on the meatball menu in the upper right corner of the song playback screen causes the app to crash

### ISSUE THREAD

**Issue by oxonium0215** [whoeevee/EeveeSpotify#406]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

Clicking on the meatball menu in the upper right corner of the song playback screen causes the app to crash.

![8E447F09-D069-48C4-A092-F2377ACB0732](https://github.com/user-attachments/assets/12b3d102-f1d4-4379-ba78-8c5d737bce56)

https://github.com/user-attachments/assets/66b8edf6-7f97-403e-ba97-ca0b940af87f

**Comment by ElliotCHEN37** [comment]
check #388
