### ISSUE TITLE
[FR] Increase Pin Limit In Library Possible?

### ISSUE THREAD

**Issue by TheNightRider12** [whoeevee/EeveeSpotify#407]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

Is it possible to increase the pin limit of artists, playlists, etc., to a higher number? Or perhaps unlimited. Only having 4 pins is a rather low number. I know that’s the default and maximum currently available in Spotify, but I wonder if there is a way to increase that

**Comment by asdfzxcvbn** [comment]
no
