### ISSUE TITLE
[Bug] Clicking on the meatball menu in the upper right corner of the song playback screen causes the app to crash

### ISSUE THREAD

**Issue by Richard-NDC** [whoeevee/EeveeSpotify#408]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [x] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

It only happens when i turn on Overwrite Configuration so your team can check that feature and fix it. And for user maybe just turn off it in eeveespotify settings

**Comment by Richard-NDC** [comment]
*Bonus: when i use that feature on premium account it "Create Playlist" button is disappeared so maybe just replace it with new configuration from spotify

**Comment by Richard-NDC** [comment]
maybe when fix with the lastest configuration it won't appear Register Premium anymore

**Comment by ElliotCHEN37** [comment]
#388

**Comment by ElliotCHEN37** [comment]
#406

**Comment by Richard-NDC** [comment]
i'm just help them to find solution if it possible lol

**Comment by whoeevee** [comment]
I’ve looked into it, seems to be configuration issue that causes the app to crash for some reason. This configuration defines many UI/UX-related features, like buttons, etc. While it works on my machine, I’ll update the configuration in the next release, which should resolve the issue

**Comment by yodaluca23** [comment]
> I’ve looked into it, seems to be configuration issue that causes the app to crash for some reason. This configuration defines many UI/UX-related features, like buttons, etc. While it works on my machine, I’ll update the configuration in the next release, which should resolve the issue

Perhaps this could be the problem with Spotify connect breaking around version 4.0. And would make sense kind of why downgrading to before that and then updating through to the latest it works...

**Comment by whoeevee** [comment]
should be fixed with https://github.com/whoeevee/EeveeSpotify/commit/07d505fe8035e34e5280cf2409e6d64b1df298a1

**Comment by Richard-NDC** [comment]
> should be fixed with [07d505f](https://github.com/whoeevee/EeveeSpotify/commit/07d505fe8035e34e5280cf2409e6d64b1df298a1)

ok i will check and test it

**Comment by Richard-NDC** [comment]
> should be fixed with [07d505f](https://github.com/whoeevee/EeveeSpotify/commit/07d505fe8035e34e5280cf2409e6d64b1df298a1)

it’s working fine
![IMG_0158](https://github.com/user-attachments/assets/a18b05de-5432-4fee-ab1c-f56b3187800a)
