### ISSUE TITLE
[Bug] Repo Alt Store - Duplicate version

### ISSUE THREAD

**Issue by sergio-nadal** [whoeevee/EeveeSpotify#409]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

Alt Store 2.0 has been released but when adding the official source it shows an error for duplicate version.

In the repo.json and repo.altsource.json files there is a duplicate of version 8.9.60. When a duplicate is removed it works correctly.

![Imagen de WhatsApp 2024-09-28 a las 22 03 34_ab5c9e30](https://github.com/user-attachments/assets/ef071c7e-2878-4abd-a0de-7a55e96ce82f)

**Comment by asdfzxcvbn** [comment]
lol oops
