### ISSUE TITLE
Premium doesn't get activated

### ISSUE THREAD

**Issue by AstudilloMarillo** [whoeevee/EeveeSpotify#41]
Whatever I try, whatever I do, Premium will not get activated for me.
I tried login out and back in multiple times, restarting the app multiple times, resetting the data multiple times.
Are there any requirements I'm not aware of?

I'm using Swift 1.4.1 sideloaded with Alt Store, I'm on iOS 17.4.1 on an iPhone XS. I have another (older) sideloaded Spotify app on my phone that does work.
Are any of these things not supported?

**Comment by whoeevee** [comment]
do you get any popups?

**Comment by AstudilloMarillo** [comment]
> do you get any popups?

Yes, I get the popups that say to login and restart app or else to reset data and restart app. I follow those instructions but unfortunately no luck. For what it's worth, I also get the popup to allow notifications.

**Comment by vuviett47** [comment]
make new account not working, but I haven't try use VPN and make US account yet

**Comment by asdfzxcvbn** [comment]
> maybe try making a new account? and also use a VPN to USA


please test and update @AstudilloMarillo

**Comment by Service1995** [comment]
> do you get any popups?

Excuse me, how to solve the infinite jump song?

**Comment by AstudilloMarillo** [comment]
> please test and update @AstudilloMarillo 

Will do within the next few days, haven't had time.

**Comment by AstudilloMarillo** [comment]
> maybe try making a new account? and also use a VPN to USA

Tried this, does not work. Tried with the 2.0 version.

**Comment by vuviett47** [comment]
its working for me in 2.1

**Comment by AstudilloMarillo** [comment]
I don't know why, but it's finally working for me now in 3.0! I didn't do anything different then with previous versions. Anyway, finally works 😀.
