### ISSUE TITLE
[Bug] OS version issue

### ISSUE THREAD

**Issue by Wenwenwhen** [whoeevee/EeveeSpotify#416]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

This may be stupid, but I'm finally turning to this solution after Spotifys recent BS premium update. I have MacOS version 11.3.1. It says that 11+ is required to complete installation, does that not count? Sorry if this is dumb.
<img width="222" alt="Screen Shot 2024-09-29 at 10 47 36 PM" src="https://github.com/user-attachments/assets/fd901cfa-3b86-433a-9b31-c8089a3ad55c">

**Comment by yodaluca23** [comment]
This is not meant to be used with MacOS (you might be able to get it working but I wouldn't recommend it) . For MacOS you should use SpotX or BlockTheSpot...

**Comment by Wenwenwhen** [comment]
> This is not meant to be used with MacOS (you might be able to get it working but I wouldn't recommend it) . For MacOS you should use SpotX or BlockTheSpot...

I was told it was for iOS but I read a few people saying that it could potentially work on MacOS. Thank you for clarifying and offering alternatives. I'll just leave this here so if anyone else makes the same mistake as me they can read your reply.
