### ISSUE TITLE
i believe we've already told people to use bluetooth countless times, eeveespotify does not touch spotify connect

### ISSUE THREAD

**Issue by elbow-stan** [whoeevee/EeveeSpotify#417]
i believe we've already told people to use bluetooth countless times, eeveespotify does not touch spotify connect

even then it probably wouldn't work, i believe it connects directly to spotify so premium features wouldnt work anyway

_Originally posted by @asdfzxcvbn in https://github.com/whoeevee/EeveeSpotify/issues/396#issuecomment-2380906279_

Reply: using Bluetooth is fine for speakers and headphones, but does not work for listening on Xbox. When switching from listening on mobile to Xbox I start getting ads.
You mentioned this is a premium feature, but spotilife had no issue with this previously, is there any workaround?

**Comment by yodaluca23** [comment]
My current theory is that either Spotilife or just the very old version that of the Spotify app uses a different Spotify Connect endpoint that allows it to not check premium status for streaming or something. I don't know... assuming it is true that Spotilife does work whenever using Spotify connect...

**Comment by Richard-NDC** [comment]
> My current theory is that either Spotilife or just the very old version that of the Spotify app uses a different Spotify Connect endpoint that allows it to not check premium status for streaming or something. I don't know... assuming it is true that Spotilife does work whenever using Spotify connect...

Yes, in the previous version that Spotilife supported, Spotify didn’t play songs randomly.

**Comment by elbow-stan** [comment]
@Richard-NDC so you don’t think there’s any way to implement/ get round it?

**Comment by Richard-NDC** [comment]
> @Richard-NDC so you don’t think there’s any way to implement/ get round it?

maybe no because it's server-sided

**Comment by Richard-NDC** [comment]
> @Richard-NDC so you don’t think there’s any way to implement/ get round it?

i think there is a way is play it using a computer

**Comment by elbow-stan** [comment]
> > @Richard-NDC so you don’t think there’s any way to implement/ get round it?
> 
> i think there is a way is play it using a computer

What’s the method? Any way to do this from iPhone?

**Comment by Richard-NDC** [comment]
> > > @Richard-NDC so you don’t think there’s any way to implement/ get round it?
> > 
> > 
> > i think there is a way is play it using a computer
> 
> What’s the method? Any way to do this from iPhone?

idk

**Comment by bfsr83** [comment]
When using the github.com/Team-xManager/xManager on android or github.com/SpotX-Official/SpotX on windows, this "issue" doesn't occur, even when using Spotify Connect (obviously with the same - free - account). Doesn't this prove that this is not a server-side feature?

**Comment by yodaluca23** [comment]
> When using the github.com/Team-xManager/xManager on android or github.com/SpotX-Official/SpotX on windows, this "issue" doesn't occur, even when using Spotify Connect (obviously with the same - free - account). Doesn't this prove that this is not a server-side feature?

I've tried using spotX to cast to a Google Home speaker and it doesn't work for me... but that was a while ago. 

Also
https://spotx-official.github.io/spotx-docs/faq/Windows#i-get-ads-when-i-use-spotify-connect-airplay-etc-why

**Comment by bfsr83** [comment]
> > When using the github.com/Team-xManager/xManager on android or github.com/SpotX-Official/SpotX on windows, this "issue" doesn't occur, even when using Spotify Connect (obviously with the same - free - account). Doesn't this prove that this is not a server-side feature?
> 
> I've tried using spotX to cast to a Google Home speaker and it doesn't work for me... but that was a while ago.
> 
> Also https://spotx-official.github.io/spotx-docs/faq/Windows#i-get-ads-when-i-use-spotify-connect-airplay-etc-why

Don't know about Google Home Speakers, Connect works - with no ads whatsoever - with Amazon Echo when using xManager and SpotX...

**Comment by yodaluca23** [comment]
> Don't know about Google Home Speakers, Connect works - with no ads whatsoever - with Amazon Echo when using xManager and SpotX...

I just got home to test it, I have been playing music on my Google Home speakers group through SpotX and it's been working fine no ads and unlimited skip so yeah it's definitely possible...

Also, the last time I checked EeveeSpotify, you could do your six skips disconnect from the Spotify connect and then reconnect and you get six more skips. I'm thinking maybe what SpotX does is it just sends whatever API request that is and is able to get effectively unlimited skips. Though for ads, I have no idea. Maybe it works kind of the same way. Or I could be completely wrong and it has nothing to do with this.

**Comment by yodaluca23** [comment]
> Also, the last time I checked EeveeSpotify, you could do your six skips disconnect from the Spotify connect and then reconnect and you get six more skips. I'm thinking maybe what SpotX does is it just sends whatever API request that is and is able to get effectively unlimited skips. Though for ads, I have no idea. Maybe it works kind of the same way. Or I could be completely wrong and it has nothing to do with this.

It might also just be the nature that spotX patches the Spotify XPUI files instead of offline.bnk. Might allow it to bypass more things... meaning that it would not be practically feasible to add this functionality to EeveeSpotify...
