### ISSUE TITLE
[BUG] Local file lyrics

### ISSUE THREAD

**Issue by ElliotCHEN37** [whoeevee/EeveeSpotify#418]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

Lyric is available on Musixmatch, but EeveeSpotify didn't use it. 

![IMG_3901](https://github.com/user-attachments/assets/966782de-355e-4acd-8764-5e570c56cecd)
![IMG_3902](https://github.com/user-attachments/assets/129e8a94-638d-47d6-bade-1ffccbbbbc5d)
![IMG_3900](https://github.com/user-attachments/assets/97b2ec5e-d0e6-427b-8a4f-4511f950f992)

**Comment by whoeevee** [comment]
its a specific song issue
