### ISSUE TITLE
Play desired songs not working

### ISSUE THREAD

**Issue by xelahot** [whoeevee/EeveeSpotify#421]
I'm using release 4.9 of EeveeSpotify along with Spotify 8.9.68. The tweak worked fine for like a month. But now, after playing some songs, it wont let play the song I select (it plays and random song in the album just like when you don't have premium). I can still queue the song and play next to kinda bypass this issue but the main purpose of the tweak seem not to be working anymore. Maybe automating these steps would be a good workaround: 1 - queuing the desired song 2 - making it on top of the queue 3 - skipping the currently playing song (would make the desired song play instantly). Or maybe just try to fix the tweak.

**Comment by yodaluca23** [comment]
Did you try the reset data and override configuration options?

**Comment by xelahot** [comment]
I didnt know about this option. It seems to work again already today though. I enabled it in case it prevents this from happening again. You can close the issue, ill open another one if it happens again.

**Comment by srinivasb99** [comment]
> I'm using release 4.9 of EeveeSpotify along with Spotify 8.9.68. The tweak worked fine for like a month. But now, after playing some songs, it wont let play the song I select (it plays and random song in the album just like when you don't have premium). I can still queue the song and play next to kinda bypass this issue but the main purpose of the tweak seem not to be working anymore. Maybe automating these steps would be a good workaround: 1 - queuing the desired song 2 - making it on top of the queue 3 - skipping the currently playing song (would make the desired song play instantly). Or maybe just try to fix the tweak.

Please update to v5.3 has latest updates
