### ISSUE TITLE
[Bug] Sidestore refresh

### ISSUE THREAD

**Issue by xhfpsxm** [whoeevee/EeveeSpotify#427]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

I installed eeveespotify on sidestore. This is fine right after installation, but when I refresh, something's up. The problem I'm having is that I'd like to have YTLitePlus installed along with eeveespotify, but sidestore takes up 2 app IDs, YTLitePlus takes 3 app IDs. So when I install eeveespotify, it says that it requires 6 app IDs and I only have 5 remaining. What should I do?

**Comment by ElliotCHEN37** [comment]
Just remove the plugins
