### ISSUE TITLE
[Bug] New update got rid of "hamburger" icon in settings 

### ISSUE THREAD

**Issue by LoganWolfie** [whoeevee/EeveeSpotify#428]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

Updated to v5.3 from being on v5.2 and now it's just gone. Unless I somehow hid it and theres a way to bring it back, but if I did I still have no idea how to bring it back.
![image](https://github.com/user-attachments/assets/321e2cdc-a67c-46c6-8a37-4996b6445c4b)
![image](https://github.com/user-attachments/assets/b08839b2-ff24-41b7-9ec8-a3b9be021189)

**Comment by yodaluca23** [comment]
What hamburger icon?

**Comment by LoganWolfie** [comment]
> What hamburger icon?

There was one in the top right was there not?
You clicked on it and there was a bunch of options to turn on or off specific settings made for eevee

**Comment by yodaluca23** [comment]
> There was one in the top right was there not?
> 
> You clicked on it and there was a bunch of options to turn on or off specific settings made for eevee 
> 
> 
> 
> It was on SPOTILIFE too not sure if that might have just added it somehow before I updated. 

Ah, you're referring to Sposify, a different tweak. Not apart of EeveeSpotify.

**Comment by LoganWolfie** [comment]
> > There was one in the top right was there not?
> > 
> > You clicked on it and there was a bunch of options to turn on or off specific settings made for eevee 
> > 
> > 
> > 
> > It was on SPOTILIFE too not sure if that might have just added it somehow before I updated. 
> 
> Ah, you're referring to Sposify, a different tweak. Not apart of EeveeSpotify.

Ohh alright that's weird idk why it was still there then even after I installed eevee.
