### ISSUE TITLE
[Bug] CarPlay APP without Trollstore

### ISSUE THREAD

**Issue by ta20d** [whoeevee/EeveeSpotify#429]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

Will be ever possible to use CarPlay app without the trollstore injection ?

**Comment by ElliotCHEN37** [comment]
A paid dev account (cert)
