### ISSUE TITLE
[Bug] Changing the lyrics does not trigger the change on the current song

### ISSUE THREAD

**Issue by officiallor** [whoeevee/EeveeSpotify#434]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.
It's just a nice to have and very **minor**. To see the update you need to switch song or reopen the app.

Steps to reproduce:
1. Play a song with selected Musixmatch as lyrics source
2. Verify that the lyrics are displayed normally
3. Change the lyrics source to something else
4. Go to the song and see that the lyrics are not updated to the currently selected source

**Comment by asdfzxcvbn** [comment]
how often are you changing the lyrics source? 😭

**Comment by officiallor** [comment]
It's not how often do I change lyrics. It's a nice to have as I said, if it's easy to implement it.
