### ISSUE TITLE
local files

### ISSUE THREAD

**Issue by Kassra1** [whoeevee/EeveeSpotify#435]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

Someone help. I need my local files and normally I would just add my downloaded songs to my Spotify file on my files app(ios) but with eevee there’s no Spotify file or anything like that so how do I get my local files into the app

**Comment by ElliotCHEN37** [comment]
Check if their formats are MP3 and turn on the Local files in settings

**Comment by Diowboss** [comment]
Use iTunes to add it to your music library, then in Spotify settings under “local files” turn on the setting. And boom you have local files

**Comment by Kassra1** [comment]
> Use iTunes to add it to your music library, then in Spotify settings under “local files” turn on the setting. And boom you have local files
Where do I find my music library

**Comment by ElliotCHEN37** [comment]
![ebvuls4r hi0](https://github.com/user-attachments/assets/73fb6cf8-db75-48db-a652-a7a78ed18eae)
![tqj5hvye jpf](https://github.com/user-attachments/assets/d50c8771-5b37-4155-ab0c-4bb1e70c981e)
![kzfo40et axj](https://github.com/user-attachments/assets/04d52bbc-3788-4625-a719-b19275ab526b)

**Comment by Kassra1** [comment]
> ![ebvuls4r hi0](https://github.com/user-attachments/assets/73fb6cf8-db75-48db-a652-a7a78ed18eae)
> 
> ![tqj5hvye jpf](https://github.com/user-attachments/assets/d50c8771-5b37-4155-ab0c-4bb1e70c981e)
> 
> ![kzfo40et axj](https://github.com/user-attachments/assets/04d52bbc-3788-4625-a719-b19275ab526b)
> 
> 

I think I love you thank you so much have a good day
