### ISSUE TITLE
Allow to use the Download button to transfer/share custom music file from other devices

### ISSUE THREAD

**Issue by Kutez** [whoeevee/EeveeSpotify#437]
Hello I want to have the download useable to transfer my custom music file from my laptop to my phone. If you didn't know, Spotify have a feature that allow you to transfer your custom music file from other devices when they are connecting to the same WiFi, this can be done by pressing the Download button. I have already used this on EeveeSpotify and it worked flawlessly(achievable by long pressing the playlist then press Download, it is now patched).

So can you do it? Maybe as an extra options to choose for the warning when pressing the Download button? Thank you.

**Comment by whoeevee** [comment]
should be fixed in version 5.5, test it

**Comment by RabbyDevs** [comment]
Tested it, this wasn't fixed with swift 5.5. The native downloading warning pops up everytime I try.

**Comment by Kutez** [comment]
Tested 5.5, same here

**Comment by whoeevee** [comment]
unfortunately i can’t even test it
how the button is supposed to work? can you send screenshots where it’s located or something

**Comment by Kutez** [comment]
This is not a bug or anything, just my request to allow to use the download button
![5319E688-34BA-498D-8CE8-8309FBE4A69B](https://github.com/user-attachments/assets/bb9796dc-8064-4bd2-a606-370051f706f2)
![5B2551A0-87BB-4507-8AB3-B29D3A4F8A93](https://github.com/user-attachments/assets/8dff8ab1-7290-4024-84fc-330be9fdfee5)
After clicking it, the local file should download to your phone, but it is no blocked because of your warning.

**Comment by BB4LIFE** [comment]
I don't know if this helps, but I have used this feature in the past. I believe if you have a playlist made up entirely of local files from your PC you can "download" them to your phone (i.e., when u click the button it transfers the files over Wi-Fi) and stores them in Spotify's cache.

**Comment by Kutez** [comment]
> I don't know if this helps, but I have used this feature in the past. I believe if you have a playlist made up entirely of local files from your PC you can "download" them to your phone (i.e., when u click the button it transfers the files over Wi-Fi) and stores them in Spotify's cache.

Tried it, and it still the same, when I press the Download button, the warning appear, preventing it from dowloading.

**Comment by whoeevee** [comment]
> I don't know if this helps, but I have used this feature in the past. I believe if you have a playlist made up entirely of local files from your PC you can "download" them to your phone (i.e., when u click the button it transfers the files over Wi-Fi) and stores them in Spotify's cache.

thanks for clarification
should be really fixed with https://github.com/whoeevee/EeveeSpotify/commit/e0fe39d71760f2504aff816c8a58f81bcd214e7a, you can test the debs here: https://github.com/whoeevee/EeveeSpotify/actions/runs/11276615753

**Comment by BB4LIFE** [comment]
> > I don't know if this helps, but I have used this feature in the past. I believe if you have a playlist made up entirely of local files from your PC you can "download" them to your phone (i.e., when u click the button it transfers the files over Wi-Fi) and stores them in Spotify's cache.
> 
> thanks for clarification should be really fixed with [e0fe39d](https://github.com/whoeevee/EeveeSpotify/commit/e0fe39d71760f2504aff816c8a58f81bcd214e7a), you can test the debs here: https://github.com/whoeevee/EeveeSpotify/actions/runs/11276615753

Just tested and can confirm it is working
