### ISSUE TITLE
App to Watch

### ISSUE THREAD

**Issue by phxnkforcce** [whoeevee/EeveeSpotify#438]
Is there a way to make EeveeSpotify on AppleWatch? 🤔

**Comment by yodaluca23** [comment]
The Apple Watch app is a separate .ipa file the only way we'd be able to decrypt it would be if we have a watchOS jailbreak, which the most advanced one we ever got just allowed for basic SSH access and was like way back with the series 3... additionally, there's no easy way for users to sideload to Apple Watch
