### ISSUE TITLE
[Bug] Shazam not discovering the EveeSpotify sideloaded app, thus not able to open Shazamed songs into Spotify

### ISSUE THREAD

**Issue by giohb777** [whoeevee/EeveeSpotify#439]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

Not able to open the Spotify app from Shazam, it redirects me to the open.spotify.com website only

**Comment by ElliotCHEN37** [comment]
Enable extension or sideload with a paid dev cert or using troll store should solve this

**Comment by giohb777** [comment]
> Enable extension or sideload with a paid dev cert or using troll store should solve this

The app is sideloaded with a Paid dev cert; which Extension are you referring to?

**Comment by ElliotCHEN37** [comment]
> > Enable extension or sideload with a paid dev cert or using troll store should solve this
> 
> The app is sideloaded with a Paid dev cert; which Extension are you referring to?

OpenSpotifySafari

**Comment by giohb777** [comment]
> > > Enable extension or sideload with a paid dev cert or using troll store should solve this
> > 
> > 
> > The app is sideloaded with a Paid dev cert; which Extension are you referring to?
> 
> OpenSpotifySafari, which is contained by default with the official release from telegram or github

Thank you! I was a using a different IPA that did not have the extension contained.
