### ISSUE TITLE
NOT REALLY AN ISSUE BUT JUST A QUESTION--PLEASE READ FIRST \/

### ISSUE THREAD

**Issue by KeyboardChampion** [whoeevee/EeveeSpotify#45]
I'm sorry as posting this as an issue, but its a very important question- Is all of this client sided? Can Spotify see that something is up if someone uses this? Or are they safe?

**Comment by asdfzxcvbn** [comment]
all modifications are client sided obviously --

as for whether spotify can see if you use this, probably. they should at least be able to see that a free account is making requests that surpass the free limit ¯\\\_(ツ)\_/¯

**Comment by asdfzxcvbn** [comment]
no lol, they're not going to waste money on a legal battle over a $10 subscription or something

nothing has ever happened to anyone using spotilife. you'll be fine.
