### ISSUE TITLE
[Bug] Unable to choose any song from a playlist/album to play

### ISSUE THREAD

**Issue by rattpack2066** [whoeevee/EeveeSpotify#454]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

I’m having this issue which prevents me from choosing any song from a playlist/album and reverts back to the beginning track.
The app also keeps reminding me that songs are played in random orders before playing any song, please help

https://github.com/user-attachments/assets/b73c5613-0d44-4806-b576-3b6d07acb86d

**Comment by whoeevee** [comment]
https://github.com/whoeevee/EeveeSpotify/issues/454
