### ISSUE TITLE
[Feature Req] removal of the Fan Support part from Artists page

### ISSUE THREAD

**Issue by gototheskinny** [whoeevee/EeveeSpotify#457]
Could you please remove the fan support section from the Artists page in the app, or make it optional to move or remove? It’s currently placed at the top of the page, which makes it inconvenient and a bit annoying. I’d appreciate it if this could be adjusted.

Screenshots:

<details>
  <summary>Example 1</summary>
  
![image](https://github.com/user-attachments/assets/d2194293-91fb-4af8-a393-08b0442a1df2)
  
</details>

<details>
  <summary>2</summary>
  
 ![image](https://github.com/user-attachments/assets/e82f4e97-43c9-4d0c-b2a2-8d4394c41090)
  
</details>

**Comment by srinivasb99** [comment]
> Could you please remove the fan support section from the Artists page in the app, or make it optional to move or remove? It’s currently placed at the top of the page, which makes it inconvenient and a bit annoying. I’d appreciate it if this could be adjusted.
> 
> Screenshots:
> 
> <details>
>   <summary>Example 1</summary>
>   
> ![image](https://github.com/user-attachments/assets/d2194293-91fb-4af8-a393-08b0442a1df2)
>   
> </details>
> 
> <details>
>   <summary>2</summary>
>   
>  ![image](https://github.com/user-attachments/assets/e82f4e97-43c9-4d0c-b2a2-8d4394c41090)
>   
> </details>

No it's a native Spotify feature contact Spotify if you have any issues

**Comment by asdfzxcvbn** [comment]
> > Could you please remove the fan support section from the Artists page in the app, or make it optional to move or remove? It’s currently placed at the top of the page, which makes it inconvenient and a bit annoying. I’d appreciate it if this could be adjusted.
> > Screenshots:
> > 
> >   Example 1
> > ![image](https://private-user-images.githubusercontent.com/51786709/376243169-d2194293-91fb-4af8-a393-08b0442a1df2.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5MjMxNjMsIm5iZiI6MTcyODkyMjg2MywicGF0aCI6Ii81MTc4NjcwOS8zNzYyNDMxNjktZDIxOTQyOTMtOTFmYi00YWY4LWEzOTMtMDhiMDQ0MmExZGYyLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNFQxNjIxMDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZGRkYzVjNTNiNzcwYWYzYWY4MTE4ZTAzN2E1ZjZiOTFhZjdkYmU1NzFlM2M0NDIxMzExZDI0MDk0ZDNkZDMyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.izU1dXosyALpvOJrDv56L6pH2g9ZcBrsuTmezknaAQ8)
> > 
> > 
> >   2
> > ![image](https://private-user-images.githubusercontent.com/51786709/376243125-e82f4e97-43c9-4d0c-b2a2-8d4394c41090.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5MjMxNjMsIm5iZiI6MTcyODkyMjg2MywicGF0aCI6Ii81MTc4NjcwOS8zNzYyNDMxMjUtZTgyZjRlOTctNDNjOS00ZDBjLWIyYTItOGQ0Mzk0YzQxMDkwLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNFQxNjIxMDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MTYzMGQ1MWJkN2RlYmRiNjMxNTcyNmE4Y2NlM2ZmZWQyNzY0NzljMjVjNThlZWQwNTQyNzhiNzYzNWIzM2U1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.jRMVXQ7W_5Ek0LQb9FBG3C-bwxKqMELoiMMHHInEQJY)
> 
> No it's a native Spotify feature contact Spotify if you have any issues

lol what

**Comment by gototheskinny** [comment]
> > Could you please remove the fan support section from the Artists page in the app, or make it optional to move or remove? It’s currently placed at the top of the page, which makes it inconvenient and a bit annoying. I’d appreciate it if this could be adjusted.
> > 
> > Screenshots:
> > 
> > <details>
> >   <summary>Example 1</summary>
> >   
> > ![image](https://github.com/user-attachments/assets/d2194293-91fb-4af8-a393-08b0442a1df2)
> >   
> > </details>
> > 
> > <details>
> >   <summary>2</summary>
> >   
> >  ![image](https://github.com/user-attachments/assets/e82f4e97-43c9-4d0c-b2a2-8d4394c41090)
> >   
> > </details>
> 
> No it's a native Spotify feature contact Spotify if you have any issues 

Lyrics doesn't have translations in the native version too? It's not that much to ask from the devs IMO, If they wanna add this they can.

**Comment by yodaluca23** [comment]
> Lyrics doesn't have translations in the native version too? 

It does? Where do you think they got it from? They're just hooking it, and forcing it to appear, then intercepting it and overriding it...

> It's not that much to ask from the devs IMO, If they wanna add this they can.

You're welcome to add it and PR it 🙂.

**Comment by gototheskinny** [comment]
> > Lyrics doesn't have translations in the native version too? 
> 
> It does? Where do you think they got it from? They're just hooking it, and forcing it to appear, then intercepting it and overriding it...
> 
> > It's not that much to ask from the devs IMO, If they wanna add this they can.
> 
> You're welcome to add it and PR it 🙂.
> 

Musixmatch has that feature but Spotify natively doesn't have. And adding that feature in to the Spotify app is super convenient. This suggestion would add convenience too, especially  for small screen devices like ip se and mini models.

**Comment by yodaluca23** [comment]
> Musixmatch has that feature but Spotify natively doesn't have.

Yes it literally does! It's a premium only feature (which is why they needed a Premium account to get it working for us), and in testing so not everyone has it, but EeveeSpotify most certainly is not adding it, it's simply hooking and intercepting the Native Spotify feature!

https://community.spotify.com/t5/Android/Lyrics-translation/td-p/5568997

https://www.reddit.com/r/AppleMusic/comments/106h52q

**Comment by gototheskinny** [comment]
> > Musixmatch has that feature but Spotify natively doesn't have.
> 
> Yes it literally does! It's a premium only feature (which is why they needed a Premium account to get it working for us), and in testing so not everyone has it, but EeveeSpotify most certainly is not adding it, it's simply hooking and intercepting the Native Spotify feature!
> 
> https://community.spotify.com/t5/Android/Lyrics-translation/td-p/5568997
> 
> https://www.reddit.com/r/AppleMusic/comments/106h52q 

OK obviously i didn't tried with premium(with free acc I checked if it's a recent feature). I guess I underestimated Spotify 😄 . All I'm saying is I hope the devs consider adding this tweak.

**Comment by ElliotCHEN37** [comment]
> > > Could you please remove the fan support section from the Artists page in the app, or make it optional to move or remove? It’s currently placed at the top of the page, which makes it inconvenient and a bit annoying. I’d appreciate it if this could be adjusted.
> > > 
> > > Screenshots:
> > > 
> > > <details>
> > >   <summary>Example 1</summary>
> > >   
> > > ![image](https://github.com/user-attachments/assets/d2194293-91fb-4af8-a393-08b0442a1df2)
> > >   
> > > </details>
> > > 
> > > <details>
> > >   <summary>2</summary>
> > >   
> > >  ![image](https://github.com/user-attachments/assets/e82f4e97-43c9-4d0c-b2a2-8d4394c41090)
> > >   
> > > </details>
> > 
> > No it's a native Spotify feature contact Spotify if you have any issues 
> 
> Lyrics doesn't have translations in the native version too? It's not that much to ask from the devs IMO, If they wanna add this they can.

Nope, lyrics translations were native function

**Comment by asdfzxcvbn** [comment]
> just don’t look
