### ISSUE TITLE
[Feature Request] Carplay Integration

### ISSUE THREAD

**Issue by barbonzz** [whoeevee/EeveeSpotify#458]
Could you make it so that Carplay detects the app like normal spotify? i can already listen to playlists in my car but i need to start them on my phone and can't change them while driving

**Comment by srinivasb99** [comment]
> Could you make it so that Carplay detects the app like normal spotify? i can already listen to playlists in my car but i need to start them on my phone and can't change them while driving

Won't work unless you have trollstore. This requires iOS 14-17.0 (7.1 and higher will not work)
