### ISSUE TITLE
[Suggestions]Please add version to ipa name

### ISSUE THREAD

**Issue by Joshua-18** [whoeevee/EeveeSpotify#46]
Please add what version of EeveeSporify you’re using for the ipa, currently it is very confusing what version you’re releasing with the ipa. 
Also maybe add a github actions to build the tweak from an ipa? take a look at how [YTLITEPLUS](https://github.com/YTLitePlus/YTLitePlus/tree/main/.github) does this.

**Comment by asdfzxcvbn** [comment]
> Please add what version of EeveeSporify you’re using for the ipa, currently it is very confusing what version you’re releasing with the ipa. 

this is a good idea, cc @whoeevee 

> Also maybe add a github actions to build the tweak from an ipa? take a look at how [YTLITEPLUS](https://github.com/YTLitePlus/YTLitePlus/tree/main/.github) does this. 

no reason to. the ipa is automatically updated on the EeveeSpotify IPAs telegram channel (use telegram global search), and they should be updated on github soon after they are released on telegram

**Comment by whoeevee** [comment]
> this is a good idea, cc @whoeevee

EeveeSporify version will be added in future releases
