### ISSUE TITLE
Instrumental music lyric box

### ISSUE THREAD

**Issue by ElliotCHEN37** [whoeevee/EeveeSpotify#460]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

Can you make the share button and full-screen button hidden when detecting playing instrumental music
![IMG_4110](https://github.com/user-attachments/assets/b14f90ca-7c4a-484c-8d40-1cd4279e8677)

**Comment by Richard-NDC** [comment]
The tweak just overwrites the lyrics box, so I think it’s not possible at all. Not like the translate button it's optional
