### ISSUE TITLE
-FEATURE REQUEST- Is there any way to have Spotify videos on app?

### ISSUE THREAD

**Issue by Steppen-wolf** [whoeevee/EeveeSpotify#461]

**Comment by ElliotCHEN37** [comment]
Do you mean Canvas?
If yes, just go to settings

**Comment by Steppen-wolf** [comment]
I don't mean canvas.

With premium version, you can watch video of certain songs like YouTube although the quality is not the best.

Is it possible to integrate this option into Eeveespotify?

**Comment by Richard-NDC** [comment]
> I don't mean canvas.
> 
> With premium version, you can watch video of certain songs like YouTube although the quality is not the best.
> 
> Is it possible to integrate this option into Eeveespotify?

what's that bro i'm a premium user

**Comment by ElliotCHEN37** [comment]
screenshot plz

**Comment by aviwad** [comment]
It's a buggy feature and probably locked server side just like high quality is. you're not missing out on much and it's not even available in some regions
