### ISSUE TITLE
[Bug] Tweak isn't working for older spotify app version like 8.8.2 

### ISSUE THREAD

**Issue by Cimmerian-Iter** [whoeevee/EeveeSpotify#463]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

I am using an older Spotify version (because I'm on iOS14.8.1 and version below 8.9 have great support for spotify tweaks like ablaze and such) and the app straight up crash when launching. I can't even manage to get a crash log in CR4SHED

I know this might not be the priority but it would be really cool if support could be added to this version.

Thank you

**Comment by ElliotCHEN37** [comment]
this tweak is designed for the latest version, not old ones. Use spotilife for old versions

**Comment by Cimmerian-Iter** [comment]
I would love to use spotilife if it was indeed working. The lowest spotify app version on which spotilife successfully work (without premium access being lost after like 3 days) is 8.5.96, which is kinda too low and doesn't have the feature to share library music in a separate tab

**Comment by asdfzxcvbn** [comment]
> EeveeSpotify only supports the latest App Store versions and the latest available version for iOS 14 (8.9.8)

support for lower versions won't be added.
