### ISSUE TITLE
Album Art not showing on Local Files (.m4a files)

### ISSUE THREAD

**Issue by samuelawachie** [whoeevee/EeveeSpotify#464]
I have a meticulously maintained library when it comes to tags. Everything is in order and complete, and I go to great effort making sure it's all done well. 
In all my music apps on mobile or desktop, they show up well (Foobar, Neutron, Spotify desktop,Deadbeef, iTunes, etc)
They also showed up well on the old sideload Spotify app I used to use v 8.6.94.351 but in Eevee only about 40% of the files show the album artwork (Front covers only).
Is this the same for everyone? I just have ignored this, because the songs do play and I don't usually stare at the screen when playing music but it makes the Local Library look terrible and disjointed

**Comment by JackPlaysGames0510** [comment]
Not a bug if you download music with no album art work then it won’t show on Spotify

**Comment by samuelawachie** [comment]
> Not a bug if you download music with no album art work then it won’t show on Spotify

>
These are not downloaded files. These are my own music files that have been imported to Spotify with already tagged album covers.

**Comment by yodaluca23** [comment]
Does this happen with the Spotify app from the AppStore?

**Comment by samuelawachie** [comment]
> Does this happen with the Spotify app from the AppStore?

>
I hope someone else can experiment and answer this coz for some personal reasons I can't install the un-modded Spotify at the moment..

**Comment by ElliotCHEN37** [comment]
Send me the music files and I will test it

**Comment by JackPlaysGames0510** [comment]
Make the mp3 them self had art work sometimes the download messes up and doesn’t have it if they do then it’s a Spotify thing then and I recommend removing it and adding it back in

**Comment by whoeevee** [comment]
EeveeSpotify shouldn’t have affected this in any way

**Comment by ElliotCHEN37** [comment]
Have you ever modified or deleted some files? If yes, try to toggle the local file function in settings

**Comment by samuelawachie** [comment]
> EeveeSpotify shouldn’t have affected this in any way

>
After investigations, I have discovered why this is happening. 
All the files that are .mp3 show album art. The other files are .m4a which are not showing the album art. 
The .m4a is a better codec in my opinion by far compared to mp3, so this is a shame. 
This also indicates it'll be the same with the normal un-modded Spotify. 
I assume it'll also be the same with not just AAC files but OPUS(ogg) and other high quality audio formats. 

I wonder if a fix can be made...

**Comment by asdfzxcvbn** [comment]
> This also indicates it'll be the same with the normal un-modded Spotify.

not an eeveespotify issue
