### ISSUE TITLE
Problem with language Italian

### ISSUE THREAD

**Issue by Filic308** [whoeevee/EeveeSpotify#465]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

In italian language, the text “Settings” still “Settings”, but in italian is “Impostazioni” not “Settings”.
![IMG_6529](https://github.com/user-attachments/assets/99a1e5ac-43ed-4e34-83fa-9466fd223e12)

**Comment by asdfzxcvbn** [comment]
is this in the eeveespotify settings screen or normal spotify settings

**Comment by Filic308** [comment]
only in eeveespotify settings

**Comment by whoeevee** [comment]
on EeveeSpotify settings page, the title “EeveeSpotify” is displayed, while the screenshot you attached shows the Spotify settings page, which is not related to the tweak

moreover, i’ve just set the language to italian and can confirm that “Settings” is the default Spotify localization, so there is nothing wrong
