### ISSUE TITLE
[Bug] Musixmatch Token broke out of nowhere 

### ISSUE THREAD

**Issue by srinivasb99** [whoeevee/EeveeSpotify#466]
Keep getting error saying no song found.

![image](https://github.com/user-attachments/assets/2575d3e2-5438-4219-aea2-5aa543fad42e)

![image](https://github.com/user-attachments/assets/04c755c2-e7f8-4959-8411-2abcee909453)

**Comment by srinivasb99** [comment]
Figured out the issue had to replace the Musixmatch token, although I tried downloading the official app from the App Store and using the token from that and it didn't work. I had to use a tweaked Musixmatch Version 7.10.2
Build 2022122100. The version 7.11 didn't work.

**Comment by officiallor** [comment]
It wasn't the musixmatch token. It happened to me too. I tried to find the reason but couldn't. In the end, after a few hours it worked without even changing the token.
