### ISSUE TITLE
[버그]

### ISSUE THREAD

**Issue by pyooooooo** [whoeevee/EeveeSpotify#467]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

Hello, at some point, when I try to listen to a certain song, I hear that the song is not available, and I see a lock mark. I'm told to sign up for a premium to fix the phenomenon, is this a bug or is it an unsolvable problem? For your information, I'm using a Korean account

**Comment by whoeevee** [comment]
common issue, see https://github.com/whoeevee/EeveeSpotify/blob/swift/common_issues.md#unable-to-play-songs

**Comment by pyooooooo** [comment]
> 일반적인 문제, [https://github.com/whoeevee/EeveeSpotify/blob/swift/common_issues.md#unable-to-play-songs ](https://github.com/whoeevee/EeveeSpotify/blob/swift/common_issues.md#unable-to-play-songs)참조

I can't solve it even though I used that method
