### ISSUE TITLE
(question) will there ever be a web version?

### ISSUE THREAD

**Issue by lanxiangcai** [whoeevee/EeveeSpotify#468]
will there ever be a web version? something like a chrome extension? i looked at how it works, and i think it could work as spotify probably fetches the same user file on every platform, but i'm also probably wrong.

**Comment by yodaluca23** [comment]
It'd be better to use the App along with [SpotX](https://github.com/SpotX-Official/SpotX) or [BlockTheSpot](https://github.com/mrpond/BlockTheSpot) (Windows). Or [SpotX-Bash](https://github.com/SpotX-Official/SpotX-Bash) (MacOS/Linux).

But if you really want to use the website you can use [this](https://github.com/Isaaker/Spotify-AdsList) Adblock list.

**Comment by lanxiangcai** [comment]
i'm not looking for an ad blocker, i'm looking for premium. thanks for your help either way
