### ISSUE TITLE
[Feature Request] Dark "Now Playing" Windows (Like in Spotilife)

### ISSUE THREAD

**Issue by Flex4249** [whoeevee/EeveeSpotify#469]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

Spotilife has a feature where you can make the background of the "Now Playing" window completely black, which for me is a lot easier on the eyes and I like the look of it. To turn it on in Spotilife, just go into the Spotilife settings and turn on "Dark Background in Now Playing" 

Spotilife IPA used: SpotilifeC

EeveeSpotify IPA used: Whatever the latest one was as of today

**Comment by asdfzxcvbn** [comment]
are you referring to "Blackout Mode" in sposify settings?

**Comment by Flex4249** [comment]
I'm not sure what that is, but if you check SpotilifeC (the IPA I used) it
should have a feature in the Spotilife settings where you can have a black
now playing screen, but still be able to see all the song details
