### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by JackPlaysGames0510** [whoeevee/EeveeSpotify#471]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

Sometimes Spotify will forever load and I don’t know why and the only way to fix it is to delete the app and open it up again

**Comment by whoeevee** [comment]
crazy
