### ISSUE TITLE
[Bug] Why doesn't it support Apple Carplay in the car?

### ISSUE THREAD

**Issue by Achordchan** [whoeevee/EeveeSpotify#477]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [ ] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

Why doesn't it support Apple Carplay in the car?

**Comment by wlxxd** [comment]
Duplicate #458 
CarPlay only works with a certain that has CarPlay Entitlements.
