### ISSUE TITLE
[Bug] Cannot remove songs from the queue.

### ISSUE THREAD

**Issue by TeaselUwU** [whoeevee/EeveeSpotify#478]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

Like the title says, I cannot remove songs from the queue whenever I want to play certain songs on albums. I cannot confirm if it’s like that on normal Spotify, if someone could test for me and confirm if it works or doesn’t, I’m sure it would help the developers. The problem started with the latest version(5.6), previous versions were working fine.

**Comment by wlxxd** [comment]
Quote: „ On mobile, after you open the queue you can tap on the circles on the left hand side to select songs and then you can choose to remove them.“

https://community.spotify.com/t5/Your-Library/Delete-a-single-song-from-queue/td-p/5593885

**Comment by TeaselUwU** [comment]
> Quote: „ On mobile, after you open the queue you can tap on the circles on the left hand side to select songs and then you can choose to remove them.“
> 
> https://community.spotify.com/t5/Your-Library/Delete-a-single-song-from-queue/td-p/5593885

I am aware of how it works, but clicking the ‘Remove’ button does nothing. On previous versions it would actually removed the selected songs, but now it just does the click animation and that’s it.

**Comment by TeaselUwU** [comment]
All fine on EeveeSpotify 5.7!
