### ISSUE TITLE
Error when clicking on video player

### ISSUE THREAD

**Issue by Diowboss** [whoeevee/EeveeSpotify#48]
Unable to apply tweak: Error
Domain=NSCocoaErrorDomain Code=513 "You don't have permission to save the file "offline.bnk" in the folder "PersistentCache"."
UserInfo={NSFilePath=/var/mobile/Containers/ Data/Application/5920C9BE-594A-4436-B2BE-5D812E3EDF13/Documents/Data/
Application/2DD715B3-5B31-46FB-9F8C-
E339278185AC/Library/Application Support/
PersistentCache/offline.bnk,
NSUnderlyingError=0×28049c0f0 {Error
Domain=NSPOSIXErrorDomain Code=13
"Permission denied"}}

**Comment by whoeevee** [comment]
try to restart the app

**Comment by asdfzxcvbn** [comment]
uninstall and reinstall
