### ISSUE TITLE
[Feature Request] Auto refresh spotify 2 weeks period for travellers

### ISSUE THREAD

**Issue by nyakokitsu** [whoeevee/EeveeSpotify#481]
Hi, I use Spotify from a country where it is not officially available and I can't pay for a subscription, it would be very useful to add a setting to Eevee that allows proxying authorization requests once every 2 weeks via specified proxy.

**Comment by ElliotCHEN37** [comment]
Make sure Do Not Patch Premium is disabled so Spotify thinks you have a subscription so you won't get this popup

**Comment by whoeevee** [comment]
nice suggestion, but it won't be implemented
it covers quite rare cases, and it’s better to connect with a proxy if you have one. you can use it constantly, or from time to time, for accessing spotify, or set up split-tunneling to spotify endpoints, etc
