### ISSUE TITLE
songs play in a random order

### ISSUE THREAD

**Issue by mahmoudgamal78** [whoeevee/EeveeSpotify#484]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

why i can't play any song any time ?

**Comment by ElliotCHEN37** [comment]
Just read Common issues

**Comment by mahmoudgamal78** [comment]
> Just read Common issues

okay , thanks
