### ISSUE TITLE
crashing when launching

### ISSUE THREAD

**Issue by pengorr** [whoeevee/EeveeSpotify#49]
i installed it through trollstore on ios 16.3 iphone 11 but it just crashes everytime i try to launch it. i already tried swtiching user registration and reinstalling it multiple times

**Comment by asdfzxcvbn** [comment]
are you jailbroken?

**Comment by pengorr** [comment]
yes

**Comment by asdfzxcvbn** [comment]
try disabling tweak injection with choicy

**Comment by pengorr** [comment]
yeah it worked thx
