### ISSUE TITLE
AI DJ & AI Playlist Support

### ISSUE THREAD

**Issue by srinivasb99** [whoeevee/EeveeSpotify#490]
Idk if these are server-sided features or not, but it would nice to see them in this tweak.

**Comment by asdfzxcvbn** [comment]
this info is in the readme, and this is a duplicate

**Comment by srinivasb99** [comment]
> this info is in the readme, and this is a duplicate

Actually, it isn't:

Please refrain from opening issues about the following features, as they are server-sided and will NEVER work:

Very High audio quality
Native playlist downloading (you can download podcast episodes though)
Jam (hosting a Spotify Jam and joining it remotely requires Premium; only joining in-person works)

Please update this so people in the future will know

**Comment by asdfzxcvbn** [comment]
thanks
