### ISSUE TITLE
Able to download?

### ISSUE THREAD

**Issue by ghh-jb** [whoeevee/EeveeSpotify#494]
What happened? Now we can download albums?![image](https://github.com/user-attachments/assets/e09fb8c8-6c23-4e2d-914e-d9e9ca9dff2a)

**Comment by ghh-jb** [comment]
Like, it IS downloading...

**Comment by ElliotCHEN37** [comment]
> Nope, just animation

Only downloading the local file is working

**Comment by ghh-jb** [comment]
Ok🤘🏻

**Comment by srinivasb99** [comment]
> > Nope, just animation
> 
> 
> 
> Only downloading the local file is working

What does this mean? Like will be slung actually download?

**Comment by ElliotCHEN37** [comment]
> > > Nope, just animation
> > 
> > 
> > Only downloading the local file is working
> 
> What does this mean? Like will be slung actually download?

nope, just animation, download won't start
