### ISSUE TITLE
I think we need a pinned issue with a list of dupe/don't open/etc. issues cuz many people "don't have" a search bar

### ISSUE THREAD

**Issue by ElliotCHEN37** [whoeevee/EeveeSpotify#495]
I think we need a pinned issue with a list of dupe/don't open/etc. issues cuz many people "don't have" a search bar

**Comment by ElliotCHEN37** [comment]
They don't even read the common issues but ticked "I read it"

**Comment by asdfzxcvbn** [comment]
yeah, we're gonna start blocking people who do that from the repo

**Comment by asdfzxcvbn** [comment]
actually it still wouldnt do anything lol rip
