### ISSUE TITLE
[Improvement] Auto-get or refresh musixmatch token

### ISSUE THREAD

**Issue by ElliotCHEN37** [whoeevee/EeveeSpotify#496]
We can get a user token directly from `https://apic.musixmatch.com/ws/1.1/token.get?app_id=<app id, iphone: mac-ios-v2.0, ipad: mac-ios-ipad-v1.0, (we can even get one for desktop but not need in Eevee lol>`
Can you implement it into the next version? 
Thanks~~~

**Comment by asdfzxcvbn** [comment]
nice

**Comment by ElliotCHEN37** [comment]
ok, i'll try to make it work in a few days

**Comment by ElliotCHEN37** [comment]
it's working now, i'll open a pull request later (maybe 1hour?)

**Comment by asdfzxcvbn** [comment]
> it's working now, i'll open a pull request later (maybe 1hour?)

we don't need a pr, eevee was already going to implement this

**Comment by ElliotCHEN37** [comment]
ummm, ok

**Comment by ElliotCHEN37** [comment]
any update?
