### ISSUE TITLE
[FEATHRE REQUEST] Auto Update Eevee Spotify

### ISSUE THREAD

**Issue by luh-99** [whoeevee/EeveeSpotify#499]
Hey, I was wondering if it was possible to make an auto update. I would like this feature because it would be so useful to not have to go to the GitHub and download the ipa then sideload it. If this is possible I would highly appreciate it. Or you can even do a manual update but inside the app would be useful.

**Comment by asdfzxcvbn** [comment]
nah, eeveespotify updates when spotify updates, which wouldnt be possible to install in-app. nice idea, and updating the tweak in-app is theoretically possible, but for the reason i mentioned it's not very helpful

**Comment by yodaluca23** [comment]
> nah, eeveespotify updates when spotify updates, which wouldnt be possible to install in-app. nice idea, and updating the tweak in-app is theoretically possible, but for the reason i mentioned it's not very helpful

Yeah, you could theoretically do something like what most Discord tweaks do where it fetches the latest stuff from an online server but yeah your. IPA version would very quickly fall out of date...
