### ISSUE TITLE
Can you get rid of this Advertisement popup

### ISSUE THREAD

**Issue by JackPlaysGames0510** [whoeevee/EeveeSpotify#5]
![photo_2024-04-23_16-40-51](https://github.com/whoeevee/EeveeSpotify/assets/48178959/1ea728ee-40e1-468d-b29d-8764ffacf052)

**Comment by asdfzxcvbn** [comment]
do all the other premium features work? it's just that ad that shows up?

**Comment by asdfzxcvbn** [comment]
> yeah it works fine just this

does it keep showing up? or is it random? i don't get any ads at all (on objc experimental version)

**Comment by JackPlaysGames0510** [comment]
all the time for me im in the uk

**Comment by asdfzxcvbn** [comment]
is this fixed with v1.2?

**Comment by JackPlaysGames0510** [comment]
Yea it is thanks
