### ISSUE TITLE
Spotify repeatedly crashing if no action is taken to press 'play' on the song

### ISSUE THREAD

**Issue by wqffi** [whoeevee/EeveeSpotify#50]
After awhile of listening to music with AirPods in (15 Pro Max iOS 17.4.1), the app will crash and if you open, will load and crash/force close again. You have a brief second to unpause the song in order to keep it open otherwise it will crash. Going to try a device restart to fix it

**Comment by Tz4i** [comment]
Exact thing started happening to me like right at this moment did the restart fix?

**Comment by Finealex** [comment]
> After awhile of listening to music with AirPods in (15 Pro Max iOS 17.4.1), the app will crash and if you open, will load and crash/force close again. You have a brief second to unpause the song in order to keep it open otherwise it will crash. Going to try a device restart to fix it

Yea this just started to happen to me

**Comment by Finealex** [comment]
> Exact thing started happening to me like right at this moment did the restart fix?

What I did was after it crashed, reopen it and quickly force close it

**Comment by tyrachi** [comment]
Seems like a lot of regular spotify users are having this issue too according to downdetector.

**Comment by tyrachi** [comment]
> is this resolved? since apparently this was on spotify's part

Seems fine for me now. Occasionally the app reverts back to the free version, but that was regular before.
