### ISSUE TITLE
As pic shows ,this tweaked app won't work anymore

### ISSUE THREAD

**Issue by Fi-tz** [whoeevee/EeveeSpotify#500]
![image](https://github.com/user-attachments/assets/2e862ea1-185d-4334-b451-f8f5872aadd8)

**Comment by asdfzxcvbn** [comment]
https://github.com/whoeevee/EeveeSpotify/blob/swift/common_issues.md

**Comment by Fi-tz** [comment]
Why it is closed as not planned

**Comment by Fi-tz** [comment]
Sorry about the summits,have a nice day bro
