### ISSUE TITLE
[Bug] "Spotify" is no longer available

### ISSUE THREAD

**Issue by MilanObrenovic** [whoeevee/EeveeSpotify#502]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

I tried opening my spotify app and all of a sudden getting the message "Spotify" Is No Longer Available.
I installed EeveeSpotify-5.7-8.9.86.ipa

It worked fine until yesterday (november 3rd).

**Comment by ElliotCHEN37** [comment]
screenshot?

**Comment by yodaluca23** [comment]
Nothing to do with EeveeSpotify, either the certificate you used to sign was revoked, or something alike.
