### ISSUE TITLE
I get this ad pop up again

### ISSUE THREAD

**Issue by JackPlaysGames0510** [whoeevee/EeveeSpotify#51]
![IMG_0653](https://github.com/whoeevee/EeveeSpotify/assets/48178959/8de3b3ee-fcab-497b-b180-ffb363202257)

**Comment by asdfzxcvbn** [comment]
but all other premium features work?

**Comment by yodaluca23** [comment]
yea, that happens for me sometimes, even when all other premium features work, a force close usually fixes it..

**Comment by JackPlaysGames0510** [comment]
This is working fine now
