### ISSUE TITLE
[Bug] Unable to install the latest version of EeveeSpotify

### ISSUE THREAD

**Issue by AntoDipp** [whoeevee/EeveeSpotify#511]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

Error code: The operation couldn’t be completed. Unable to install the app: Siri Intents app extension is present in the WatchKit app com.spotify.client.watchkitapp but there are no Siri Intents in the companion app com.spotify.client.Q39G54T6VH

![IMG_9426](https://github.com/user-attachments/assets/bbb20ede-e865-4dd5-9c82-fa3bbd6a856f)

**Comment by Lorenzoformi2001** [comment]
Same here, I use AltStore but app keep closing himself during installation. A fix might come soon.

**Comment by Ale-su** [comment]
same here with sidestore 0.5.9 nightly

**Comment by srinivasb99** [comment]
![image](https://github.com/user-attachments/assets/30272284-3ae5-443e-8601-263ebf7a15ca)

v5.8 didn't work with Signulous, but worked successfully with ESign +DNS
![image](https://github.com/user-attachments/assets/770d2bd7-b970-4f71-839d-066412d27061)

**Comment by asdfzxcvbn** [comment]
updated the latest release
