### ISSUE TITLE
[request]

### ISSUE THREAD

**Issue by Xsoeazy** [whoeevee/EeveeSpotify#515]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

Hello,
I hope this message finds you well. I'm writing as a user of EeveeSpotify to suggest a potential improvement.
It would be fantastic if you could add a "Skip 10 Seconds" button to the main music player. This feature is already available in the podcast player and would greatly enhance the user experience for music playback as well.
Thank you for considering this suggestion. I'm looking forward to seeing this feature implemented in future updates.

**Comment by asdfzxcvbn** [comment]
Nah
