### ISSUE TITLE
Only for iOS 15? I‘m on iOS 13.6

### ISSUE THREAD

**Issue by r0my** [whoeevee/EeveeSpotify#52]
Hello and big thanks for this project. ♥ 
My iPhone is jailbroken and on iOS 13.6. It it possible, to get a version for lower spotify versions? 

The last version i can dl from AppStore is 8.8.2.511. If you like, i can send you the .ipa, if it helps.

**Comment by tjhooker73ps3** [comment]
I was about to make the same post I actually have 8.8.96 Decrypted

**Comment by asdfzxcvbn** [comment]
injection could be a bit of a challenge currently.. i think most injectors have one issue currently. maybe you could try injecting with sideloadly. just decrypt the ipa and use the deb from releases

**Comment by whoeevee** [comment]
the Objective-C version requires iOS 15, but it's outdated

current Swift version deb, 1.4.1, requires iOS 14. in theory, it might work on iOS 13, but not on arm64e devices (iPhone XS and newer) because you need an older version of Xcode to build arm64e iOS 13 binaries. however, it may work when injected into an IPA. try injecting the latest deb, dev.theos.orion12, and CydiaSubstrate into IPA, and test it

if it doesn't work, either you or I can build an iOS 13 arm64e tweak deb to install with jailbreak

**Comment by r0my** [comment]
Can someone do that?

**Comment by fugegate** [comment]
> Hello and big thanks for this project. ♥ 
> My iPhone is jailbroken and on iOS 13.6. It it possible, to get a version for lower spotify versions? 
> 
> The last version i can dl from AppStore is 8.8.2.511. If you like, i can send you the .ipa, if it helps.



This is a tweak that still works perfectly and is supported for devices from iOS 11 and above : https://appdb.to/details/55b16fca5193c0e7ee8a33156a2f07095f6c6c89

**Comment by r0my** [comment]
> perfectly

Thank you! Can you download it?

**Comment by r0my** [comment]
> > Hello and big thanks for this project. ♥ 
> > My iPhone is jailbroken and on iOS 13.6. It it possible, to get a version for lower spotify versions? 
> > 
> > The last version i can dl from AppStore is 8.8.2.511. If you like, i can send you the .ipa, if it helps.
> 
> 
> 
> This is a tweak that still works perfectly and is supported for devices from iOS 11 and above : https://appdb.to/details/55b16fca5193c0e7ee8a33156a2f07095f6c6c89

Many versions have also worked for me. Until the day when I could no longer play or see full Playlists. Very strange. Even with old versions that worked before. 

Can you download the app from your site? It tells me to link my device.

**Comment by r0my** [comment]
> the Objective-C version requires iOS 15, but it's outdated
> 
> 
> 
> current Swift version deb, 1.4.1, requires iOS 14. in theory, it might work on iOS 13, but not on arm64e devices (iPhone XS and newer) because you need an older version of Xcode to build arm64e iOS 13 binaries. however, it may work when injected into an IPA. try injecting the latest deb, dev.theos.orion12, and CydiaSubstrate into IPA, and test it
> 
> 
> 
> if it doesn't work, either you or I can build an iOS 13 arm64e tweak deb with old Xcode to install with jailbreak


That sounds very difficult to me. I have never initiated anything. I hope there is someone here who can do that.

**Comment by fugegate** [comment]
> > the Objective-C version requires iOS 15, but it's outdated
> > 
> > 
> > 
> > current Swift version deb, 1.4.1, requires iOS 14. in theory, it might work on iOS 13, but not on arm64e devices (iPhone XS and newer) because you need an older version of Xcode to build arm64e iOS 13 binaries. however, it may work when injected into an IPA. try injecting the latest deb, dev.theos.orion12, and CydiaSubstrate into IPA, and test it
> > 
> > 
> > 
> > if it doesn't work, either you or I can build an iOS 13 arm64e tweak deb with old Xcode to install with jailbreak
> 
> 
> That sounds very difficult to me. I have never initiated anything. I hope there is someone here who can do that.

- Yes I can

**Comment by fugegate** [comment]
https://drive.google.com/file/d/1XqoY1g8gBV1-wLnJqWk_kWvdtKc02TpK/view?usp=drivesdk

**Comment by r0my** [comment]
> https://drive.google.com/file/d/1XqoY1g8gBV1-wLnJqWk_kWvdtKc02TpK/view?usp=drivesdk

Thank you for the upload. Just installed and the app crashes immediately. I also have to say that almost all apps crash. I don't know if it was after rootfs. When I download the app from the Appstore, my profile is also directly logged in there. Even after reinstallation. I don't know why the app always crashes. Other apps that I have installed work great. I only have the problem with Spotify. The app from the store works. Other versions crash directly or can't be tweaked to Premium. 
I've tried downgrading, sideloading, despite jb. I've already been on 100 Reddit threads, but I don't know what to do anymore. Turned off all other tweaks, but the app still crashes. There is no crash log from Spotify in the system either. Strange! 

I could cry. 😿

**Comment by fugegate** [comment]
> > https://drive.google.com/file/d/1XqoY1g8gBV1-wLnJqWk_kWvdtKc02TpK/view?usp=drivesdk
> 
> Thank you for the upload. Just installed and the app crashes immediately. 
> I also have to say that almost all tweaked spotify apps crash. I don't know if it was after rootfs a few month ago. 
> 
> 
> When I download the spotify app from the Appstore, my profile is also directly logged in there. Even after reinstallation. I don't know why the app always crashes. Other apps that I have installed work great. 
> 
> I only have the problem with Spotify. 
> 
> The app from the store works. Downgraded ones too. 
> Other tweaked versions crash directly or work, but can't be tweaked to Premium. 
> I've tried downgrading, sideloading, despite jb. 
> I've already been on 100 Reddit threads, but I don't know what to do anymore. Turned off all other tweaks, but the app still crashes. There is no crash log from Spotify in the system either. Strange! 
> 
> I could cry. 😿
> 
> 
> 

I'm so sorry it didn't work for you...it works for me tho idk why not you. 😭😭. If you don't mind me asking, what iPhone do you have and what version of iOS is it I'll try again to see if I can help you out

**Comment by r0my** [comment]
> > > https://drive.google.com/file/d/1XqoY1g8gBV1-wLnJqWk_kWvdtKc02TpK/view?usp=drivesdk
> > 
> > Thank you for the upload. Just installed and the app crashes immediately. 
> > I also have to say that almost all tweaked spotify apps crash. I don't know if it was after rootfs a few month ago. 
> > 
> > 
> > When I download the spotify app from the Appstore, my profile is also directly logged in there. Even after reinstallation. I don't know why the app always crashes. Other apps that I have installed work great. 
> > 
> > I only have the problem with Spotify. 
> > 
> > The app from the store works. Downgraded ones too. 
> > Other tweaked versions crash directly or work, but can't be tweaked to Premium. 
> > I've tried downgrading, sideloading, despite jb. 
> > I've already been on 100 Reddit threads, but I don't know what to do anymore. Turned off all other tweaks, but the app still crashes. There is no crash log from Spotify in the system either. Strange! 
> > 
> > I could cry. 😿
> > 
> > 
> > 
> 
> I'm so sorry it didn't work for you...it works for me tho idk why not you. 😭😭. If you don't mind me asking, what iPhone do you have and what version of iOS is it I'll try again to see if I can help you out 


Thank you very much for your help. I have about 30 .ipa's lying around here and none of them work. It's a horror. As I said I don't know exactly what happened but one day I opened Spotify and I had no more premium. I then tried all the tweaks from all the repos. nothing helped. after the grass grew over the matter again and again and my frustration passed, I started a new attempt. Like yesterday, when I once again came across an IPA in a Reddit topic. I then installed it and believe it or not, it finally works. I can't believe it but it's true. I don't know why exactly this version works for me and doesn't crash. Maybe someone can find out. But it works. It is:
