### ISSUE TITLE
[Question] Lyric fallback but with Musixmatch

### ISSUE THREAD

**Issue by RealTerrafrost** [whoeevee/EeveeSpotify#521]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

Not really an issue, but a requested feature. There's a genius lyric fallback thing in the settings, yes? I was thinking since the Musixmatch seems to region-lock (I don't know the name for it but when it pops up it suggests I get a vpn because the lyrics aren't available for some reason), you could make a LRCLIB fallback too so at least the lyrics are still time-synced. I only ask this because Musixmatch has the translate thing for most songs (at least I think), but I can't really default to using that because for other songs it will do the region-lock thing. So I was thinking a feature could be made where if Musixmatch region-locks the song it switches to LRCLIB instead of Genius so the lyrics are still time-synced.

**Comment by asdfzxcvbn** [comment]
related #237 #242 ?
