### ISSUE TITLE
[Bug] chromecast not working

### ISSUE THREAD

**Issue by Inframund** [whoeevee/EeveeSpotify#523]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

When I try to share my connection with Google chromecast I can't see the devices and I get a message that I am not connected to the same wifi.
![IMG_0546](https://github.com/user-attachments/assets/180178b8-baad-45fa-92eb-bd26f7493459)

**Comment by ElliotCHEN37** [comment]
dupe 
#342
