### ISSUE TITLE
[Bug] Using Musixmatch the Lyrics are all marked as No song found, with lyrics by Genius

### ISSUE THREAD

**Issue by AntoDipp** [whoeevee/EeveeSpotify#528]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

Each lyrics is mentioned as Song not found using Musixmatch, and therefore they do not appear synchronized. With other sources (example: LRCLIB) instead all texts appear synchronized

**Comment by AntoDipp** [comment]
Even if duplicated I provide a solution, in the other reports it is confusing. Just request, by deleting the old token, an anonymous token (only with the latest version of Eevee)

**Comment by AntoDipp** [comment]
**Solution**: requires a new anonymous token using the **latest version** of Eevee.

**Comment by ElliotCHEN37** [comment]
just refresh the token from musixmatch app or using latest ver of eevee and get one or any other ways
