### ISSUE TITLE
[Bug] Play Last/Restart Not working as it Should

### ISSUE THREAD

**Issue by TNT599** [whoeevee/EeveeSpotify#529]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

Video shows bug. When trying to return to a previous song in a playlist or mix, it goes back to the first song not the one before AND reshuffles the playlist instead of maintaining the order.

https://github.com/user-attachments/assets/378d56b2-9d55-4ab6-b41c-006b221a97f0

**Comment by asdfzxcvbn** [comment]
video doesnt load. anyways, eeveespotify shouldnt mess with this, are you sure you can reproduce this issue using stock spotify?

**Comment by asdfzxcvbn** [comment]
inactivity
