### ISSUE TITLE
Spotify prem icon

### ISSUE THREAD

**Issue by dezzyreal** [whoeevee/EeveeSpotify#53]
After like 1mins on spotify, premium icon appears again, i tried restarting the app and relogin. Nothing make the icon disappear but premium features works fine like no ads and unlimited skips. How do remove the prem icon.

**Comment by asdfzxcvbn** [comment]
strange. the icon going away was part of using the new offline.bnk data, maybe you could try uninstalling and reinstalling ? we likely won’t be bringing back SpotifyHidePremium anyway

**Comment by dezzyreal** [comment]
I tried already it doesnt hide it

**Comment by asdfzxcvbn** [comment]
okay weird. nobody else has reported this so i have no clue what the problem could be. gonna close this, will reopen if someone else opens an issue about this

**Comment by dezzyreal** [comment]
also when i switch playlist shuffle keep being disable how do i fix that?

**Comment by benswolo** [comment]
having the same issue (premium icon showing up). I installed in place from a previous spotify that uses spotilife though. Tried completely deleting and reinstalling, and then logging out and in again and I still see the premium icon.

**Comment by hazchempop** [comment]
Same issue for me. When i first install and get the pop up message to restart to get premium it works, then re-appears again the next time i open the app.
________________________________
