### ISSUE TITLE
This menu does not seem to work

### ISSUE THREAD

**Issue by dylans509** [whoeevee/EeveeSpotify#530]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

When I change these settings on this menu, it remains the same nothing changes
![IMG_0343](https://github.com/user-attachments/assets/e12ff5cd-a98d-42f4-9652-fa32d8d640a7)

**Comment by yodaluca23** [comment]
This is not from EeveeSpotify this is from Sposify, a different tweak, which yes, lots of the options are broken in recent versions of Spotify.

**Comment by dylans509** [comment]
So it can’t be fixed?Sent from my iPhoneOn Nov 16, 2024, at 8:49 PM, Luca LeBlanc ***@***.***> wrote:﻿
This is not from EeveeSpotify this is from Sposify, a different tweak, which yes, lots of the options are broken in recent versions of Spotify.
