### ISSUE TITLE
Delete the “Add Account” button

### ISSUE THREAD

**Issue by dylans509** [whoeevee/EeveeSpotify#534]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

Is it possible to delete the “Add Account” button on the next update 
![IMG_0360](https://github.com/user-attachments/assets/90570914-23d4-4338-87b3-4d8542820c7f)

**Comment by yodaluca23** [comment]
This seems to be an A/B feature, have you tried toggling override configuration? EeveeSpotify could probably edit the A/B flag, or just make the element transparent...
