### ISSUE TITLE
adding it to altstore

### ISSUE THREAD

**Issue by Zaculor** [whoeevee/EeveeSpotify#535]
### Is this issue appropriate?

- [ ] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [ ] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [ ] This is a unique issue

### Describe the bug.

im not sure whether im doing it right or typing it wrong but i tried to use the repo but it didnt work
can someone help 
i hope im not asking something illegal im new

**Comment by ElliotCHEN37** [comment]
dupe
#136

**Comment by asdfzxcvbn** [comment]
answer should be in common issues which you apparently didnt read..? wtf
