### ISSUE TITLE
[Bug] repo.altsource.json

### ISSUE THREAD

**Issue by encor50** [whoeevee/EeveeSpotify#542]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

after the last change of the repo.altsource.json i get an error now 

The source "eeveespotify" contains duplicate versions (8.9.92) for eeveespotify (com.spotify.client)

**Comment by encor50** [comment]
i think this those lines needs to be deleted 
from 28 to 34 

        {
          "version": "8.9.92",
          "version": "8.9.92",
          "date": "2024-11-18",
          "date": "2024-11-18",
          "localizedDescription": "Spotify v8.9.92 injected with EeveeSpotify",
          "localizedDescription": "Spotify v8.9.92 injected with EeveeSpotify",
          "downloadURL": "https://github.com/whoeevee/EeveeSpotify/releases/download/swift5.8.1/EeveeSpotify-5.8.1-8.9.92.ipa",
          "downloadURL": "https://github.com/whoeevee/EeveeSpotify/releases/download/swift5.8.1/EeveeSpotify-5.8.1-8.9.92.ipa",
          "size": 84064527
          "size": 84064527
        },
        },

**Comment by asdfzxcvbn** [comment]
fixed by #539
