### ISSUE TITLE
[Bug] Iphone SE - iOS 14.3 - Unable to Launch Eevee Spotify (Crashes on Startup)

### ISSUE THREAD

**Issue by Zwie0** [whoeevee/EeveeSpotify#545]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

I have a Iphone SE Software Version 14.3

When I try to launch Eevee Spotify through troll store, it crashes on startup. 

I have tried the debug versions, the arm64 versions. 

All fail on startup. 
What am i doing wrong ?

**Comment by whoeevee** [comment]
send crashlog with the debug version

**Comment by asdfzxcvbn** [comment]
can you try disabling tweak injection into the app with choicy?

**Comment by asdfzxcvbn** [comment]
oh we're stupid lol forgot to mention that the ipas require iOS 15.0 or later

iOS 14 users must be jailbroken and install the debs

**Comment by ceedveed** [comment]
I tried latest compatible for Spotify and arm deb on iPhone X 14.3 JB with Taurine. Settings show the deb works but premium is not active. 

Anyone get this working on a 14.3 device?

**Comment by ElliotCHEN37** [comment]
> I tried latest iOS 14 compatible Spotify 8.9.8.487 and arm deb on iPhone X 14.3 JB with Taurine. Settings show the deb works but premium is not active.
> 
> Anyone get this working on a 14.3 device?

try older version of eevee or just use spotilife

**Comment by whoeevee** [comment]
> try older version of eevee or just use spotilife. because eevee is designed for latest not older one

EeveeSpotify is actually designed to support only two versions: the latest one and 8.9.8, which is the last available for iOS 14. it targets iOS 14, uses SDKs compatible with iOS 14, complies with Spotify code changes, and implements all the methods to function correctly on version 8.9.8. i’ve tested latest debs on 8.9.8 a couple of days ago, and they work perfectly fine

> Settings show the deb works but premium is not active

try going to EeveeSpotify settings within the app and tapping “Reset Data”

**Comment by ceedveed** [comment]
> > try older version of eevee or just use spotilife. because eevee is designed for latest not older one
> 
> EeveeSpotify is actually designed to support only two versions: the latest one and 8.9.8, which is the last available for iOS 14. it targets iOS 14, uses SDKs compatible with iOS 14, complies with Spotify code changes, and implements all the methods to function correctly on version 8.9.8. i’ve tested latest debs on 8.9.8 a couple of days ago, and they work perfectly fine
> 
> > Settings show the deb works but premium is not active
> 
> try going to EeveeSpotify settings within the app and tapping “Reset Data”
> 
> 

Thank you much for your work!  Reset Data is the solution.
