### ISSUE TITLE
[Bug] When connecting to cars bluetooth Spotify always plays the same song over and over again.

### ISSUE THREAD

**Issue by blake2151** [whoeevee/EeveeSpotify#548]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

I noticed same thing happens on the regular Spotify app as well.
maybe there's a way to fix this somehow?

https://github.com/user-attachments/assets/43fcad7a-5642-4424-8df9-b3d73dcbe57f

**Comment by asdfzxcvbn** [comment]
bruh
