### ISSUE TITLE
Jam unable to join

### ISSUE THREAD

**Issue by RishiSuthar** [whoeevee/EeveeSpotify#55]
Sorry the ticket earlier closed, but just to note : the jam functionality is also not able to join as it proceeds to an error and does not open the app for me. Sorry, if this is already working and is a problem for me only, you can delete the issue. If not, it is just a suggestion for the next update. Thank you again for making this amazing tweak, always appreciated. :)

**Comment by qwool** [comment]
this is serverside i think

**Comment by sysconf16** [comment]
I am also experiencing this issue. 

Someone with a premium subscription will create a jam, but it will not show up for me even despite being on the same network with local network and bluetooth enabled on both devices. 

Scanning the QR code/opening the link from the jam redirects to download Spotify from the app store.

**Comment by ItsMeDrath** [comment]
jam feature is server sided and won't work in this tweak, but you can still join the jam if a premium user has started jam.

**Comment by RishiSuthar** [comment]
> jam feature is server sided and won't work in this tweak, but you can still join the jam if a premium user has started jam.

Does not work with tweaked version, it won’t not allow remote

**Comment by daddycool322** [comment]
I tried but it works with Jam (bluetooth)
I tried with the link, don't work, only try to download the official app.
Tried also with the Opener app, still try to open app store

**Comment by RishiSuthar** [comment]
> I tried but it works with Jam (bluetooth) I tried with the link, don't work, only try to download the official app. Tried also with the Opener app, still try to open app store

????? What do you mean, did it work or no

**Comment by daddycool322** [comment]
By bluetooth connection, yes

By link, (no) because (i think) the link don't go into the app, directly to the App Store (tried with Opener but same thing)

**Comment by RishiSuthar** [comment]
> By bluetooth connection, yes
> 
> By link, (no) because (i think) the link don't go into the app, directly to the App Store (tried with Opener but same thing)

Are you able to start a jam on your own ?

**Comment by daddycool322** [comment]
Nope it's not possible

**Comment by RishiSuthar** [comment]
> Nope it's not possible

Yeah same for me☹️☹️I can’t even join a jam. It’s server side

**Comment by whoeevee** [comment]
Hosting a Spotify Jam requires Premium, while joining by link doesn't, but it currently works only with Jailbreak/TrollStore. I'll probably look into it in the next update

**Comment by RishiSuthar** [comment]
> Hosting a Spotify Jam requires Premium, while joining by link doesn't, but it currently works only with Jailbreak/TrollStore. I'll probably look into it in the next update

Thank you so much, would appreciate 😄😄😄

**Comment by RishiSuthar** [comment]
> It works with link if you also download the normal Spotify app and join through that. You can have the side loaded and normal app at the same time

However, you still need premium to join in remotely. Not through same speaker.

**Comment by RishiSuthar** [comment]
> > However, you still need premium to join in remotely. Not through same speaker.
> 
> I could join a jam since I downloaded normal Spotify then using the join link, if that's what you're saying

On Spotify Jam, there’s 2 ways to join 

1.remotely from your own device: this one requires you to have a premium subscription 

2. From their speaker: this one, any user can join, whether free or premium

**Comment by RishiSuthar** [comment]
> Ohh do you mean creating a jam? If that's what you're talking about then that makes a lot more sense

Yes, creating a jam you need premium
Joining jam remotely you need premium
joining jam in person, no need for premium 
👍

**Comment by RishiSuthar** [comment]
> Sorry, I'm still confused, what do you mean joining a jam remotely??

Ok, so suppose you have hosted a jam, and I am at your house and we are both listening from one speaker, I can join the jam for free as a free user and add music to the jam. If I’m at your house 

but, if you are at your house and I am at my own house and we want to listen to music together, that is you are listening from your speaker and I am listening from my speaker. I need to have premium. To join the jam or even host the jam.


So there’s 2 ways of jam 
1. We are together physically - free
2. We are far away from each other- premium

**Comment by asdfzxcvbn** [comment]
the updated OpenSpotifySafariExtension now lets you join jams

**Comment by daddycool322** [comment]
not me ![image](https://github.com/whoeevee/EeveeSpotify/assets/116239295/a1c6104e-e4d9-486c-8d38-0103f3514aec)

**Comment by RishiSuthar** [comment]
> not me ![image](https://private-user-images.githubusercontent.com/116239295/332973857-a1c6104e-e4d9-486c-8d38-0103f3514aec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0MTU1ODIsIm5iZiI6MTcxNjQxNTI4MiwicGF0aCI6Ii8xMTYyMzkyOTUvMzMyOTczODU3LWExYzYxMDRlLWU0ZDktNDg2Yy04ZDM4LTAxMDNmMzUxNGFlYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMlQyMjAxMjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYTNiNWJhNDIwOTMzZTkzNTE4M2Q3MTdkZTFmNTU4NTllN2YwZjNlNDA3MDNjMDcyZTI2Y2FiMTYyOWQyZDJmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0C5goQbVBbgiCvt6hsKTmI5uBJKA2xrvIzVdg-PPmXY)

Can you really quick send me a jam link. So I can test

**Comment by daddycool322** [comment]
My friend had shared with her premium account

**Comment by RishiSuthar** [comment]
> My friend had shared with her premium account

Is there no link to the jam? Like a Spotify link so I can open with browser

**Comment by whoeevee** [comment]
> not me ![image](https://private-user-images.githubusercontent.com/116239295/332973857-a1c6104e-e4d9-486c-8d38-0103f3514aec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0MTU4MjcsIm5iZiI6MTcxNjQxNTUyNywicGF0aCI6Ii8xMTYyMzkyOTUvMzMyOTczODU3LWExYzYxMDRlLWU0ZDktNDg2Yy04ZDM4LTAxMDNmMzUxNGFlYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMlQyMjA1MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yODcyMjNhZjg3OWE2NmRlZmRkYjExMTdmZGNlMmRjZTQyYmMwMDMzNjdhOTRkMDgzZGEyZTZjNWIwNDFlMjJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qj9VBFoEC3WatORQvD7OvST--97dksHXOUyjJlceEmQ)

try opening the link again with Spotify opened

**Comment by daddycool322** [comment]
Will ask, can't create since I have a free plan

**Comment by daddycool322** [comment]
> > not me ![image](https://private-user-images.githubusercontent.com/116239295/332973857-a1c6104e-e4d9-486c-8d38-0103f3514aec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0MTU4MjcsIm5iZiI6MTcxNjQxNTUyNywicGF0aCI6Ii8xMTYyMzkyOTUvMzMyOTczODU3LWExYzYxMDRlLWU0ZDktNDg2Yy04ZDM4LTAxMDNmMzUxNGFlYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMlQyMjA1MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yODcyMjNhZjg3OWE2NmRlZmRkYjExMTdmZGNlMmRjZTQyYmMwMDMzNjdhOTRkMDgzZGEyZTZjNWIwNDFlMjJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qj9VBFoEC3WatORQvD7OvST--97dksHXOUyjJlceEmQ)
> 
> 
> 
> try following the link again with Spotify opened

Okay

**Comment by RishiSuthar** [comment]
Okay, just tried to join one of my friends jams. Still not working ☹️☹️☹️
![Uploading IMG_8178.png…]()

**Comment by daddycool322** [comment]
When I try to enter with the first option, it pop-up Premium
The second work but useless
![image](https://github.com/whoeevee/EeveeSpotify/assets/116239295/a246e016-2644-4472-8b81-41b76abb043f)
![image](https://github.com/whoeevee/EeveeSpotify/assets/116239295/581a8014-8cb4-4680-abc2-6188307633c8)
![image](https://github.com/whoeevee/EeveeSpotify/assets/116239295/02dd68e7-2af9-408a-bf00-24f16539d2f5)

**Comment by RishiSuthar** [comment]
Okay, just tried to join one of my friends jams. Still not working ☹️☹️☹️
![IMG_8178](https://github.com/whoeevee/EeveeSpotify/assets/77315331/1af22d3a-6960-4ef7-8e08-05c75f7d10c1)

**Comment by RishiSuthar** [comment]
> When I try to enter with the first option, it pop-up Premium The second work but useless ![image](https://private-user-images.githubusercontent.com/116239295/332977631-a246e016-2644-4472-8b81-41b76abb043f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0MTY4MTYsIm5iZiI6MTcxNjQxNjUxNiwicGF0aCI6Ii8xMTYyMzkyOTUvMzMyOTc3NjMxLWEyNDZlMDE2LTI2NDQtNDQ3Mi04YjgxLTQxYjc2YWJiMDQzZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMlQyMjIxNTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lOTc4YTRkNTU0Mjk3ZDcxNzZmOWFjNzFjNjc5MmFlMzMyZTc5ODBkNTk4ZmM1MDI3ODIzMWM3NWYxMjBmMDc1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XInLeJreZQ3H-QGYXY2p-HQhLpgliRBQbTSzQVj4r0s) ![image](https://private-user-images.githubusercontent.com/116239295/332977672-581a8014-8cb4-4680-abc2-6188307633c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0MTY4MTYsIm5iZiI6MTcxNjQxNjUxNiwicGF0aCI6Ii8xMTYyMzkyOTUvMzMyOTc3NjcyLTU4MWE4MDE0LThjYjQtNDY4MC1hYmMyLTYxODgzMDc2MzNjOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMlQyMjIxNTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04OGE3NWVmYWQ5ODE0MGM3MjhhYTk2NmI2MmNkODJlN2ZhMDQ3NjFlNjhmYWNkYTlhOGIzODE0ZmRhMGM0NzNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Eic4kQcIJnXVY5Jsz7LchOyAT1u6uUxgaF6niWmaaOU) ![image](https://private-user-images.githubusercontent.com/116239295/332977699-02dd68e7-2af9-408a-bf00-24f16539d2f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0MTY4MTYsIm5iZiI6MTcxNjQxNjUxNiwicGF0aCI6Ii8xMTYyMzkyOTUvMzMyOTc3Njk5LTAyZGQ2OGU3LTJhZjktNDA4YS1iZjAwLTI0ZjE2NTM5ZDJmNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMlQyMjIxNTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04OTFkZDkzMWU4ZGMwMjAwMDUyYTkzYWE3ZGRmZjgzMDBiZDI0ZWQ1NDdiZmQ2MzdjZmVjMGI2NzVmYzFlZmNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Yqp6XbwewMuoA8S8Tyks2TgAq3tcA60rioUI-CLc5zU)

Yeah exactly, same problem

**Comment by whoeevee** [comment]
only joining in-person works, joining remotely requires premium

**Comment by RishiSuthar** [comment]
> only joining in-person works, joining remotely requires premium

Yeah, hopefully you can find a fix for this in the coming future🙏🙏 would be amazing

**Comment by daddycool322** [comment]
> only joining in-person works, joining remotely requires premium

Okay thanks
