### ISSUE TITLE
Not being able to se my devices for example ps5 and speaker on spotify.

### ISSUE THREAD

**Issue by Agge0706** [whoeevee/EeveeSpotify#552]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

When I try to connect to other devices I cant se them when trying to connect. I have to connect via bluetooth for it to work but I can’t for example connect to my ps5 to play music thru my phone. I tried with the regular spotify app and i could se my devices but on eevee spotify I cannot.

**Comment by asdfzxcvbn** [comment]
#548, #396, #292
