### ISSUE TITLE
[Bug] meatballs menu broken again

### ISSUE THREAD

**Issue by ElliotCHEN37** [whoeevee/EeveeSpotify#554]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

Please update, Thx

**Comment by asdfzxcvbn** [comment]
can you.. specify?

**Comment by ElliotCHEN37** [comment]
> can you.. specify?

same as #408 #406 #388

**Comment by ElliotCHEN37** [comment]
https://github.com/whoeevee/EeveeSpotify/issues/408#issuecomment-2380894985

**Comment by ElliotCHEN37** [comment]
But it even happens when push config is turned off

**Comment by ElliotCHEN37** [comment]
I’m using iPhone X, 16.7.10, Rootless, using Sileo to inject

**Comment by asdfzxcvbn** [comment]
confirmed. leaving open for now

**Comment by ElliotCHEN37** [comment]
> confirmed. leaving open for now

thanks

**Comment by ElliotCHEN37** [comment]
> does it happen with Overwrite Configuration disabled? what if you enable Do Not Patch Premium?

Yes
Tested:
Turn off/on overwrite config
Turn off/on do not patch premium
IPA from Release
Inject with Sileo

**Comment by ElliotCHEN37** [comment]
Injected with TrollFools, but I got the same result (crashed...

**Comment by Taunty** [comment]
Same here freezing when installed via TrollStore

**Comment by ElliotCHEN37** [comment]
Solved!
I updated my Spotify to the latest version (9.0.0) and it works perfectly!

**Comment by Taunty** [comment]
> Solved!
> I updated my Spotify to the latest version (9.0.0) and it works perfectly!

Huh it still freeze for me even with latest v9 🧐

**Comment by ElliotCHEN37** [comment]
> > Solved!
> 
> > I updated my Spotify to the latest version (9.0.0) and it works perfectly!
> 
> 
> 
> Huh it still freeze for me even with latest v9 🧐

Really? OK, I’ll leave it open.

**Comment by Taunty** [comment]
> > > Solved!
> > 
> > 
> > > I updated my Spotify to the latest version (9.0.0) and it works perfectly!
> > 
> > 
> > Huh it still freeze for me even with latest v9 🧐
> 
> Really? OK, I’ll leave it open.

Yes, thank you 👌🏼So you’re using the ipa and it works for you? How did you do ? 🤣

**Comment by ElliotCHEN37** [comment]
> > > > Solved!
> 
> > > 
> 
> > > 
> 
> > > > I updated my Spotify to the latest version (9.0.0) and it works perfectly!
> 
> > > 
> 
> > > 
> 
> > > Huh it still freeze for me even with latest v9 🧐
> 
> > 
> 
> > Really? OK, I’ll leave it open.
> 
> 
> 
> Yes, thank you 👌🏼So you’re using the ipa and it works for you? How did you do ? 🤣

Nope I'm using Selio and App Store

**Comment by whoeevee** [comment]
meatballs
![IMG_0320](https://github.com/user-attachments/assets/5dc627fc-5dad-40dc-9020-8ccb142def1a)

**Comment by BB4LIFE** [comment]
Hamburger also crashes

**Comment by Richard-NDC** [comment]
I can still use it lol
![image](https://github.com/user-attachments/assets/630e77a6-073c-42fc-8d23-337261b57653)

**Comment by BB4LIFE** [comment]
I think updating the app fixed everything.

**Comment by Taunty** [comment]
> I think updating the app fixed everything.

It’s still crashing for me even with the latest ipa :(

**Comment by ElliotCHEN37** [comment]
Works well in 9.0.2

**Comment by Taunty** [comment]
Yeah finally working very well 👌🏼 Thanks !

**Comment by samuelawachie** [comment]
Had to go back to version 5.8.1 which doesn't have the same issue
