### ISSUE TITLE
[Bug] Songs are greyed out and unable to be played

### ISSUE THREAD

**Issue by gray-morley** [whoeevee/EeveeSpotify#557]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

When choosing songs from an album, all the songs are greyed out. Tapping on them does nothing. See below example

![IMG_9352](https://github.com/user-attachments/assets/5c0159d3-728a-46f9-a332-76642c982a5e)

**Comment by asdfzxcvbn** [comment]
have you read common issues?

**Comment by gray-morley** [comment]
Yes. It’s not a VPN issue

**Comment by 3xynos7** [comment]
It seems like you’ve changed your country to a different one in your account settings. Just head over to your account settings and make sure your country is set back to your home country.

**Comment by gray-morley** [comment]
Yep, just fixed it. I think there was an issue with my VPNearlier when I tried to reset it. Thanks! It’s working now
