### ISSUE TITLE
[Bug] Error popup with LiveContainer

### ISSUE THREAD

**Issue by michael1900** [whoeevee/EeveeSpotify#558]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

Hi, i have installed Eevee with LiveContainer but every time i run Eevee i have a popup error: Impossible to open the link, etc..

How to fix this error?

![IMG_0004](https://github.com/user-attachments/assets/879ed7e3-9aeb-44ce-9a82-56d8b5ecc501)

**Comment by asdfzxcvbn** [comment]
support will not be provided for livecontainer installs

**Comment by michael1900** [comment]
> support will not be provided for livecontainer installs

About the popup, can i know at least which link Spotify try to open? 
Are you sure that this popup doesn't appear also without LiveContainers?

**Comment by asdfzxcvbn** [comment]
> > support will not be provided for livecontainer installs
> 
> About the popup, can i know at least which link Spotify try to open? Are you sure that this popup doesn't appear also without LiveContainers?

i don't even know why that's showing up on launch if you're not opening a link, must be some issue related to how LiveContainer works. we don't use LC ourselves and aren't interested in fixing such an issue

**Comment by michael1900** [comment]
> > > support will not be provided for livecontainer installs
> > 
> > 
> > About the popup, can i know at least which link Spotify try to open? Are you sure that this popup doesn't appear also without LiveContainers?
> 
> i don't even know why that's showing up on launch if you're not opening a link, must be some issue related to how LiveContainer works. we don't use LC ourselves and aren't interested in fixing such an issue

Ok, thank you for the reply

**Comment by michael1900** [comment]
> > > support will not be provided for livecontainer installs
> > 
> > 
> > About the popup, can i know at least which link Spotify try to open? Are you sure that this popup doesn't appear also without LiveContainers?
> 
> i don't even know why that's showing up on launch if you're not opening a link, must be some issue related to how LiveContainer works. we don't use LC ourselves and aren't interested in fixing such an issue

Fixed in the last nightly build of LC! 
https://github.com/hugeBlack/LiveContainer/actions

@asdfzxcvbn
