### ISSUE TITLE
How to inject tweaks to latest spotify ipa with sideloadly?

### ISSUE THREAD

**Issue by ElliotCHEN37** [whoeevee/EeveeSpotify#56]
How to inject tweaks to latest spotify ipa with sideloadly?

**Comment by asdfzxcvbn** [comment]
you'll need EeveeSpotify's deb, [orion](https://repo.chariz.com/debs/EERul-KR3KNJai8flkX9wP7w4CN48J6dUa1ig25cdmT4CdepwTMG_hi8mWbimcP9h7o8JjQMVXfeTxcNTgXZ3w/dev.theos.orion14_1.0.1_iphoneos-arm.deb), and [swiftprotobuf](https://files.catbox.moe/s16z3c.deb)

sideloadly has an option to inject debs, so you can use that. btw there really is no need to make your own -- we manage our own telegram channel that keeps spotify updated automatically. use telegram's global search to search for EeveeSpotify IPAs and it'll show up.

**Comment by ElliotCHEN37** [comment]
Thanks
