### ISSUE TITLE
UPDATE!!!!! THIS ISN'T A BUG Spotify just changed where the local files option is in the spotify app new ui its in apps and devices 

### ISSUE THREAD

**Issue by Solowas2taken** [whoeevee/EeveeSpotify#560]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

I noticed in Swift 5.8 Spotify I noticed that the in app local files setting worked just fine and appeared in the app. Now when updating to Swift 5.8.2 its completely gone so I had to roll back. Is this a bug and can it be fixed? I buy certificates to sideload my app's and when I sideload Spotify I always click support document browsing however it dosen't work on the new version

**Comment by asdfzxcvbn** [comment]
this actually seems to be rolling out through A/B. you can enable local files option in the Apps and devices tab

**Comment by Solowas2taken** [comment]
Lol I found it write you commented on this Spotify changed where they put the local files option
