### ISSUE TITLE
[Bug] unable to play songs in any order?

### ISSUE THREAD

**Issue by M4TT587** [whoeevee/EeveeSpotify#562]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

I clicked on a song to play but then I received this pop up and couldn’t play the song I wanted for some reason 
![IMG_0816](https://github.com/user-attachments/assets/f16a2968-225f-4ee5-911e-2b76dfea52eb)

**Comment by rayanshchauhan05** [comment]
facing the exact same issue, only fix at the moment is to go to queue manually and play the song you want to after adding it to queue.

**Comment by yodaluca23** [comment]
Works for me, have you tried Reset data option? Override configuration?

**Comment by M4TT587** [comment]
> Works for me, have you tried Reset data option? Override configuration?

It works temporarily but after a few hours it happens again

**Comment by whoeevee** [comment]
this issue is related solely to region. you should change it using a vpn and then relogin. overwrite configuration should not be used if you experience issues with track playback or other common features

**Comment by Ricky-1221** [comment]
> this issue is related solely to region. you should change it using a vpn and then relogin (see common issues). overwrite configuration should not be used if you experience issues with track playback or other common features

I recommend using the [CCVPN ](https://www.ios-repo-updates.com/repository/bigboss/package/com.kingpuffdaddi.control-center.ccvpn/)tweak so you don't have to go into settings or the vpn app
