### ISSUE TITLE
not rlly an issue, i'm jus new to this

### ISSUE THREAD

**Issue by crept12** [whoeevee/EeveeSpotify#564]
how do i actually get this to work on ios

**Comment by yodaluca23** [comment]
Checkout https://www.reddit.com/r/sideloaded

The most notable methods to sideload are:

https://github.com/opa334/TrollStore/releases (Free, best option if on compatible version)

https://github.com/SideStore/SideStore (Free but limited)

https://github.com/khcrysalis/Feather + Paid certificate.

**Comment by crept12** [comment]
thx bro
