### ISSUE TITLE
I can’t download evee Spotify 

### ISSUE THREAD

**Issue by F727163** [whoeevee/EeveeSpotify#566]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

So I was on the 5.8v and I uninstalled it to install the official Spotify to see my wrapped but when I delete Spotify to download the new version of evee this didn’t work and I tried to download the old version but same issue

**Comment by srinivasb99** [comment]
Be more specific what's the issue? What method did you use to sideload? Also you can view wrapped in eevee it's the same as regular Spotify lol

**Comment by F727163** [comment]
So the spotify icône stay white and don't download , I use ESign. So I did all this for nothing ..
