### ISSUE TITLE
New Release 2.0 keeps crashing

### ISSUE THREAD

**Issue by TheDoctor200** [whoeevee/EeveeSpotify#57]
Ipa as well as both tweaks don't work. Ipa instantly crashes, tweaks work but as soon Songs are skipped the app crashes.

**Comment by asdfzxcvbn** [comment]
try using the ipa and disabling tweak injection with choicy

**Comment by TheDoctor200** [comment]
That still doesn't work

**Comment by whoeevee** [comment]
send the crash log

**Comment by TheDoctor200** [comment]
[Spotify-2024-05-05-212840.txt](https://github.com/whoeevee/EeveeSpotify/files/15214440/Spotify-2024-05-05-212840.txt)

**Comment by whoeevee** [comment]
is this issue resolved in v2.1?

**Comment by TheDoctor200** [comment]
Yes it's solved now, thanks :))
