### ISSUE TITLE
App for Android phones? 

### ISSUE THREAD

**Issue by FangGit0** [whoeevee/EeveeSpotify#570]
I can't find any app package for Android os in assets. Is it not available for Android os? If yes, why not? Please make an apo for Android os too.

**Comment by TeaselUwU** [comment]
Modded apks exist for Spotify and many more applications/games than for iOS. You can find them anywhere and everywhere, please stop being arrogant, picky and lazy.

**Comment by ElliotCHEN37** [comment]
> I can't find any app package for Android os in assets. Is it not available for Android os? If yes, why not? Please make an apo for Android 

Eevee will NEVER have Android ver.

**Comment by asdfzxcvbn** [comment]
xmanager
