### ISSUE TITLE
[Bug] Spotify not opening from control center or in the notification center when click on the track

### ISSUE THREAD

**Issue by bat-deluxe** [whoeevee/EeveeSpotify#572]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

As previously said, Spotify does not open from the control center, the notification center or from the Dynamic Island.. idk why, i’m using FlekSt0re to signe it.
except this really annoying bug, everything works fine !

https://github.com/user-attachments/assets/2030fbf5-278d-4341-ac80-c910c43fb16e

**Comment by yodaluca23** [comment]
Read common issues next time please.
https://github.com/whoeevee/EeveeSpotify/blob/swift/common_issues.md#sideloading
