### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by MilyVilly** [whoeevee/EeveeSpotify#576]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

I don't understand what's the point if nothing works, it's not premium anyway, it's just an ordinary application

**Comment by TeaselUwU** [comment]
Reading is fundamental. Do you by any chance use text to speech? If you are collidearazorbladewithyourveins. If you want premium so bad, buy it.

**Comment by asdfzxcvbn** [comment]
![image](https://github.com/user-attachments/assets/1b96d593-a5c1-4917-b84c-80cf126d2892)

(read common issues)
