### ISSUE TITLE
Spotify asks for premium

### ISSUE THREAD

**Issue by Ur7rash** [whoeevee/EeveeSpotify#577]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

Spotify asks for premium after a certain amount of song changes just like when you don’t have premium. You can still skip song but when you select a specific song it just plays the first song of the playlist. I’m using version 9.0.2

https://github.com/user-attachments/assets/c22d902e-f468-49e7-aa10-fd3775887e75

**Comment by asdfzxcvbn** [comment]
common issues
