### ISSUE TITLE
Genius lyrics has issues for some songs

### ISSUE THREAD

**Issue by gototheskinny** [whoeevee/EeveeSpotify#58]
iphone 14 pro 17.3.1 
Installed via Sideloady
Tweak version 2.0

All of them are Taylor Swift songs.

-Some of them have random language translated lyrics 
-Some of them are not actual lyrics but the article?? Of the song.

Screenshots of the issues
[https://ibb.co/v152b2F](https://ibb.co/v152b2F)
[https://ibb.co/bbkPK6J](https://ibb.co/bbkPK6J)
[https://ibb.co/F4KSjFR](https://ibb.co/F4KSjFR)
[https://ibb.co/5vMLvNT](https://ibb.co/5vMLvNT)
[https://ibb.co/M5VppYB](https://ibb.co/M5VppYB)
[https://ibb.co/W3rYkR1](https://ibb.co/W3rYkR1)
[https://ibb.co/jHZPRfr](https://ibb.co/jHZPRfr)
[https://ibb.co/kXb1z1L](https://ibb.co/kXb1z1L)

**Comment by Bryceshaw06** [comment]
Having a similar issue, it seems when it can't find lyrics for the song it pulls random articles.

**Comment by whoeevee** [comment]
The lyrics might be wrong for some songs. This is due to how the tweak searches songs on Genius. It strips the song name and attempts to find a song on Genius that matches this name. If it's unable to find the song, it'll use the first one from the search hits. I've made it work with most cases.

**Comment by gototheskinny** [comment]
> The lyrics might be wrong for some songs. This is due to how the tweak searches songs on Genius. It strips the song name and attempts to find a song on Genius that matches this name. If it's unable to find the song, it'll use the first one from the search hits. While I've made it work in most cases, kindly refrain from opening issues about it.

I was just letting you about the issue. I get it. For the most part it's working without any issues. Thank you so much for making this tweak. 

BTW is there a way to implement musixmatch timed lyrics like the native lyrics feature? That would be the perfect solution for the lyrics situation.

**Comment by gototheskinny** [comment]
> The lyrics might be wrong for some songs. This is due to how the tweak searches songs on Genius. It strips the song name and attempts to find a song on Genius that matches this name. If it's unable to find the song, it'll use the first one from the search hits. While I've made it work in most cases, kindly refrain from opening issues about it.

Ty for considering musixmatch or other sources for timed lyrics! And fixing translated lyrics.
You're a legend ❤️!
