### ISSUE TITLE
[Bug] Options to turn on local Files disappeared

### ISSUE THREAD

**Issue by LD-0640** [whoeevee/EeveeSpotify#580]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

![IMG_8582](https://github.com/user-attachments/assets/6289c6a5-d0c8-424c-b6c4-6f2d549b4fdd)

I can’t turn on local files I had them on in the previous version but once I updated they disappeared.

**Comment by TeaselUwU** [comment]
It’s in “Apps and devices” tab
