### ISSUE TITLE
[Bug] Not able to skip songs when connected to Alexa devices

### ISSUE THREAD

**Issue by Comfizuki** [whoeevee/EeveeSpotify#581]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

My premium features used to be still applicable to whenever i connect to my Alexa devices to use as speakers. But since this update (or maybe the last) , every time i connect to my speakers, Spotify acts as if i don't have premium anymore (cant skip songs, shuffles between random songs etc.)

**Comment by asdfzxcvbn** [comment]
doesnt work with spotify connect, use bluetooth
