### ISSUE TITLE
SideStore: Link

### ISSUE THREAD

**Issue by Amazon90** [whoeevee/EeveeSpotify#582]
The data couldn't be read because it is missing.

I hope you can re-add the Sidestore repository. Thank you 🙏

**Comment by asdfzxcvbn** [comment]
can you send a screenshot of the issue??

**Comment by Amazon90** [comment]
> can you send a screenshot of the issue??

![image](https://github.com/user-attachments/assets/094a74fc-2406-4b90-a8cb-0cf890a1aca4)

**Comment by asdfzxcvbn** [comment]
can you access https://repo.whoeevee.com/altstore from your browser?

**Comment by Amazon90** [comment]
> can you access https://repo.whoeevee.com/altstore from your browser?

Sorry, I encountered an issue while using SideStore today. After reinstalling it, I couldn’t get it to work. I’ll try the link you provided tomorrow to see if it’s effective.
The link you provided opens fine in Safari, but I can’t confirm right now whether it can be added to SideStore.
![image](https://github.com/user-attachments/assets/4ab6b709-7d48-4290-9ba1-64793584d122)

**Comment by Yongsterp** [comment]
> can you send a screenshot of the issue??

![IMG_3924](https://github.com/user-attachments/assets/ef898e92-a902-4f44-90c8-80299731910f)

**Comment by asdfzxcvbn** [comment]
> > can you send a screenshot of the issue??
> 
> ![IMG_3924](https://private-user-images.githubusercontent.com/68872039/398010799-ef898e92-a902-4f44-90c8-80299731910f.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5MjAzNDgsIm5iZiI6MTczNDkyMDA0OCwicGF0aCI6Ii82ODg3MjAzOS8zOTgwMTA3OTktZWY4OThlOTItYTkwMi00ZjQ0LTkwYzgtODAyOTk3MzE5MTBmLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyM1QwMjE0MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jOTc5NGNjZDlhYTM1NDU3NTgwMzYxMjA3NjY3MTFlY2UzNzdiZjc0ODczNWVmZWFiYjUyMjU0YjA3NGE3ZTEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.j7eupXV1JcGzRa0PERbzv0fz9rph9nSdKDSfrB2NXU0)

will be fixed soon

**Comment by asdfzxcvbn** [comment]
@Yongsterp please try again

**Comment by Yongsterp** [comment]
> @Yongsterp please try again

says this now
![IMG_3925](https://github.com/user-attachments/assets/1b03b62f-7af4-4853-be33-db66c71ba331)

**Comment by asdfzxcvbn** [comment]
> > @Yongsterp please try again
> 
> says this now ![IMG_3925](https://private-user-images.githubusercontent.com/68872039/398039825-1b03b62f-7af4-4853-be33-db66c71ba331.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5Mjk5MzEsIm5iZiI6MTczNDkyOTYzMSwicGF0aCI6Ii82ODg3MjAzOS8zOTgwMzk4MjUtMWIwM2I2MmYtN2FmNC00ODUzLWJlMzMtZGI2NmM3MWJhMzMxLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyM1QwNDUzNTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYmVkZmNmNjU3ZjE3ODA1NDMwZTQzZTI3Yzk2MTA0NjkyMzBiOTA5Njc1MzcwNWEzMWE3NmRjMDQzNTExZDI5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.JutoKmwUPdCT0CpFJep3_ymP3v4pS2vKasfIHSD59ko)

oh now i remember why. i think im gonna end up making a seperate sidestore output in UniversalRepoFmt, since it's just so different from altstore (really stupid)

**Comment by wynwxst** [comment]
to everyone here, what version of sidestore are you using?

**Comment by asdfzxcvbn** [comment]
@Yongsterp @Amazon90 i've fixed the issue, it should work now (tested myself as well)

@wynwxst said sidestore's behavior here is unintentional and hopefully a fix for sidestore should come out soon
