### ISSUE TITLE
Not a bug, just a question

### ISSUE THREAD

**Issue by Sorena-29** [whoeevee/EeveeSpotify#588]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

I am clueless about what to do. I have no computer experience. Can you make a tutorial, please?

**Comment by Aditya4studys** [comment]
Just type how to use sideloadly on youtube and follow the steps for this app

**Comment by ElliotCHEN37** [comment]
The easiest way: Sideloadly!
Everyone begins from zero, explore and find the best method that works for you

**Comment by Sorena-29** [comment]
Ok I watched the tutorial video and I have downloaded the necessary things. However, there are two things. When I opened Sideloadly, it appeared in a very small window and I can't resize it to make it bigger. Also, I don't know what I have to download from this github. Where is the ipa file?
