### ISSUE TITLE
Crashes when trying to load lyrics

### ISSUE THREAD

**Issue by HackZy01** [whoeevee/EeveeSpotify#59]
> **Device:** iPhone 11 Pro, iOS 17.0
> **System Language:** Polish
> **Version:** Swift 2.0, `EeveeSpotify-2.0-8.9.36.ipa`
> **Install method:** TrollStore

Version 2.0 crashes whenever it tries to load lyrics in the now playing view (1.4.1 works flawlessly)

https://github.com/whoeevee/EeveeSpotify/assets/77678316/80d9f228-7e66-48d4-bebd-0a85eab70e05

As you can see, it crashes instantly after the "Lyrics" card shows up

**Comment by Bryceshaw06** [comment]
This just started happening to me as well, it was fine earlier though and I didn't mess with the app. Just now updated to 2.1, the issue is still happening.

**Comment by whoeevee** [comment]
try to reinstall the app
if it doesn’t work and you still experience crashes, install the debug IPA and send the crashlog

**Comment by Bryceshaw06** [comment]
Reinstalling fixed it for me

**Comment by HackZy01** [comment]
Fixed on 2.1
