### ISSUE TITLE
[FR] Alternative plan if hiding lyric box can't be realized.

### ISSUE THREAD

**Issue by ElliotCHEN37** [whoeevee/EeveeSpotify#590]
We can make it display something like “Oops, We don't know the lyric” etc. just like the desktop version of Spotify instead of the ugly gray box

**Comment by 3xynos7** [comment]
Or remove the gray box section.

**Comment by ElliotCHEN37** [comment]
You caught us, we're still working on getting lyrics for this one.
Hmm. We don't know the lyrics for this one.

Get two of them~~~

**Comment by asdfzxcvbn** [comment]
kinda related to #253, and wont be implemented

**Comment by ElliotCHEN37** [comment]
Ok
