### ISSUE TITLE
[BUG] Local Files Problem

### ISSUE THREAD

**Issue by andrixcx** [whoeevee/EeveeSpotify#592]
So after updating EeveeSpotify in the latest version. it didn’t ask me about my iTunes library so it didn’t show me my local files or the toggle in the settings. The only version i can toggle local files is v5.8. Does this happen to y’all too?

**Comment by asdfzxcvbn** [comment]
local files is now in the **Apps and devices** tab

**Comment by andrixcx** [comment]
my bad, thanks
