### ISSUE TITLE
[Bug] TrollApps, AltStore, SideStore repo not working

### ISSUE THREAD

**Issue by jimmysofat6864** [whoeevee/EeveeSpotify#595]
### Is this issue appropriate?

- [X] I have read the document in its entirety

### Is this issue unique to EeveeSpotify?

- [X] I was unable to reproduce my issue using the stock Spotify app

### Have you searched the existing issues?

- [X] This is a unique issue

### Describe the bug.

The Altstore repo doesn't work. It returns 404. 

![image](https://github.com/user-attachments/assets/4ce0091b-67c2-4a29-ae1a-820b00fc6960)

**Comment by asdfzxcvbn** [comment]
EeveeSpotify has new repo links, you can find them here: https://github.com/whoeevee/EeveeSpotify/tree/swift/Repositories

**Comment by jimmysofat6864** [comment]
> EeveeSpotify has new repo links, you can find them here: https://github.com/whoeevee/EeveeSpotify/tree/swift/Repositories

I was using the links at https://github.com/whoeevee/EeveeSpotify/blob/swift/common_issues.md so that might be why.

**Comment by asdfzxcvbn** [comment]
> > EeveeSpotify has new repo links, you can find them here: https://github.com/whoeevee/EeveeSpotify/tree/swift/Repositories
> 
> @asdfzxcvbn I was using the links at https://github.com/whoeevee/EeveeSpotify/blob/swift/common_issues.md so that might be why.

i've just updated the document, thanks
