### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by trevmont65** [whoeevee/EeveeSpotify#64]
My Spotify crashes on latest 2 versions of Spotify. 2.0 seems to be doing it. When I go into the now playing view it'll instantly crash

**Comment by PrigoanaEd** [comment]
Can confirm. It seems to only be the latest version with the genius lyrics added.

**Comment by fugegate** [comment]
It was working and then started crashing 😭

**Comment by PrigoanaEd** [comment]
> It was working and then started crashing 😭 

As a quick fix, just go back to the previous version while this issue gets resolved.

**Comment by whoeevee** [comment]
is it resolved in 2.1?

**Comment by PrigoanaEd** [comment]
> is it resolved in 2.1?

Hey, I didn't see the latest release. Let me try it and I'll get back to you.

**Comment by PrigoanaEd** [comment]
Yes, it is resolved in 2.1.
