### ISSUE TITLE
lyrics messy code

### ISSUE THREAD

**Issue by zippy2005** [whoeevee/EeveeSpotify#65]
![image](https://github.com/whoeevee/EeveeSpotify/assets/16781687/b36b89a1-5f37-45a9-9ac1-4cea65703378)

version 2.1

**Comment by zippy2005** [comment]
sorry,it works i just tested.
errors only this song 😆 
btw is there any setting menu? 
I couldn't find yet.

**Comment by whoeevee** [comment]
the lyrics might be wrong for some songs, this is due to how the tweak searches songs on Genius. I've made it work in most cases

and there is no settings menu
