### ISSUE TITLE
Reloading user data endlessly

### ISSUE THREAD

**Issue by manstyB4III** [whoeevee/EeveeSpotify#66]
Every time I start the application I get this error message. I restart the app once with 'Restart App' but it always reappears, same for 'Reset Data and Restart App' but it eventually stops and works after a while.

![IMG_3710](https://github.com/whoeevee/EeveeSpotify/assets/129116507/5b296b0b-8fff-4448-ad24-26509eeb6613)

**Comment by PrigoanaEd** [comment]
This doesn't happen to me in version 2.1. Try clicking restart Spotify and then force restart it. It should appear one or 2 more times but just keep doing it.

**Comment by manstyB4III** [comment]
Oh yes, so it's normal that it starts again a few times even after restarting, I thought it was just an unsupported bug.

**Comment by PrigoanaEd** [comment]
> Oh yes, so it's normal that it starts again a few times even after restarting, I thought it was just an unsupported bug.

I think there's no way around it, Spotify just reloads user data when you install it first. If it was easy to just get rid of the prompt, I'm sure the developer would've already implemented it.

**Comment by manstyB4III** [comment]
I agree, then the app is already amazing as it is.

**Comment by Yaggio94** [comment]
I have the same error here in Italy, i read that you need to use debug ipa and send the crash log
![image](https://github.com/whoeevee/EeveeSpotify/assets/39501754/71d88a71-81b8-4561-b85b-db5881c777b1)

**Comment by manstyB4III** [comment]
I installed Spotify with the normal version then with the debug version, but that doesn't change anything (how do I send crash logs?). I just think that this Reloading user data endlessly is not considered as a "crash" because the developer himself tells us to restart the application.

**Comment by Yaggio94** [comment]
i have the same issue, to use spotify i restart the App 3 or 4 times.
For send the log you need to check this inside the app, i do the same today so me too need to ceck how to do it

**Comment by manstyB4III** [comment]
Yes, that's the only "big problem" otherwise the application works perfectly. If you find how to share error logs, please let me know

**Comment by manstyB4III** [comment]
For example, my phone went to sleep with Spotify open (I was inactive in the application), and when I unlocked it, the application reappeared the message "Spotify has just reloaded user data".

**Comment by PrigoanaEd** [comment]
> For example, my phone went to sleep with Spotify open (I was inactive in the application), and when I unlocked it, the application reappeared the message "Spotify has just reloaded user data".

Try disabling background app refresh.![image](https://github.com/whoeevee/EeveeSpotify/assets/146183093/a0454ad7-f1ea-4ddf-ad6f-bdb72713b3b4)

**Comment by manstyB4III** [comment]
It is disabled by default in General -> Background Refresh -> Background Refresh: No

**Comment by PrigoanaEd** [comment]
> It is disabled by default in General -> Background Refresh -> Background Refresh: No

For me, I have to go into settings, search Spotify, and disable background app refresh. I haven't had this issue.

**Comment by Yaggio94** [comment]
so the background app refresh needs to be ON or OFF ?

**Comment by PrigoanaEd** [comment]
> so the background app refresh needs to be ON or OFF ?

It doesn't have to be anything but in my experience having it off has less issues.

**Comment by manstyB4III** [comment]
Personally, I still have the bug. What I meant is that background refresh is disabled for all apps, so I don't need to disable it specifically for Spotify.
![image](https://github.com/whoeevee/EeveeSpotify/assets/129116507/19120693-b08c-464e-a18d-fba68370edb8)
![image](https://github.com/whoeevee/EeveeSpotify/assets/129116507/7d341397-53da-4757-9b53-95ab32ad16c4)

**Comment by PrigoanaEd** [comment]
> Personally, I still have the bug. What I meant is that background refresh is disabled for all apps, so I don't need to disable it specifically for Spotify.
> 
> ![image](https://github.com/whoeevee/EeveeSpotify/assets/129116507/19120693-b08c-464e-a18d-fba68370edb8)
> 
> ![image](https://github.com/whoeevee/EeveeSpotify/assets/129116507/7d341397-53da-4757-9b53-95ab32ad16c4)
> 
> 

Just restart the app 3 or 4 times, it should work. Of course, nothing you can really do about the random losses of premium.

**Comment by manstyB4III** [comment]
Yes, maybe wait for a fix, I don't know.

**Comment by asdfzxcvbn** [comment]
answered in #118
