### ISSUE TITLE
Endless track skip

### ISSUE THREAD

**Issue by quadyyyy** [whoeevee/EeveeSpotify#67]
While playing, the tracks skip on their own and it is impossible to stop it

**Comment by oneisabirdotgw** [comment]
Having the same issue!

https://github.com/whoeevee/EeveeSpotify/assets/169163271/f6fdd346-2333-4809-81bd-4010abea91dd

**Comment by whoeevee** [comment]
try to change the region to some other at accounts.spotify.com with vpn

**Comment by oneisabirdotgw** [comment]
Thanks that worked for me!

**Comment by asdfzxcvbn** [comment]
@quadyyyy please try provided solution

**Comment by THICCD0GG0** [comment]
Any other solutions the vpn with change region didn’t work

**Comment by whoeevee** [comment]
did you relogin with vpn in the app after changing the region?

**Comment by quadyyyy** [comment]
@whoeevee thanks, that worked for me
