### ISSUE TITLE
Alternative for genius api

### ISSUE THREAD

**Issue by Diowboss** [whoeevee/EeveeSpotify#69]
Instead of using the genius api, you could use the https://lrclib.net/ api as it has timesynced lyrics.

**Comment by daddycool322** [comment]
+1 please. Genius as backup if possible too

**Comment by trevmont65** [comment]
+1 would be dope

**Comment by yodaluca23** [comment]
I agree, this would be a nice way of getting time synced lyrics, and having Genius as a backup.

**Comment by whoeevee** [comment]
thanks for the suggestion, I may add this lyrics provider in next updates

but while lrclib offers time-synced lyrics, it lacks lyrics for many songs and its lyrics aren't as high-quality as Genius. personally, I find Genius has the best text quality, it’s available for almost every song, and I prefer it even if it’s not synced

do you really need lrclib?

**Comment by yodaluca23** [comment]
For me personally, I won’t use the lyrics if they’re not timed Sync, maybe you could have a little menu where you can choose which one has priority and which one to use as a fallback.

**Comment by Diowboss** [comment]
> thanks for the suggestion, I may add this lyrics provider in next updates
> 
> but while lrclib offers time-synced lyrics, it lacks lyrics for many songs and its lyrics aren't as high-quality as Genius. personally, I find Genius has the best text quality, it’s available for almost every song, and I prefer it even if it’s not synced
> 
> do you really need lrclib?

I wasn’t really “needing” it it’s just that for most songs that it does have it’s a great api.

**Comment by jasperaelvoet** [comment]
Spicetify has an extension that also loads the lyrics from other sources. Might be helpful. [https://github.com/spicetify/spicetify-cli/tree/master/CustomApps/lyrics-plus](https://github.com/spicetify/spicetify-cli/tree/master/CustomApps/lyrics-plus)

**Comment by not-yuvi** [comment]
+1 for custom sources

**Comment by fugegate** [comment]
> Spicetify has an extension that also loads the lyrics from other sources. Might be helpful. [https://github.com/spicetify/spicetify-cli/tree/master/CustomApps/lyrics-plus](https://github.com/spicetify/spicetify-cli/tree/master/CustomApps/lyrics-plus)

+1 yeah same

**Comment by whoeevee** [comment]
check out v3.0

**Comment by daddycool322** [comment]
Tested and work great. Thanks.

**Comment by hazchempop** [comment]
Can you explain how to extract user token for Musixmatch? What is “MITM”
________________________________

**Comment by daddycool322** [comment]
Tested and work great.

But I think it's normal yeah ?! Lyrics preview
![image](https://github.com/whoeevee/EeveeSpotify/assets/116239295/736bdc6f-c923-4bbc-ba6e-8ff5a7dbc3be)

**Comment by daddycool322** [comment]
@hazchempop https://www.reddit.com/r/spicetify/s/L4iVnJ2b4B 

Try this. I haven't tried it yet but seems to be the same thing

**Comment by daddycool322** [comment]
@whoeevee Okay thanks. How to extract the user token from the phone please ?

**Comment by daddycool322** [comment]
Okay thanks
