### ISSUE TITLE
Liked songs that disappear / are limited to 300?

### ISSUE THREAD

**Issue by manstyB4III** [whoeevee/EeveeSpotify#70]
In the Liked Tracks playlist, I have 3983 tracks as you can see on the screen of the Spotify web player. In advance, on the app, I am limited to 300 and these are 300 random songs among the 3983.

First screen is that of spotify in the web player
Second one is on iPhone

![image](https://github.com/whoeevee/EeveeSpotify/assets/129116507/63b461cd-16a3-463e-95fb-bb44069fcedc)
![image](https://github.com/whoeevee/EeveeSpotify/assets/129116507/b33a3da0-5d45-4205-a8b8-ba1ac7a84915)

**Comment by heelmarc** [comment]
did you managed to fix it?

**Comment by manstyB4III** [comment]
It came back on its own after relaunching the application during the day.

**Comment by yodaluca23** [comment]
This is a native Spotify mobile app issue
