### ISSUE TITLE
Known issues

### ISSUE THREAD

**Issue by stefanodvx** [whoeevee/EeveeSpotify#72]
- Some songs have translated lyrics instead of original lyrics. Example:  https://open.spotify.com/track/0Pq8CSHDXInMK8atOkWSAv. As discussed on group chat, track title should have space characters stripped before searching via Genius API.
- Songs have incorrect coloring and it's impossible to view lyrics while sharing. I occured this issue only on local files for the moment. See video: https://github.com/whoeevee/EeveeSpotify/assets/69367859/96629d42-880e-4f26-b7c0-c3910617879f
- Download tracks locally. This is not an issue, but an idea. I understand that offline mode could not be implemented, but a free account could actually download the track directly from Spotify, and there's no DRM. Check out ZSpotify project: https://github.com/limaceous-bushwhacker/zspotify/blob/97c281252213b88ff3b248954a3db3642e4a0e88/zspotify.py#L341

This is the best tweak for Spotify I've seen so far, maybe it needs more customization just like Spotilife (a "True Shuffle" option would be good). Keep it up <3

**Comment by TheDoctor200** [comment]
That are cool features 👍

**Comment by asdfzxcvbn** [comment]
first 2 should be fixed in v3.0
