### ISSUE TITLE
Spotify crashing when locking the device and playlist

### ISSUE THREAD

**Issue by THICCD0GG0** [whoeevee/EeveeSpotify#73]
This is really weird bug and I can’t fix either with changing location that I saw some fixes nothing worked . Any fixes?

**Comment by HandsomeBoba** [comment]
got this too, tried even different versions. Approx, 15-22seconds after i put my phone on Standby mode Spotify stops playing Music. After i turn on my phone and go to Spotify it doesn‘t play any Music until the App is restarted.

**Comment by whoeevee** [comment]
did you disable background app refresh

**Comment by HandsomeBoba** [comment]
well no, i have disabled it now and it seems to work. It did work before too though, weird that it randomly start closing in standby. Anyway, seems to have fixed it. Thanks for everything you did

**Comment by HandsomeBoba** [comment]
> did you disable background app refresh

quick update, i did. doesn‘t work still.
