### ISSUE TITLE
New 3.0 is Crashing when opening lyrics.

### ISSUE THREAD

**Issue by hazchempop** [whoeevee/EeveeSpotify#78]
Iphone 13 Pro Max ios 17.4.1

Just automatically force closes app when i scroll down to Lyrics.

**Comment by whoeevee** [comment]
does this happen with all sources?
install debug IPA and send the crashlog

**Comment by hazchempop** [comment]
> does this happen with all sources?
> 
> install debug IPA and send the crashlog

It has stopped for now, happened to LRCLIB. Is it easy to setup token for Musixmatch match and use Lyric Source? i have no idea what "MITM" is from the instructions

**Comment by whoeevee** [comment]
it’s pretty easy
there will be a guide soon
