### ISSUE TITLE
HOW TO GET SYNCED LYRICS TUTORIAL (MUSIXMATCH)

### ISSUE THREAD

**Issue by fugegate** [whoeevee/EeveeSpotify#79]
Link to hacked premium file : https://appdb.to/details/fcbddda606fbca279dc022c0340f1e391352639a

https://github.com/whoeevee/EeveeSpotify/assets/46111388/6702b699-4899-4e82-a3ed-10c72fbd80f7

**Comment by whoeevee** [comment]
fine but you don’t need hacked Musixmatch app and can install it from the App Store
