### ISSUE TITLE
(feature request)

### ISSUE THREAD

**Issue by fugegate** [whoeevee/EeveeSpotify#80]
If MUSIXMATCH or lrclib cannot find lyrics for a certain song, instead of saying "couldn't load lyrics for this song" it should switch to Genius Lyrics api.

**Comment by bzzzzzzzq** [comment]
best idea. DO THIS

**Comment by whoeevee** [comment]
will do in the next update

**Comment by YHangbin** [comment]
Please consider allowing customization for selecting the range of lyrics search in the design of the feature, as there are many errors in the Chinese lyrics returned by Genius Lyrics.

**Comment by yodaluca23** [comment]
@whoeevee You could have instead of a section menu, a priority menu, where you can slide the three sources around and the top most one is the first place it checks, then second, then third...

**Comment by zippy2005** [comment]
> Please consider allowing customization for selecting the range of lyrics search in the design of the feature, as there are many errors in the Chinese lyrics returned by Genius Lyrics.

just use MUSIXMATCH

**Comment by whoeevee** [comment]
3.1 is out
