### ISSUE TITLE
App crashes when opening the full player

### ISSUE THREAD

**Issue by officiallor** [whoeevee/EeveeSpotify#81]
When i open the full player that has the cover, sometimes it crashes directly and sometimes when I tap on the cover or control buttons. The mini player doesn't seem to have an issue. It seems like a lyrics functionality issue. 

8.9.38
iOS 17.5 (21F79) - beta

**Comment by whoeevee** [comment]
install debug IPA and send the crashlog

**Comment by officiallor** [comment]
I couldn't reproduce it with any of the latest releases from GitHub. The one that I was using was from an ipa repository. 😅
I'll try installing the releases from here first before opening a ticket in the future in case that the repository has issues.
Thank you for your time
