### ISSUE TITLE
(FEATURE REQUEST)

### ISSUE THREAD

**Issue by KeyboardChampion** [whoeevee/EeveeSpotify#84]
For me, the open in Spotify extension barely works, so instead of that, well it needs to be fixed, I press it and most of the time it just says "Hello world" and nothing happens. It would be helpful for a share extension, maybe easier too. Where I could press share and click the Spotify and it would open the link in Spotify. Either that or fix the extension.

**Comment by asdfzxcvbn** [comment]
> I press it and most of the time it just says "Hello world" and nothing happens.

you dont need to press it. it will automatically prompt you to open spotify when it detects a compatible spotify link

> It would be helpful for a share extension, maybe easier too. Where I could press share and click the Spotify and it would open the link in Spotify.

not possible in a sideloaded environment (without changing app id and bundle id). you would need trollstore to make this work, but you wouldnt need the Open in Spotify extension if you had TS anyway..
