### ISSUE TITLE
Lyrics not working

### ISSUE THREAD

**Issue by Pangaulin** [whoeevee/EeveeSpotify#87]
lrclib and musixmatch lyrics don't work, they always switch to default limited spotify lyrics

**Comment by daddycool322** [comment]
Can you try with Smooth Criminal - Michael Jackson and do a screenshot ?

**Comment by Pangaulin** [comment]
It's work, idk why

**Comment by Pangaulin** [comment]
It doesnt work on some songs am using lrclib 
![Uploading 329780256...]

**Comment by Pangaulin** [comment]
I guess it's work, lrclib doesnt find the song, ty

**Comment by daddycool322** [comment]
The lyrics isn't available on lrclib. 
That's the reason you see that.
You need to change to Genius or MusixMatch (but for Musixmatch you need a mobile user token)

**Comment by whoeevee** [comment]
If the tweak is unable to find a song or process the lyrics on LRCLIB, you'll see the original Spotify one
