### ISSUE TITLE
Tweak quit working after a day (offline.bnk not found)

### ISSUE THREAD

**Issue by Bryceshaw06** [whoeevee/EeveeSpotify#9]
Hello, thanks for making this tweak! I installed when it first came out and had no issues. Without updating, I used it for a few days until the premium quit working. I reinstalled the app, but had no success. I updated to the latest versions (objective-c and swift) but they both didn't fix the issue. 

When I open the app upon reinstalling, it says "An offline.bnk file was not found. Please log in and restart the app when you're done!" I've logged out and back in many times, and tried closing out the app a lot too. My old Spotify version with Spotilife still works excellently. I am using the provided ipa and ESign to install it. Let me know if you have any ideas of things to try. Thank you!

**Comment by asdfzxcvbn** [comment]
could you try the objc 1.2 release that's about to come out?

**Comment by Bryceshaw06** [comment]
Same problem unfortunately :(

**Comment by bachig26** [comment]
> This time, the premium tab is there though.

i think this is same as my issue #8.
with v1.2, it works fine.
i'll explain based on my experience with v1.2.

with `objc v1.2` on my iOS 17.4.1 iPhone, I did have seen the offline.bnk popup and i saw that premium turned into free couple of times after restarting the app couple times. then i noticed that my login is there from my previous installs. so i logged out and logged in again. and then it worked perfectly fine.

with `swift v1.2`on my iOS 15.8.2 iPhone, it just worked directly without any hindrance like objc version. i just logged in and restarted the app. i worked perfectly fine.

**Comment by Bryceshaw06** [comment]
Interesting update: I installed with Altstore and it worked without an issue. This will be fun to troubleshoot. At least it's just an ESign issue, though

**Comment by bachig26** [comment]
> Interesting update: I installed with Altstore and it worked without an issue. This will be fun to troubleshoot. At least it's just an ESign issue, though

yeah, i also did it with altstore. i forgot to mention.

**Comment by asdfzxcvbn** [comment]
> Interesting update: I installed with Altstore and it worked without an issue. This will be fun to troubleshoot. At least it's just an ESign issue, though

did you remove the embedded mobileprovision?

**Comment by Bryceshaw06** [comment]
I tried it with both ( the assign option “Remove mobileprovision after
signing”)

**Comment by bachig26** [comment]
@asdfzxcvbn @whoeevee hi, after these ~5hrs after the v1.2 release, still the tweak switches to free version. and i need to restart the app to use the app as indented. i experienced this issue with both v1.2's.
for example,
1. one time when i was exploring the settings page and the app displayed three dot loading animation and turned into free version. it was fixed after a restart.
2. sometimes, while starting the app as new after sometime, it opens as free version, this also fixed if closed and restarted.

**Comment by asdfzxcvbn** [comment]
> @asdfzxcvbn @whoeevee hi, after these ~5hrs after the v1.2 release, still the tweak switches to free version. and i need to restart the app to use the app as indented. i experienced this issue with both v1.2's.
> 
> for example,
> 
> 1. one time when i was exploring the settings page and the app displayed three dot loading animation and turned into free version. it was fixed after a restart.
> 
> 2. sometimes, while starting the app as new after sometime, it opens as free version, this also fixed if closed and restarted.

strange. i have a new idea (for the billionth time lol) and will (hopefully) release v1.3 today

**Comment by asdfzxcvbn** [comment]
actually, scratch that. it works fine for the most part, and those tiny bugs can be fixed with a restart (or using altstore, which solved the problem this issue was opened for). i don't think i'll work on the tweak anymore, but if eevee decides to update the swift branch, i'll still keep the objc branch up to date

**Comment by caafurcias42** [comment]
It’s unfortunate you won’t work in this issue anymore, it switches to free 2-3 times a day for me.

**Comment by asdfzxcvbn** [comment]
> It’s unfortunate you won’t work in this issue anymore, it switches to free 2-3 times a day for me.

over the span of 24 hours? or just 12-16, etc? and how often does it happen, like how much time passed in between each time?

**Comment by caafurcias42** [comment]
Let’s say I use it 8 times a day for a total of 2 hours total. It happened around 3-4 times. I ended up going back to an old version until it gets more stable. I’m on 17.4.1 with iPhone 13

**Comment by asdfzxcvbn** [comment]
> Let’s say I use it 8 times a day for a total of 2 hours total. It happened around 3-4 times. I ended up going back to an old version until it gets more stable. Also, for me it just reverts to a free version, no error given. I’m on 17.4.1 with iPhone 13

weird. i'm jailbroken with the deb installed and it doesn't ever revert while in the background. occasionally it can revert if i reopen the app but it works by relaunching.
