### ISSUE TITLE
Gets stuck on previous song when listening on another device

### ISSUE THREAD

**Issue by yodaluca23** [whoeevee/EeveeSpotify#90]
If you're listening on a different device, and controlling from this app on your phone, when it goes to the next song, it does not 
update on the app unless you force quit, or move it to playing on another device... It only seems to have started with the latest 3.0 release, I am using Musixmatch with User ID, if that makes any difference...

**Comment by yodaluca23** [comment]
Note, this does not happen if you are originally playing with this app and then from the app switch to a new device. Only if it already was playing on another device then you try to control from this app.

**Comment by whoeevee** [comment]
Couldn't reproduce the issue. Did you try common solutions like reinstalling the apps? It's weird also because the tweak shouldn't affect song updating

**Comment by yodaluca23** [comment]
> Couldn't reproduce the issue. Did you try common solutions like reinstalling the apps? It's weird also because the tweak shouldn't affect song updating

Yes, I completely reinstalled, signed out and back in. It's really weird, cause it only happens sometimes, usually if you have the app in the background... Wait... I just tested it, it's because I was on low power mode... I'm dumb, sorry for wasting your time.

But at least this is here for others, if your on low power mode, and the app is in the background, the songs won't update when controlling remote devices till you force it to...
