### ISSUE TITLE
Only shuffle with google external device

### ISSUE THREAD

**Issue by emaschi5** [whoeevee/EeveeSpotify#91]
As the description, with the old mod Spotify app I can cast the music on google home, with this version I can cast too but I can choose the queue or move forward the played song
![image](https://github.com/whoeevee/EeveeSpotify/assets/160335663/0f3df617-16b9-4190-9b1b-74c89b46828e)

**Comment by emaschi5** [comment]
When using connect only 6 skip are available, no seek bar and no queue available, I’m on 3.0

**Comment by yodaluca23** [comment]
> When using connect only 6 skip are available, no seek bar and no queue available, I’m on 3.0

That'd because it's not actually playing from your phone anymore, but that device, and ur phone is remote. You have two options, use that device of Bluetooth speaker that way it actually from your phone or get modded Spotify on that device too.

**Comment by emaschi5** [comment]
Ok thanks, I was asking for a check because in another version of Spotify all the features are working, in the cypwn version for example (older version of Spotify ) but the lyrics feature work only on this version (that is perfect except the connection mode)
