### ISSUE TITLE
(feature request) 2

### ISSUE THREAD

**Issue by fugegate** [whoeevee/EeveeSpotify#93]
Would it be possible to implement a custom DJ button not using Spotify's AI Dj but perhaps something else like Radiant(getradiant.app) or something like Mixonset?(https://apps.apple.com/us/app/mixonset-music-clip-dj-mixer/id1477282813)
And for the AI playlist maybe you could implement something like playlistable(playlistable.io) if possible.
And also for the Jam feature maybe something like Juky(Juky.app) could be implemented if possible.
These are all features that would be amazing but obviously not necessary

**Comment by asdfzxcvbn** [comment]
nope

**Comment by fugegate** [comment]
> nope

Could I ask why?

**Comment by asdfzxcvbn** [comment]
EeveeSpotify is a tweak to give you free premium, lyrics were implemented due to it being a popular basic feature, however everything else will likely be ignored

**Comment by samuelawachie** [comment]
And you need to learn to name your threads better with more descriptive titles. Just saying "feature request" doesn't cut it.
