### ISSUE TITLE
Eevee (Swift 3.0 version) does not work with AltStore

### ISSUE THREAD

**Issue by AntoDipp** [whoeevee/EeveeSpotify#95]
Hi, I installed the new version of Eevee (Swift 3.0) using AltStore (extension removed due to AppID limit) but once Spotify is loaded and restarted, the app remains in free version. I tried to close and reopen, remove the update in the background but nothing, it always remains free. I downgraded to Swift version 2.1 and Eevee is back to work! Too bad but for the new version with the synchronized lyrics not working 😕.

**Comment by whoeevee** [comment]
do you see EeveeSpotify section in settings? or any popups?

**Comment by AntoDipp** [comment]
EeveeSpotify section is visible but changing an option crashes the app. I only get a pop-up written to re-enter the app but then it disappears and never reappears once I get back into the app. Not even the reset date one appears.

**Comment by whoeevee** [comment]
did you try reinstalling the app?

**Comment by AntoDipp** [comment]
Yes, using Scarlet also works. AltStore on the other hand doesn't really go.

**Comment by Blockr22** [comment]
I am using it with Sidestore, which is a fork of altstore & it works fine. U might need a full reinstall

**Comment by asdfzxcvbn** [comment]
> Yes, using Scarlet also works. AltStore on the other hand doesn't really go.

weird. there really should be no real difference in being able to apply the premium. maybe this is just some bad luck thing? someone else said it worked for them on sidestore. gonna close since we don’t know what the issue is

**Comment by AntoDipp** [comment]
Hello! I reopened this problem by attaching a video of all the steps I follow to install the new version of Eevee and show the problem; maybe it could help developers figure something out. 

https://github.com/whoeevee/EeveeSpotify/assets/52698241/8aba4e77-d7ca-43d5-8a9f-a2a7c6963f10
